cmd/bank-vaults/unseal.go
Without PFlag lookup `--init` command-line parameter has no effect
=> Add missing PFlag lookup

vault/vault.go
=> Fix Vault token renewal error because of a blocked channel

.circleci/config.yml, operator/deploy/cr.yaml, operator/pkg/apis/vault/v1alpha1/types.go, operator/pkg/stub/handler.go
If someone defines posts a Vault CRD with the following configuration block all operator related Vault instances will drop TLS support and will not generate any certificates for Vault:
```yaml
config:
listener:
tcp:
address: "0.0.0.0:8200"
tls_disable: true
```
=> Operator: optional Vault TLS

pkg/vault/vault.go, vault-config.yml
Added support for cross-account access under AWS auth config. Ref #139.
=> cross account support for aws auth

cmd/bank-vaults/unseal.go, operator/deploy/cr-etcd-ha.yaml, operator/pkg/apis/vault/v1alpha1/types.go, operator/pkg/stub/handler.go, pkg/vault/vault.go
This feature gives us the option to workaround current **StatefulSet limitations** around updates
See: https://github.com/kubernetes/kubernetes/issues/67250
By default it is set to **false**.
Fixes: #154
=> Support StatefuleSet upgrade with workaround

operator/pkg/apis/vault/v1alpha1/types.go, operator/pkg/stub/handler.go
If etcd is chosen as a back end, the size is hard coded to 3
https://github.com/banzaicloud/bank-vaults/blob/master/operator/pkg/stub/handler.go#L608
This might cause issues if quorum is lost https://github.com/coreos/etcd-operator/issues/1972, having a size of 3 only tolerates the failure of 1 etcd pod.
Added support in the spec for etcd size
=> etcd size for quorum fault tolerance

operator/pkg/apis/vault/v1alpha1/types.go
As of vault 0.11.0 MySQL storage supports HA.
https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#0110-august-28th-2018
The code isn't tested, can someone test it?
=> Added mysql to HA storage type's

.licensei.toml, Gopkg.toml, README.md, pkg/vault/operator_client.go, vault-config.yml
Signed-off-by: Oleksandr Stepanov <alexandrst88@gmail.com>
We very like this tool, so we were trying to use it, but faced with the issue, there is not possible to enable plugins via it. 
This PR provides an ability to enable Vault Plugins: https://www.vaultproject.io/docs/internals/plugins.html
Requirements:
- **Vault Plugin Directory must be set** otherwise, vault will throw an error.
Question: 
- We have some concern about using `getOrDefault` function? We are thinking about creating a new function like `getValue` or `getStringValue`, because, fields: command, plugin_name and sha256 are obligatory. 
- Also, should we add an output of existing plugins as it did for `configureSecretEngines` method?
We did tests with this plugin: https://github.com/immutability-io/vault-ethereum. 
If you …
=> Added ability to enable plugins via bank-vaults

operator/pkg/apis/vault/v1alpha1/types.go, operator/pkg/stub/handler.go
Hello,
Here are some additions to the operator to allow a generic fluentd sidecar container. This was brought up in this issue https://github.com/banzaicloud/bank-vaults/issues/163 . We plan on using this sidecar to handle audit logging.
Everything related to this is purely optional and disabled by default.
Please let me know if you have any questions.
=> operator: add generic fluentd logging sidecar

cmd/bank-vaults/configure.go, pkg/vault/operator_client.go
This solves a race condition when Vault hasn't mounted the auth backends/secret engines before configuring but is mounting them during configuration.
=> Configurer needs to check if Vault is active before configuring

operator/README.md, operator/pkg/apis/vault/v1alpha1/types.go, operator/pkg/stub/handler.go
I have a special case. Which have to use existing etcd as vault's backend storage. 
So use EtcdSize < 0 to let operator not create new etcd cluster. And not override any setting under etcd storage section.
=> Add ability to use existing etcd cluster

README.md
After the help @bonifaido gave me in Issue #180, I think it would be valuable to have a PKI example in the example External Config.
=> Add PKI config to example

operator/pkg/apis/vault/v1alpha1/types.go, operator/pkg/stub/handler.go
This fixes #187 
**Edit:**
This allows users to customize the `securityContext` of the Vault Statefulset.
```yaml
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
name: "vault"
spec:
size: 1
image: vault:0.11.0
bankVaultsImage: banzaicloud/bank-vaults:latest
securityContext:
runAsUser: 100
fsGroup: 100
```
=> Add Security Context to Vault CR

README.md
The code required s3 return `NoSuchKey` error when perform `keyStoreNotFound` check. But if the user/role don't have `s3:ListBucket` permission on bucket level. s3 will return `AccessDenied` instead of `NoSuchKey`. It will cause an error returned. And the unseal key won't upload to s3.
End result is the vault initialized. But no any unseal key.
=> Add required s3 permission on readme page

pkg/vault/operator_client.go
Sorry, is me again...
On SSH secret engine config. There have a `default_extensions` to contain some child config.
Example:
```
type: ssh
path: ssh-client-signer
description: SSH Client Key Signing.
configuration:
config:
- name: ca
generate_signing_key: "true"
roles:
- name: infra
allow_user_certificates: "true"
default_extensions:
permit-pty: ""
permit-port-forwarding: ""
permit-agent-forwarding: ""
allowed_users: "*"
key_type: "ca"
default_user: "ubuntu,admin,ec2-user"
ttl: "1h"
```
But it cause error `json: unsupported type: map[interface {}]interface {}`.
So have to check and replace by `map[string]interface{}` before use it.
=> Support child dict on secrets engine's configuration

README.md, pkg/vault/operator_client.go
This PR adds support for Approle Authentication Backend.
An example config:
```yaml
auth:
- type: approle # https://www.vaultproject.io/docs/auth/approle.html
roles:
- name: default
policies: allow_secrets,allow_certs
secret_id_ttl: 10m
token_num_uses: 10
token_ttl: 20m
token_max_ttl: 30m
secret_id_num_uses: 40
```
```bash 
$ vault read auth/approle/role/default/
Key                   Value                          
bind_secret_id        true                           
bound_cidr_list       null                           
local_secret_ids      false                          
period                0                              
policies              ["allow_certs","allow_secrets"]
secret_id_bound_cidrs null                           
secret_id_num_uses    40 …
```
=> Add Approle Auth backend support

Gopkg.lock, Gopkg.toml, pkg/vault/operator_client.go, vault-config.yml
The config block was ignored until now (except options, which was used for KV version 2).
Fixes: #180
=> configurer: support ConfigMountInput in secret engine mount requests

operator/deploy/cr-etcd-ha.yaml, operator/pkg/apis/vault/v1alpha1/types.go, operator/pkg/stub/handler.go
This allows users to add `spec.etcdAnnotations` to the Vault Custom Resource object which is used to annotate the `etcdcluster` Custom Resource accordingly.
This is specifically for the `etcd.database.coreos.com/scope=clusterwide` annotation, however CoreOS allows for arbitrary annotations to the object so I figured I'd carry on with that and allow full passthrough of annotations.
Example usage:
```yaml
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
labels:
version: latest
group: security
app: vault
metadata:
name: vault
spec:
size: 3
image: vault:0.11.0
bankVaultsImage: banzaicloud/bank-vaults:latest
securityContext:
runAsUser: 100
supportUpgrade: true
etcdAnnotations:
etcd.database.coreos.com/scope: clusterwide
unsealConfig:
kubernetes:
secretNamespace: default
...
```
This …
=> Add etcdAnnotations field to Vault CR to annotate etcdcluster

README.md, operator/deploy/cr-credentialFromSecret.yaml, operator/pkg/apis/vault/v1alpha1/types.go, operator/pkg/stub/handler.go
Add config for set secrets to bank-vaults's environment variables. Use case can reference readme example's `my-mysql` username and password.
=> Set secrets to bank-vaults's environment variables

pkg/vault/client.go
The Vault token file path can be defined now.
=> client: introduce VAULT_TOKEN_PATH

Gopkg.lock, Gopkg.toml, README.md, operator/deploy/cr-aws.yaml, operator/deploy/cr-azure.yaml, operator/deploy/cr-credentialFromSecret.yaml, operator/deploy/cr-etcd-ha.yaml, operator/deploy/cr-gcs-ha.yaml, operator/deploy/cr-podAntiAffinity.yaml, operator/deploy/cr.yaml, pkg/vault/operator_client.go, vault-config.yml
Updates the API client used to talk with Vault 1.0.0.
Fixes: #222 Depends on: https://github.com/hashicorp/vault/pull/5913
=> Update to Vault 1.0.0

Gopkg.lock, Gopkg.toml
We can use the upstream Vault version now, the plugin API backward compatibility issue has been resolved.
=> WIP: Vault API 1.0.1

operator/README.md, operator/deploy/cr.yaml, operator/pkg/apis/vault/v1alpha1/types.go, operator/pkg/stub/handler.go
Fixes: #235 
With this change, persistent volumes can be attached to the Vault pods through the CRD definition, useful for the file based Vault backend.
=> operator: support Volumes in Vault CRD

README.md, cmd/vault-secrets-webhook/main.go, deploy/test-deployment.yaml
Breaking change! Annotations have to be moved to the `PodSpec` level as seen in the example deployment `hello-secrets`.
Fixes: #254 
The new Helm chart has to be used from now on: https://github.com/banzaicloud/banzai-charts/pull/584
=> webhook: mutate pods only for correctness

Makefile
CircleCI builds are holding a branch name containing slashes, this breaks the build as seen in: https://github.com/banzaicloud/bank-vaults/pull/253
```bash
#!/bin/bash -eo pipefail
make docker
make docker-operator
docker build -f Dockerfile.vault-env -t banzaicloud/vault-env:latest .
docker build -f Dockerfile.webhook -t banzaicloud/vault-secrets-webhook:latest .
docker build -t banzaicloud/bank-vaults:pull/253 -f Dockerfile .
invalid argument "banzaicloud/bank-vaults:pull/253" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
Makefile:58: recipe for target 'docker' failed
make: *** [docker] Error 125
Exited with code 2
```
=> Remove slashes from VERSION variable

README.md, operator/deploy/cr.yaml, operator/pkg/controller/vault/vault_controller.go
According to vault server -help, -log-level can be set with VAULT_LOG_LEVEL. There is no need to set it explicitly.
Also, fix link to Examples in README.md.
=> Allow to control vault's log level with env

operator/deploy/cr-nodeAffinity.yaml, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go
- Refactor getPodAntiAffinity for backwards compatibility
- Add nodeAffinity vault configuration option
- Add getNodeAffinity and assign output to the spec
- Add deploy example.
=> Add support for nodeAffinity for vault containers

pkg/vault/operator_client.go
Currently, roles are being written to the default Kubernetes auth path, `auth/kubernetes`. This change will have the method `configureKubernetesRoles` use the value of `path` instead, as done in `kubernetesAuthConfig`.
=> Use `path` when configuring Kubernetes auth roles

README.md, pkg/vault/operator_client.go
Like "ad", "alicloud", "azure", "gcp", "gcpkms", "kv" secret engine
=> Add support to config secret engine, which nosub-path after config

README.md
Very short description how to encrypt root token stored in S3 and encrypted with AWS KMS service.
I am not sure if you will accept such documentation update, I really wanted to have vault token, before I will try to use AWS auth plugin. It took me some time to figure out proper decryption process, maybe it will be useful for someone else.
I know it is kinda against recommendations described a few lines earlier. So if you will reject this PR it is fine ;-)
=> Describe how to encrypt root token stored in AWS

operator/pkg/apis/vault/v1alpha1/vault_types.go
Setup with ha_storage should be equal to setup with storage and ha_enabled flag set to true, as described per official documentation https://www.vaultproject.io/docs/configuration/index.html#ha_storage.
Currently, operator throws error:
```
..."error":"failed to fabricate StatefulSet: more than 1 replicas are not supported without HA storage backend"...
```
In setup like:
```
...
storage:
s3:
bucket: vault
ha_storage:
dynamodb:
table: vault
...
```
Which is valid from 1.0.0(?).
=> Allow to use ha_storage in replicated vault setup

operator/cmd/manager/main.go
It seems that the WATCH_NAMESPACE environment variable is not set when the value
is set to `""` in deployment. This lead to a crash of the operator. Watching the
entire cluster in this case seems like a better default.
=> Watch the entire cluster if the watched namespace is not set

README.md
Previous example didn't worked (at least with vault 1.0.x). Now it works fine and sets proper TTL's.
I am not sure if `options` is specific for Vault <1.0.x, I am using 1.0.2. If it is the case, we may consider adding some side note. However, all other examples use config instead of options.
=> Fix PKI engine TTL configuration example

operator/cmd/manager/main.go
With this fix, the operator will resync in every minute, so if resources are deleted (for example TLS certificates) they will be recreated relatively quickly.
Fixes: https://github.com/banzaicloud/bank-vaults/issues/318
=> operator: make sync_period configurable

pkg/tls/tls.go
Was that intentional to have 2038? If yes then I can close this pr. Isn't 2048 the standard?
=> Update defaultKeyBits to 2048

cmd/vault-env/main.go, cmd/vault-secrets-webhook/main.go
Adds rudimentary support for update / write style requests to the webhook.
It wasn't possible to generate certificates via the webhook as this required a write to the `intermediate-ca/issue/cert-name` .
Added write support to vault-env via a prepend to the vault URI.
The proposed prepend that has been implemented is `>>`
If you wanted to issue a new cert you would use the URI `>>vault:intermediate-ca/issue/cert-name`.
It might also be good to support data in the write (it is currently an empty write). This could be done via an append to the path. (E.G. `>>vault:intermediate-ca/issue/cert-name{}` where the {} is json data)
=> Env update

operator/pkg/controller/vault/vault_controller.go
With the help of the wrapper script we are able to provide correct HA Cluster address:
https://github.com/hashicorp/docker-vault/blob/master/0.X/docker-entrypoint.sh#L12
This way the standby node says:
```
$ kubectl exec -it vault-0 sh                                                                             
/ # vault status
Key                    Value
---                    -----
Seal Type              shamir
Initialized            true
Sealed                 false
Total Shares           5
Threshold              3
Version                1.0.3
Cluster Name           vault-cluster-4f0be265
Cluster ID             9399bbe1-dcaf-44fc-0d90-6cf0275a94c5
HA Enabled             true
HA Cluster             https://10.1.0.153:8201
HA Mode                standby
Active Node Address …
```
=> use VAULT_CLUSTER_INTERFACE to have correct HA Cluster address

Dockerfile, Dockerfile.operator, Dockerfile.webhook
fixes: #367 
relates: https://github.com/banzaicloud/banzai-charts/issues/717
=> Use uid instead of username due to runAsNonRoot securityContext

operator/deploy/secret.yaml, operator/pkg/controller/vault/vault_controller.go
Uses the same pattern as the configmaps, it will be useful when used alongside
sealed-secrets controller (or similar) to push sensitive vault configurations into git
=> Add support for creating vault configurations as Secrets

pkg/vault/operator_client.go
An improvement, so `sts_account` can be an integer in the configuration YAML.
fixes #371
=> always transform sts_account to a string

operator/pkg/controller/vault/vault_controller.go
fix bug in `0.4.15-rc.1` that I introduced when setting custom ports, the slice is overwriting. Need to append to the declared slice.
=> append to the slice, not overwrite the slice

pkg/vault/operator_client.go
Issue caused by YAML parser and Json Marshalling.
Already happening int he "configure secret" generic function https://github.com/primeroz/bank-vaults/blob/ffc94f13794be5429969a420197700f3e80cb439/pkg/vault/operator_client.go#L979
=> Fix json: unsupported type: map[interface {}]interface {} for jwt nested maps

cmd/bank-vaults/configure.go, cmd/bank-vaults/unseal.go
This PR should eliminate flaky CI failures.
=> Reduce unseal periods (and logs as well) to be more resilient

pkg/vault/operator_client.go
This will avoid confusing the configurer with `path already in use`
```
ERRO[0011] error configuring vault: error configuring auth methods for vault: error enabling approle auth method for vault: Error making API request.
URL: POST http://127.0.0.1:8200/v1/sys/auth/approle
Code: 400. Errors:
* path is already in use
```
=> Trim / at the end of path if present

cmd/bank-vaults/unseal.go, pkg/vault/client.go, pkg/vault/operator_client.go
Fixes: #400 
The 5 seconds global HTTP timeout caused init to fail sometimes (mostly when using remote backends).
=> Move init outside the loop + increase http.Timeout

cmd/bank-vaults/init.go, cmd/bank-vaults/unseal.go, cmd/bank-vaults/util.go, pkg/vault/operator_client.go
The kv backend changes the way user IAM policies and other access rights have to be set up, so I have moved it behind a feature flag, people can enable it on their own will.
=> move kv backend tests behind a flag

cmd/bank-vaults/configure.go
Fixes #405 
* Watch multiple directories
* Reload on WRITE on Real Files
* Reload on CREATE on Kubernetes re-link of ..data for any number of files in the configMap
* The Events watching does not need to run in its own GO thread since the whole function is already running as such
* We don't have access to the Filename in the event watching but just the event.Name
* For real files we can safely use that
* For Kubernetes Configmaps we need to path the basepath to a saved map of DIR: FILES and just reload all files
=> Make Watch function work on multiple Directories

operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go
Only the init/unseal container should get the unseal options.
=> operator: configurer shouldn't get unseal options

cmd/vault-secrets-webhook/main.go, deploy/test-deployment.yaml
The vault-agent implementation was broken for a while, this PR addresses that.
- mount_path was missing `auth/`
- ownerReferences wasn't set in agent ConfigMap
- name and namespace was empty for the obj, we get those from other sources now
=> webhook: vault-agent-fix

.circleci/config.yml
Only acceptance test needs to run on `machine` type executor. For everything else, there's `resource_class: small`
=> circleci: minimize machine executor usage

operator/cmd/manager/main.go, operator/deploy/operator-rbac.yaml, operator/deploy/operator.yaml
Prometheus metrics for the Controller are now available out of the box, as described [here](https://github.com/operator-framework/operator-sdk/tree/master/doc/user/metrics)
exposed (useful) metrics are
```
controller_runtime_reconcile_queue_length{controller="vault-controller"} 0
controller_runtime_reconcile_time_seconds_bucket{controller="vault-controller",le="0.005"} 0
controller_runtime_reconcile_time_seconds_bucket{controller="vault-controller",le="0.01"} 0
controller_runtime_reconcile_time_seconds_bucket{controller="vault-controller",le="0.025"} 0
controller_runtime_reconcile_time_seconds_bucket{controller="vault-controller",le="0.05"} 0
controller_runtime_reconcile_time_seconds_bucket{controller="vault-controller",le="0.1"} 0 …
```
=> Enable Controller prometheus metrics

operator/pkg/controller/vault/vault_controller.go
Needed by Prometheus Operator - ServiceMonitor to discover endpoints for monitoring
=> add statsd 9125 port to service

operator/deploy/operator-rbac.yaml
I had this spamming my logs on 0.4.15-rc.13 upgade, 
```
vault-operator 2019-05-02T23:13:10.54981417Z E0502 23:13:10.549486       1 reflector.go:251] pkg/mod/k8s.io/client-go@v0.0.0-20190115164855-701b91367003/tools/cache/reflector.go:95: Failed to watch *v1beta1.Ingress: unknown (get ingresses.extensions)
```
=> watch is required for operator ingresses permissions

cmd/vault-secrets-webhook/main.go
Allow to enable/disable AllowPrivilegeEscalation for injected containers to make it works with psp restricted deployments
Caused by error in replicaset
**is forbidden: unable to validate against any pod security policy: []'**
=> PSP AllowPrivilegeEscalation

pkg/vault/operator_client.go, vault-config.yml
Currently, it is not possible to configure roles for token-based authentication, this PR fixes that. One of the possible use cases is to configure a narrow role for scraping Prometheus metrics.
=> configurer: add support for token auth

pkg/vault/operator_client.go
=> configurer regression: missing config key should't cause failure

pkg/vault/operator_client.go
There is no need to convert the config keys to string. This will lead to decoding errors.
```time="2019-05-16T08:01:17Z" level=error msg="error configuring vault: error configuring secret engines for vault: error parsing config for secret engine: 2 error(s) decoding:\n\n* 'force_no_cache' expected type 'bool', got unconvertible type 'string'\n* 'options' expected a map, got 'string'"```
=> Fix mount config input serialisation

docs/README.md, docs/annotations/README.md, operator/deploy/cr-credentialFromSecret.yaml, operator/deploy/cr-customports.yaml, operator/deploy/cr-etcd-ha.yaml, operator/deploy/cr-podAntiAffinity.yaml, operator/deploy/cr-resource.yaml, operator/deploy/cr.yaml, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go
fixes #357 
* Split Annotations between
* common ( Current annotations field in the spec )
* vaultAnnotations
* vaultConfigurerAnnotations
* Set prometheus annotations only on the pod templates
* Set annotations on Deployment and Statefulset ( needed by my use case )
* Annotate vault and vault-configurer Services
* Annotate vault-tls secret
* Fix port for prometheus-exporter in vault-service ( unrelated ) 
TODO:
* EtcdAnnotations propagation to Pods 
@bonifaido @pbalogh-sa @matyix This is a Draft pull request due the missing etcd annotations ( will do tomorrow ) and to make sure you are happy with the direction this implementation is getting. 
I mostly need this to support the External Reloader for vault when cert-manager letsencrypt tls is updated
=> Extend Annotations support for operator 

cmd/vault-secrets-webhook/main.go
I have run into an edge case where the deployment may have security contexts set and you will need to override the stuff that is hard coded on a case by case basis.
It will require creating a custom image and setting securitycontext runAsUser UID, depending on your preferred approach.
The initContainer podSpec and Container podSpec I think are different so only touching the Container one.
The UID in the hashicorp container is 100:1000 for the user/group `consul-template`
=> allow for annotations overrides of the consul template image

operator/deploy/cr.yaml, operator/pkg/controller/vault/vault_controller.go
Also, add the GKE Ingress controller specific Service annotation in case of HTTPS.
Fixes #482
=> [operator] preserve NodePort for Services

cmd/examples/main.go, operator/deploy/cr-etcd-ha.yaml, pkg/vault/operator_client.go
Secret engine options weren't applied, this was introduced in 0.4.16.
=> configurer: fix regression regarding missing secret engine options

cmd/vault-env/main.go, cmd/vault-secrets-webhook/main.go, docs/mutating-webhook/consul-template.md
This change introduces the annotation `vault.security.banzaicloud.io/vault-ignore-missing-secrets`.
When set to `true` vault-env will not exit the process but will instead log a warning.
Closes #490
=> vault-env: added ability to only warn for missing secrets

cmd/vault-secrets-webhook/main.go
=> Fix configmap name for vault agent if ownerreference does not contain -

cmd/vault-secrets-webhook/configmap.go, cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/secret.go
Added option to mutate kubernetes configMaps. 
Added kubernetes annotation vault.security.banzaicloud.io/mutate-configmap.
This would be useful to use with other charts not supporting things like consulTemplate.
=> [vault-secrets-webhook] Mutate configMaps

operator/deploy/cr.yaml
While the snippet for setting up a PV at the end of this file is only for example usage/testing it needs to use the `Reclaim` policy instead of `Delete` as `Delete` isn't supported for `hostPath` PVs.  Having this set to `Delete` would cause the contents of the PV to *NOT* be deleted even when the PV was deleted which would cause bringing up subsequent iterations of Vault to fail.
=> use 'reclaim' policy for host-path PVs

.dockerignore, cmd/vault-secrets-webhook/main.go, deploy/test-deployment.yaml, docs/mutating-webhook/consul-template.md, hack/acceptance-test.sh, operator/deploy/etcd-operator.yaml, operator/deploy/operator.yaml
Fixes: #515 
- set resource limits on ALL resources
- set a `resourcequota` globally in CI to verify this in the acceptance test
- make the acceptance test more robust
=> specify global resourcequota everywhere

cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/registry/registry.go
Also 
Fix handling other public docker registries without docker creds.
Fix for cases like https://github.com/helm/charts/tree/master/stable/external-dns
=> [vault-secrets-webhook] Fix Handle pod spec when CMD is absent and ARGS are present.

go.mod, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go, operator/pkg/controller/vault/vault_controller.go
This PR addresses https://github.com/banzaicloud/bank-vaults/issues/530
This enables users to update the pod spec for created pods without having to add new fields to the CRD. The merge functionality ensures operator defined fields on the PodSpec are always respected. 
In the future, following a deprecation schedule, we could remove all of these fields and achieve the same results by using only the pod spec. 
```go
PodAntiAffinity       string                        `json:"podAntiAffinity"`
NodeAffinity          v1.NodeAffinity               `json:"nodeAffinity"`
NodeSelector          map[string]string             `json:"nodeSelector"`
Tolerations           []v1.Toleration               `json:"tolerations"`
ServiceAccount        string                        `json:"serviceAccount"` …
```
=> [Operator] Support generic PodSpec fields on CRD

operator/deploy/cr-gcs-ha.yaml, pkg/vault/operator_client.go
fixes #537 
I have been trying to get something to test this in the acceptance-test.sh but failed so far because the only backend i know to test this with is GCP Secrets and it does require a google configuration to be actually mounted and used
=> Add support for "create_only" field to secrets

operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go, operator/pkg/controller/vault/vault_controller.go
For: https://godoc.org/github.com/banzaicloud/bank-vaults/operator/pkg/apis/vault/v1alpha1#VaultSpec
- I have also changed the UnsealConfig to have a default value if not defined otherwise (Kubernetes Secrets).
- The Vault image also has a default Value now (vault:latest)
=> operator: extending godoc based documentation for VaultSpec type

Makefile, operator/deploy/crd.yaml, operator/pkg/controller/vault/vault_controller.go
- The annotation required for object matching must be applied after the patch calculation, but before setting the resource version.
- Pod names must be sorted to avoid unncessary updates.
=> Object matcher and vault CR status matcher fixes

cmd/vault-secrets-webhook/main.go
for a readinessProbe that needs to be defined in the Helm chart, related to: https://github.com/banzaicloud/banzai-charts/issues/888
=> webhook: add healthz handler

cmd/vault-secrets-webhook/main.go
Otherwise, multiple args are getting concatenated, like for Vault:
`vault server -dev server`
which is valid, but very spurious.
=> webhook: Docker CMD should be appended only if Kubernetes args is empty

operator/deploy/operator-rbac.yaml
Bug fix Vault Operator: user forbidden for access metrics in replicaset.app 
Grant access to list replicaset K8s objects.
=> RBAC - allow Operator to list replicasets

cmd/bank-vaults/init.go, cmd/bank-vaults/unseal.go, operator/deploy/cr.yaml, operator/pkg/apis/vault/v1alpha1/vault_types.go
Fixes: #558 
This should prevent a lot of bad Vault initializations, where the unseal keys can't be saved.
=> make preFlightChecks true by default

cmd/vault-secrets-webhook/main.go
Hello
Looks like after https://github.com/banzaicloud/bank-vaults/commit/f4cb1be2a1e48f3a439b7744bca9f36ca0e41440 debug logs can't be enabled by setting `DEBUG` environment variable, it's so sad when you trying to understand why something doesn't work.
=> Allow enable debug logs

cmd/vault-secrets-webhook/main.go
Giving capabilities to serve requests on 443 port should be more easily than configuring firewall rules.
ref: https://github.com/banzaicloud/banzai-charts/tree/master/vault-secrets-webhook#about-gke-private-clusters
=> Configurable webhook listen address

charts/vault-operator/Chart.yaml, charts/vault-operator/values.yaml, charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/values.yaml, charts/vault/Chart.yaml, charts/vault/values.yaml
vault has been bumped to 0.7.1 since 0.7.0 was taken already.
=> helm: bump chart and app versions

charts/vault-secrets-webhook/values.yaml, cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/registry/registry.go
**Description:**
Add environment variables to the vault-secrets-webhook that allow the specification of a default imagePullSecret that will be used when the pod that should get secrets injected does not specify an imagePullSecret (or the specified imagePullSecret does not contain matching credentials).
**Use case:**
We use a centralized docker registry to host our images and to proxy requests to upstream registries. There is only one set of credentials that is configured by default on all our kubernetes nodes so that we do not have to hand out the credentials to our users.
By being able to specify a default secret for the vault-secret-webhook, we can keep a setup where our users do not need to know about the credentials of the central docker registry. But the implementation still retains …
=> [webhook]: Add support for a default imagePullSecret

cmd/vault-secrets-webhook/main.go
partial revert of; https://github.com/banzaicloud/bank-vaults/commit/7338457003d7f019cbd96626d0073fa99bb6c128
does not seem necessary, not sure if this breaks something else but all of the doco (https://github.com/banzaicloud/bank-vaults/search?q=%2Fvault%2Ftls%2Fca.crt&unscoped_q=%2Fvault%2Ftls%2Fca.crt) and implementations is without the '-env', etc.
=> revert breaking change of vault tls path, mounts and env vars

cmd/vault-secrets-webhook/registry/registry.go, docs/mutating-webhook/README.md, operator/deploy/cr-transit-unseal.yaml
**Add support for the `auth` field in docker credentials**
Instead of solely relying on the `username` / `password` fields in the `imagePullSecrets` for a given registry, fall back to the `auth` field if necessary.
I did some research and found no conclusive information if any of the fields are "required". https://github.com/moby/moby/blob/master/api/types/auth.go lists all fields as "omitempty". Doing a `docker login` with a recent version of docker creates a config.json only containing the `auth` field. Using `kubectl create secret docker-registry` creates a secret containing all 3 fields.
**Update webhook documentation**
Add a reference to the default imagePullSecrets to the webhook documentation
**Update operator transit unseal example**
From what I see in other examples e.g. …
=> [webhook,operator] Webhook docker credentials auth + documentation update

charts/vault-operator/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/webhook-deployment.yaml, charts/vault-secrets-webhook/values.yaml
Allow setting pod annotations for the vault-secrets-webhook Helm chart from values.yaml.
Currently there is no way to set pod annotations for the webhook deployment. 
This is helpful to have in many setups, for example: In a cluster where Istio mTLS is required, the readiness probes for the webhook's deployment will fail as the containerPort is intercepted by the Envoy sidecar. Adding the pod annotation `sidecar.istio.io/rewriteAppHTTPProbers: "true"` fixes the probe.
Tested deployment with both default values, as well as values override for `podAnnotations`.
I …
=> [helm vault-secrets-webhook] Allow setting pod annotations

Makefile, charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/templates/webhook-deployment.yaml, cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/registry/registry.go
This small change makes it possible to run the mutating webhook outside of Kubernetes for rapid development with kurun.
Makes the development cycle rapid and the app debuggable.
You need to install [kurun](https://github.com/banzaicloud/kurun) for this.
=> make the webhook locally runnable

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/values.yaml
Fix indentation for the mutating webhook config's `webhooks[].namespaceSelector.matchLabels` field.
Indentation for the `matchLabels` in the mutating webhook config is incorrect:
```yaml
---
namespaceSelector:
matchLabels:
vault-injection: enabled
---
namespaceSelector:
matchLabels:
vault-injection: enabled
matchExpressions:
- key: name
operator: NotIn
values:
- kube-system
- key: name
operator: NotIn
values:
- vault
```
=> [helm vault-secrets-webhook] Fix indentation for webhook selector matchLabels

cmd/vault-secrets-webhook/configmap.go, deploy/test-configmap.yaml
This PR adds the possibility to mutate the binary data of configmaps.
Binary data must be base64 encoded inside vault (https://github.com/hashicorp/vault/issues/1423)
We need to mutate configMaps with binary data
This only work with base64 encoded data inside vault since vault cannot store binary data without encoding
=> webhook/configmap: mutate BinaryData as well

docs/cli-tool/README.md, pkg/vault/operator_client.go, vault-config.yml
Add support for the mount options described at https://www.vaultproject.io/api/system/auth.html#config
This adds a new "options" field to the auth method configuration:
```
auth:
- type: ""
path: ""
options:
listing_visibility: "unauth"
...
config: {}
roles: []
```
The main reason to implement this was the ability to set the listing_visibility option for authentication methods to configure which auth methods will be listed in the web ui.
I am not sure about the error handling guideline, I followed the style I found in the file I modified itself.
=> [config] Add support for auth mount config

charts/vault-operator/Chart.yaml, charts/vault-operator/templates/deployment.yaml, charts/vault-operator/values.yaml, charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/webhook-deployment.yaml, charts/vault-secrets-webhook/values.yaml
Allow setting `pod.spec.priorityClassName` from Helm values for vault-operator and vault-secrets-webhook.
There is currently no way to set pods' priority classes.
=> [helm] Allow setting pod priority class for vault-operator and vault-secrets-webhook

pkg/sdk/auth/auth.go
| Related tickets | https://github.com/banzaicloud/hollowtrees/pull/24
This PR makes TokenStore an optional parameter, which in the case of nil bypasses the token lookup.
To make client usage easier.
=> sdk/auth: make TokenStore optional

operator/pkg/apis/vault/v1alpha1/vault_types.go
Allow PostgreSQL to be a valid HA backend
Fixes #639
=> Add postgresql as an allowed HA backend

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/webhook-deployment.yaml
Webhook internal port did not pass as environment variable into container.
Webhook always using default port instead port from configuration.
=> [charts/webhook] Make listen address configurable

cmd/vault-secrets-webhook/main.go
Parameterizing the PullPolicy for init containers will enable users to specify whether they want to cache images or pull from image repository on init inject.
| Related tickets | N/A Slack
This PR allows for passing in either through CLI args or environment the desired PullPolicy for init containers. 
Some have voiced security concerns at caching docker images locally. Additionally, some organizations have enforced policies that don’t allow for locally cached images.
=> Change hardcoded image PullPolicy

go.mod, go.sum, pkg/sdk/vault/operator_client.go
| Related tickets | fixes #651 
Previously the configurator would check for the existence of a group-alias only by comparing names.
Now a combination of _name_ and _mount accessor_ is used to check for the existence of the alias
Ideally , if this end up being merged into master, it would be great if we could cherry pick it back on a _0.5.2_ release 
This is blocking issue for me ( After upgrading vault i lost one of my auth backend due to https://github.com/hashicorp/vault-plugin-auth-jwt/issues/72 ) but i'd rather not upgrade to 0.6.0-rcX since is an RC with backward breaking changes
=> Support creating group-aliases with same name and different mount_accessor path

.circleci/config.yml, go.mod, go.sum, pkg/vault/operator_client.go
* For external groups the name of the alias is the name in the external datastore, so is possible to have the same group name
from different datastores / group-external
* fix go mod for git.apache.org/thrift => github.com/apache/thrift
| Related tickets | https://github.com/banzaicloud/bank-vaults/pull/652
Backport of https://github.com/banzaicloud/bank-vaults/pull/652 to the 0.5.x branch.
=> [backport 0.5.x] Support creating group-aliases with same name and different mount_accessor path

cmd/vault-secrets-webhook/main.go
Parameterizing the PullPolicy for init containers will enable users to specify whether they want to cache images or pull from image repository on init inject.
| Related tickets | backport of #645 
=> [backport 0.5.x] Change hardcoded image PullPolicy

cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/registry/registry.go
PR allows to passing JSON key for Docker config from ImagePull Secret.
You may rewrite default value prevent duplication of secrets that may used in another automatization.
=> Make ImagePull Docker Config JSON key configurable

cmd/vault-secrets-webhook/registry/registry.go, go.mod
* Fix parsing Docker Image Name with digest
url:
```
eu.gcr.io/project/repo@sha256:7918a9a8ed9aebc21cd8408ae8e1bb6e4aea7ccf81f1bb81147ced54198f074a 
```
parsed as:
```
url=https://eu.gcr.io/v2/project/repo@sha256/manifests/7918a9a8ed9aebc21cd8408ae8e1bb6e4aea7ccf81f1bb81147ced54198f074a
repository=project/repo@sha256
reference=7918a9a8ed9aebc21cd8408ae8e1bb6e4aea7ccf81f1bb81147ced54198f074a
```
* Replace git.apache.org/thrift.git with github.com/apache/thrift
* Incorrect parsing doesn't allow to start jobs/pods/etc
* git.apache.org is not responding
=> Fix parsing of Image Name with digest

Makefile, cmd/vault-secrets-webhook/main.go, go.mod
The chart has to be installed first and after that, we can try port-forwarding with the TLS Secret in the given namespace.
=> webhook: fix the chart install and port-forward execution order

cmd/vault-env/main.go, cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/registry/registry.go, go.mod, go.sum, pkg/sdk/vault/client.go
Added the possibility of logging in JSON format in both `vault-secrets-webhook` as well as in `vault-env`. Furthermore I've added a global hook for adding additional field to all log entries. I added `app` as a first field, for easier debugging.
Enabling JSON logging can be configured through the environment variable `enable_json_log` and can be overridden individually through the annotation: `vault.security.banzaicloud.io/enable-json-log` to control the output of `vault-env`.
Cleanup and parity of log methods were also done. So now logrus is used everywhere.
JSON logging is very …
=> Enable possibility for JSON logging

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/templates/prometheus-monitorservice.yaml, charts/vault-secrets-webhook/templates/webhook-deployment.yaml, charts/vault-secrets-webhook/templates/webhook-pdb.yaml, charts/vault-secrets-webhook/templates/webhook-psp.yaml, charts/vault-secrets-webhook/templates/webhook-service.yaml
| Related tickets | none - fixes configured namespace not being used in the templates
We configured a namespace with helm but the namespace was not used at all points within the templates
=> Added release namespace to webhook helm templates

charts/vault-secrets-webhook/README.md
=> docs: fix typo in readme for vault-secrets-webhook chart

Dockerfile.vault-env
Hi,
I couldn't find out any use of vault inside `cmd/vault-env/main.go` and experimented with removing vault. Sure enough it worked.
The resulting image is now ~24Mb instead of 127Mb.
Hope you find this useful!
vault-env no longer build from `vault:1.2.3` but from `alpine:3.10` to remove the unneeded dependency on vault.
I was wondering why the docker-env image was so big, and found that it included the entire 104Mb vault binary.
=> Slim vault-env docker image size from 127Mb to 24Mb

operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go
| Related tickets | related to #687
The example edited in #687 utilizes volumeMounts to perform unseal and store vault token. These mounts are mounted to the vault container and not to the BankVaults sidecar causing the bank-vaults container to default to kubernetes auth as the file token doesn't exist. This allows one to specify mounts for the sidecar as well.
Allows bank-vaults sidecar to read token from generic volumeMount and not just a secret.
Utilizing a hostPath based token, I was not able to automate the unseal and initialization of vault.
=> [bankVaultsMounts] Allow Mounts for bank-vaults sidecar

cmd/vault-env/main.go
1. Allow revoke vault's token;
1. Move on top checking Args and LookPath.
In some cases Kubernetes auth backend may be configured with long-life token. Setting `VAULT_REVOKE_TOKEN=true` can revoke token.
=> [vault-env] Revoke token

charts/vault/Chart.yaml, charts/vault/README.md, charts/vault/templates/statefulset.yaml, charts/vault/values.yaml
Signed-off-by: Murphy, Kealan <kealan.murphy@aspect.com>
| Related tickets | fixes #689
This PR add's the ability to specify a nodeSelecotr and or toleration's to the Vault statefulset pods when being installed from the Vault chart.
- [x ] Related Helm chart(s) updated (if needed)
=> Adding the ability to define nodeSelector and tolerations

cmd/vault-secrets-webhook/configmap.go, cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/main_test.go, cmd/vault-secrets-webhook/registry/registry.go, cmd/vault-secrets-webhook/secret.go, go.mod, internal/configuration/vaultConfig.go
| Bug fix?       | yes 
I've added two tests, during which I found one bug.
The tests can serve as a starting point for developing a full unit test suite.
Before I spend too much time on writing more tests, I would like some feedback on the style.
I've restructured the code a little bit to make it easier to write tests:
- Use `Kubernetes.Interface` instead of `Kubernetes.ClientSet` in `main.go` to allow mocking
- Moved `vaultConfig` to `internal` package to allow mocking it
- Extracted logic for determining if a env-var has `vault:` or `>>vault:` prefix into a function.
I also found that containers with a `>>vault:` prefix would not get mutated - which seemed strange to me, so I changed it. Let me know if this …
=> Add first unit tests to vault-secrets-webhook

cmd/vault-secrets-webhook/main.go
| Bug fix?        | no 
| New feature?    | yes 
| API breaks?     | no 
| Deprecations?   | no 
| Related tickets | fixes #663 
Attempting to address the situation where PSPs are being enforced for running containers without a root user.  This takes a slightly different approach than other PRs.  Instead of introducing a new annotation, it relies on the user just leveraging the Pod Spec.  
The `PodSecurityContext` (https://godoc.org/k8s.io/api/core/v1#PodSecurityContext) and `SecurityContext` (https://godoc.org/k8s.io/api/core/v1#SecurityContext) types share some attributes, but not all.  One such attribute is the `RunAsUser`, which is fairly important for PSP policies. 
I'm not clear how far we want to take this …
=> webhook: Add RunAsUser functionality within copy-vault-init and containers

pkg/sdk/vault/client.go
If the connection never happened to Vault the `client.Close()` function didn't work properly and the connection loop never stopped.
=> fix Client.Close() state handling

charts/vault/templates/statefulset.yaml
This Pull Request extends initContainer definition with **resource limits** section.
In some Kubernetes clusters it is forbidden to deploy Pods not having resource limits defined, eg: <br/>
`StatefulSet vault-server failed error: pods "vault-server-0" is forbidden: failed quota: mem-cpu: must specify limits.cpu, limits.memory, requests.cpu, requests.memory`<br/>
Which is quite a reasonable approach, **making the entire Kubernetes cluster more secure**. It is mandatory for initConainers to have the resource limits defined - otherwise it is not possible to deploy the chart to a such specific …
=> Added limit resources to initContainer

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/values.yaml
Allow inserting static 64encoded CA and TLS certificates for the mutating webhook - off by default.
```
certificate:
generate: true
server:
tls:
crt:
key:
ca:
crt:
```
I've also changed the helm chart so the top-level `List` object is no longer needed.
The current implementation is causing us some troubles because we use git-ops via helmsman. 
Every time helmsman checks if there’s any changes to deploy (with helm-diff), helm will generate a new certificate and that will cause a redeploy.
=> [charts/vault-secrets-webhook] Add option to use static certicates for vault-secrets-webhook helmchart.

charts/vault-secrets-webhook/templates/apiservice-webhook.yaml
Fixes a missing whitespace after https://github.com/banzaicloud/bank-vaults/commit/5bb0135a3389e5a4bc24191b5caa87197783f2bc, which invalidated the manifest. Without this whitespace, the YAML fails to apply with the following:
```
error validating data: ValidationError(MutatingWebhookConfiguration.webhooks[1]): unknown field "matchExpressions" in io.k8s.api.admissionregistration.v1beta1.MutatingWebhook; if you choose to ignore these errors, turn validation off with --validate=false
```
=> Correct missing whitespace

charts/vault/Chart.yaml, charts/vault/README.md, charts/vault/templates/statefulset.yaml, charts/vault/values.yaml
add the ability to apply additional labels to the vault statefulset  and pods addresses #729
Signed-off-by: Murphy, Kealan <kealan.murphy@aspect.com>
| Related tickets | fixes #729 
This PR gives users the ability to define and apply additional labels to the Vault Statefulset and Pods, this has many use cases. The one use case in particular that would be of use is when using running Vault in Azure and you want to use the aad-pod-identity plugin to allow the vault pod to assume a Managed Identity.
=> add the ability to apply additional labels to the vault statefulset 

cmd/vault-secrets-webhook/registry/registry.go, cmd/vault-secrets-webhook/registry/registry_test.go
Disabling cache for Docker images that tagged as `latest` and for images from containers with ImagePullPolicy `PullAlways`.
With "latest" tag user says, that image can be changed and must be pulled every time; with "Pull Always" option user says, that image has static tag, but might be changed in any time.
First step to done with #726.
=> [webhook] Disable image caching for Policy=PullAlways and ref=latest

docs/cli-tool/README.md, pkg/sdk/vault/operator_client.go, vault-config.yml
| Related tickets | fixes #686 
This PR addresses the lack of ability to configure the Azure Auth mechanism with bank-vaults. The change was a straight forward addition of a case for azure in operator_client.go using the generic Auth and Roles config methods. 
Please be warned I am a first time gopher! To test I ran the the operator locally (thank you @bonifaido for the help) and deployed to a local k8s cluster to ensure both the config and the roles for Azure could be parsed and written to Vault.
=> Add ability to configure azure auth

operator/pkg/controller/vault/vault_controller.go
| Related tickets | fixes #716 
This PR add missing fsGroup to the vault pod.
In the case of the vault pod mounts a pvc, setting up the fsGroup is crucial.
=> Add fsGroup 

charts/vault-operator/Chart.yaml, charts/vault-operator/templates/deployment.yaml, charts/vault-operator/values.yaml, charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/webhook-deployment.yaml, charts/vault-secrets-webhook/values.yaml
As our internal OPA rejected **vault-operator** and **vault-secrets-webhook** charts deployment because of:
> admission webhook "webhook.openpolicyagent.org" denied the request: please set the costCenter label into the Deployment resource
I would like to add the following labels support:
https://github.com/banzaicloud/bank-vaults/blob/master/charts/vault/templates/statefulset.yaml#L10-L12
to the two other charts too.
I have already tested the change, new labels are visible as expected:
vault-secrets-webhook
```
(⎈ |minikube:default)MacBook-Pro-Piotr:charts piotrszwed$ kubectl describe deploymen estranged-antelope-vault-secrets-webhook
Name:                   estranged-antelope-vault-secrets-webhook
Namespace:              default
CreationTimestamp:      Thu, 14 Nov 2019 12:10:58 +0100 …
```
=> Added labels support to vault-operator and vault-secrets-webhook charts (same as like it is already done for vault)

cmd/vault-secrets-webhook/registry/registry.go, cmd/vault-secrets-webhook/registry/registry_test.go, go.mod
Fixing docker.io to index.docker.io in images when checking registry metadata.
Certain applications are targeting the central DockerHub image registry with docker.io, but this way the registry API address gets detected badly.
Unit test added.
=> webhook: fix docker.io addressed images to index.docker.io

cmd/vault-env/main.go, cmd/vault-secrets-webhook/main.go, internal/configuration/vaultConfig.go, pkg/sdk/vault/transit.go
Makes transit path configurable by POD's annotation.
Separating access to transit keys by prefix not so flexible as we want. To access to single transit key (encrypt and decrypt) from UI we needs give access to list all keys from transit secret engine.
We want to give full access to all secret engines created for teams.
=> [webhook] Configurable transit path

charts/vault-operator/Chart.yaml, charts/vault-operator/requirements.yaml, charts/vault-operator/templates/role.yaml
**replicaset** and **deployment** objects in earlier Kubernetes versions were put under _extensions/_ api group not _/apps_, this causes the following errors:
```
"error":"failed to initialize service object for metrics: deployments.extensions \"vault-operator\" is forbidden
"error":"failed to initialize service object for metrics: replicasets.extensions \"vault-operator-588dcd9cb6\" is forbidden:
```
Official documentation:
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16
I think it is better to support both as it is a blocker in many older environments.
TEST:
```
(⎈ |minikube:default)MacBook-Pro-Piotr:charts piotrszwed$ kubectl get clusterrole solemn-crocodile-vault-operator -o yaml | grep -C 3 extensions |head -n 17
- watch
- apiGroups:
- apps
- extensions
resources:
- …
```
=> Fixed replicaset and deployment RBAC issues for Kubernetes < 1.6

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/templates/webhook-deployment.yaml, charts/vault-secrets-webhook/values.yaml
| Related tickets | partially #742 
This PR adds objectSelector in case of K8s version is above 1.15
With this feature, we can skip mutating specified labeled pods.
=> add objecSelector in case of k8s version is above 1.15

charts/vault/Chart.yaml, charts/vault/templates/statefulset.yaml, operator/pkg/controller/vault/vault_controller.go
Fixes #758
Vaults health check parameters for standby changed in https://github.com/hashicorp/vault/issues/7323
| Bug fix?        | yes, when deploying with vault v1.3.0
| API breaks?     | no (tested the change against v1.2.3)
| Related tickets | fixes #758
Adds the boolean values to the vault readiness probe parameters `standbyok` and `perfstandbyok`.
With https://github.com/hashicorp/vault/issues/7323 vault checks the actual value when those parameters are passed and doesn't default to true.
When you spin up a v1.3.0 vault cluster the first node will start normal, though the readiness probe for the second will fail since the parameters are not set properly for …
=> Fix readiness probe for vault v1.3.0

charts/vault-operator/Chart.yaml, charts/vault-operator/values.yaml, operator/deploy/cr-transit-unseal.yaml, operator/pkg/controller/vault/vault_controller.go
Fixing the transit unseal operator example.
The transit unseal example got broken because of another change a few weeks ago and was reported by a community member @funkypenguin already on Slack. Also, the RBAC part was broken entirely (I have tested it on Docker for Mac - which has no RBAC, was a bad idea).
=> operator: various fixes around transit unseal envs and mounts

operator/deploy/cr-raft.yaml, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go
Remove always changing statefulset PVC via volumeClaimTemplates baceuse the `status.phase` is part of the diff always.
It looks pretty ugly in the logs and causes unnecessary updates.
=> operator: PVC diff fix

cmd/vault-secrets-webhook/main.go, docs/mutating-webhook/consul-template.md
Add a new annotation that defines the mount path of Consul template rendered files.
This annotation naming is more exact.
=> Add alias to vault-configfile-path and update docs

cmd/vault-secrets-webhook/registry/registry.go
| Related tickets | fixes https://github.com/banzaicloud/bank-vaults/issues/764, fixes https://github.com/banzaicloud/bank-vaults/issues/761
kubectl appends a specific (and archaic) `/v1/` to the registry address for DockerHub when creating a `docker-registry` type Secret. We detected the matching imagePullSecret for images because of this.
=> webhook: fix for kubectl DockerHub address format

docs/mutating-webhook/README.md
under Running webhook and Vault in different K8S cluster part
clarify a part of the docs that explaining: 
Running webhook and Vault in different K8S cluster
the docs weren't clear enough about how to implement it
=> adding some clarification to docs

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/values.yaml
I'm using an old version of Kubernetes (1.10.11)  here in the company I'm working (shame on me) , and we're trying to update the vault-secrets-webhook and we got this issue:
```
Comparing vault-secrets-webhook banzaicloud-stable/vault-secrets-webhook
error validating "": error validating data: ValidationError(MutatingWebhookConfiguration.webhooks[1]): unknown field "sideEffects" in io.k8s.api.admissionregistration.v1beta1.Webhook
```
The reason behind this error is explained here:  https://github.com/linkerd/linkerd2/issues/2850
This PR allows the user to choose between to active or not the sideEffects in the …
=> adding new parameters to control the sideEffect

charts/vault-operator/Chart.yaml, charts/vault-operator/README.md, charts/vault-operator/templates/role.yaml, charts/vault-operator/values.yaml, operator/cmd/manager/main.go
| New feature?    | yes and no
The Operator leader election feature was removed during the removal of operator-sdk but it is now put back with the controller-runtime implementation.
=> Restore Operator leader election

go.mod, go.sum, operator/cmd/manager/main.go
The operator was using a self-built dummy health check, but the controller-runtime package offers this functionality out of the box.
=> operator: use probes from controller-runtime

docs/mutating-webhook/webhooks-comparision.md
A lot of people were asking what is the difference and the relation between the two projects, we tried to collect the differences and compare the two projects with a small table.
=> docs: add comparision of Banzai Cloud and HashiCorp mutating webhook

go.mod, go.sum
Update the AWS SDK to work with K8S ServiceAccount -> AWS IAM Role mappings.
To support https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html
The old SDK was released before the AWS_ROLE_ARN was handled in the code.
=> update AWS SDK to support eks AWS_ROLE_ARN mappings

cmd/vault-env/main.go
Fix env that has the prefix: ">>" and not is related with Vault.
When the sanitize check each environment, they check if they have a prefix ">>" to update that path. But if you send without vault: prefix, the prefix is trim anyway.
For example:
```sh
MY_ENV=">>test"
```
sanity to
```sh
MY_ENV="test" # Incorrect
```
=> Fix trim to >> value

cmd/vault-secrets-webhook/registry/registry.go
Change the cache key of the ECR token to use ECR registry URL.
When using ECR images from multiple regions, the ECR key would be the same, causing an authentication problem, because the previously generated token was created for only one region
=> Add registry address to cache key

cmd/vault-secrets-webhook/main.go
Currently the default values for consul-template CPU and Memory are never used because the check is wrong. The value provided in the annotation should be used if the error is nil, not viceversa. This PR fixes this.
=> [webhook] Fix resource parsing check

Makefile
The namespace has to be created and labeled manually in case of Helm 3.
=> makefile: webhook fix for helm3

cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/main_test.go, deploy/test-deploy-va.yaml, docs/mutating-webhook/vault-agent-templating.md, internal/configuration/vaultConfig.go
| Related tickets | fixes #804, fixes #464, fixes #302
This PR is a WIP/POC to support vault-agent templating capabilities.
I have some open point I'd like to discuss, and something that still needs to be done to make this review-ready.
Starting with Vault 1.3.0 Templating capabilities have been ported from consul-template to vault-agent. Therefore, we can replace consul-template sidecar with vault-agent.
There are several advantages to this:
- the init container (and its configmap) is no longer required, since vault-agent has auto_auth capabilities.
- https://github.com/banzaicloud/bank-vaults/issues/804 would be solved …
=> Implement vault-agent templating support

operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go
| Bug fix?        | no|
Support for adding custom hostnames or IP addresses to the TLS certificates which the operator generates
We wanted to use a load balancer with SSL passthrough but the TLS cert didn't have the hostname of the load balancer...
=> Add support for custom hosts/IPs on the TLS certificates managed by vault-operator

cmd/bank-vaults/main.go, cmd/bank-vaults/util.go, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go, pkg/kv/k8s/k8s.go
When using the K8S Secret unseal key storage mechanism now all the Vault CR related labels are applied as well to that Secret resource.
To make all operator related component label-selectable.
=> add labels to k8s unseal Secret

docs/cli-tool/README.md, vault-config.yml
| Related tickets | https://github.com/banzaicloud/bank-vaults/pull/140
Change documentation references for Vault AWS auth cross account configuration.
https://www.vaultproject.io/api/auth/aws/index.html#inlinecode-sts_role
It's a minor documentation update, but if it can save time to someone else...
The documentation is using the wrong parameter name
If following documentation, bank-vault fails to update vault:
```
time="2020-02-06T11:37:37Z" level=error msg="error configuring vault: error configuring auth methods for vault: error configuring aws auth cross account roles for vault: error putting …
```
=> Fix aws auth cross account sts role parameter name

.gitignore, README.md, hack/acceptance-test.sh, operator/pkg/controller/vault/vault_controller.go, pkg/kv/k8s/k8s.go
| Related tickets | fixes https://github.com/banzaicloud/bank-vaults/issues/852
The Vault data is not removed when a Vault instance is deleted, the unseal keys shouldn't be removed either. This only affects the K8S backend.
=> operator: remove owner reference setting from unseal secret

cmd/bank-vaults/unseal.go, pkg/sdk/vault/operator_client.go
Signed-off-by: Salvatore Mazzarino <dev@mazzarino.cz>
| Related tickets | #863 
`bank-vaults` expects as env variable the `POD_NAME` and in case this is the first pod of a StatefulSet (in kubernetes this is suffixed with `-0`), it attempts to initialize.
`bank-vaults` could be used not only in a Kubernetes environment but also in the existing Vault cluster where is very useful to automate the Raft join of nodes.
In this scenario, as discussed with @bonifaido, we can verify if Vault is initialized by checking whether the keys stored in the configured Cloud KMS are in place. 
Does this PR break any existing cluster? I'd …
=> Make unseal cmd platform-agnostic

cmd/vault-env/main.go, cmd/vault-secrets-webhook/main.go, deploy/test-dynamic-env-vars.yaml, docs/mutating-webhook/README.md, go.sum, internal/configuration/vaultConfig.go, operator/deploy/cr-mysql-ha.yaml, operator/deploy/cr.yaml, pkg/sdk/vault/client.go
| Related tickets | fixes https://github.com/banzaicloud/bank-vaults/issues/836
Add the functionality to start `vault-env` in a so-called daemon mode, so it doesn't replace itself with the user process after setting the environment variables, but executes it as a child-process and remains in memory, so it can renew the leases on Vault tokens and on dynamic secrets.
To be able to use dynamic secrets in long-running processes with `vault-env`.
The functionality can be enabled with the `vault.security.banzaicloud.io/vault-env-daemon: "true"` annotation, the old …
=> vault-env: add daemon mode with dynamic secret renewal

cmd/vault-secrets-webhook/registry/registry.go, cmd/vault-secrets-webhook/registry/registry_test.go
| Related tickets | fixes #879 
Fix for #879 .
=> webhook: fix parseContainerImage for special image format

.github/workflows/ci.yml
Otherwise, checkout breaks for external PRs.
=> ci: use checkout@v2

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/_helpers.tpl, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/templates/warnings.tpl, charts/vault-secrets-webhook/templates/webhook-cert-manager.yaml, charts/vault-secrets-webhook/values.yaml
| Related tickets | fixes #867
This PR allows vaults-secrets-webhook to get certificates from cert-manager.
Added `warnings.tpl`. This will validate that the user of the chart does not request an invalid configuration.
=> vault-secrets-webhook: Add cert-manager certficate capability

operator/pkg/controller/vault/vault_controller.go
| Related tickets | fixes #892 
Change the way that annotations on the current `vault service` are handled when updating the service object.
To be able to update service annotation while , at the same time, keep the dynamic annotation on the updated service as well
* Locally tested to ensure that not just the "last-applied" but also any other annotation added out of the operator persist when the service is updated
=> Do not just overwrite the annotations for the updated service

operator/pkg/controller/vault/vault_controller.go
| Bug fix?        |no
| Related tickets | fixes #889 
If in the vault config section `disable_mlock` is set to true, the operator doesn't add the IPC_lock capability to `ContainerSecurityContext` of the Vault container.
=> Don't add IPC_LOCK capability when disable_mlock is true in Vault config

.circleci/config.yml
Disable license check for now, because we don't wan't to leak a GITHUB_TOKEN in external PRs.
It is enabled in the GitHub Actions build as a backup.
=> circle: disable license check

operator/deploy/cr-k8s-startup-secret.yaml, pkg/sdk/vault/operator_client.go
| Related tickets | fixes #835 , partially #Y, mentioned in #Z
We can define a K8s secret, contains a CA certificate and key, for importing to Vault PKI engine.
=> Existing root CA startup k8s secret to PKI engine

Makefile, charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/values.yaml, cmd/vault-secrets-webhook/configmap.go, cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/object.go, cmd/vault-secrets-webhook/secret.go, deploy/test-custom-resource.yaml
| Related tickets | fixes #900 
Mutation functionality for custom resources, namely any kind of Kubernetes resources with the help of the Unstructured API.
To support injection, for example, CA certificates to resources from Vault, but other use cases are possible as well.
=> [webhook] mutate any kind of k8s resources

operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go, operator/pkg/controller/vault/vault_controller.go
| Related tickets | fixes #885 
This PR adds the ability to define a Pod Affinity object to be passed through to the Etcd cluster object.  If EtcdAffinity is defined this is what will get passed through.  If that is empty but podAntiAffinity exists this will be used in the Affinity rules.  Otherwise this is not set
Have tested the main cases; explicitly defining pod affinity, using the podAntiAffinity config, and with nothing.
=> Operator: Etcd affinity

charts/vault-operator/Chart.yaml, charts/vault-operator/crds/crd.yaml, charts/vault-operator/templates/_helpers.tpl, charts/vault-operator/templates/crd.yaml
| Related tickets | fixes #908 
Support for the Helm 3 `crds` directory way of installing CRDs.
To use the Helm 3 CRD installing on Helm 3 and leave the old method for Helm 2.
Uses the `Chart` built-in-object to detect if we are running on Helm 3 (Chart `"type"` is defined only in Helm 3). See: https://helm.sh/docs/topics/charts/#chart-types
=> operator/chart: support for Helm v3

.circleci/config.yml
From now on, the default helm executor is helm3 (helm v3.1.1)
=> Bump helm orb version

charts/vault-secrets-webhook/values.yaml, cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/main_test.go, pkg/sdk/vault/client.go
This PR adds a new environment variable `VAULT_CLIENT_TIMEOUT` that allows users to configure how long `vault-env` and `vault-secrets-webhook` keep trying to fetch secrets before failing. The current hard-coded behaviour is to wait for 10 seconds, so this is the default value set for this new configuration parameter.
We are currently having pods injected with `vault-env` that are failing because the pod's Istio proxy sidecar sometimes takes more than 10 seconds to be ready. When that happens, `vault-env` fails to connect to Vault and the pod fails. …
=> Make client timeout configurable

operator/pkg/apis/vault/v1alpha1/vault_types.go
| Related tickets | fixes #926 
https://github.com/banzaicloud/bank-vaults-docs/pull/15
To clarify that ca.crt is required in the external cert anyhow.
=> operator: clarify existingTlsSecretName

cmd/vault-secrets-webhook/main.go
Update the consul-image to the 0.24.1-alpine.
In the previous versions, there was a bug that caused issues with token renewal. Which could
result in a pod/container crash loop. I experienced this myself, after 30 days consul-template container went into a crash loop. See the additional context section.
https://github.com/hashicorp/consul-template/issues/1161
n/a
=> update consul-template default image

operator/pkg/controller/vault/vault_controller.go, pkg/sdk/tls/tls.go, pkg/sdk/tls/tls_integration_test.go
| API breaks?     | no|
This PR implements the ability for Bank Vault's operator to use an existing automatically generated Certificate Authority when generating a new Server Certificate in the event of a new one being required.
It seems like etcd's CA was always replaced regardless of one already existing so I haven't implemented support for that as we don't have access to the secret at the point where we would need the CA/key to update the Server cert instead of generating a full chain
We were having issues with our cross cluster CA certificate expiring when a LoadBalancer IP was changing and causing the Server Certificate to be renewed …
=> Implement the ability for a CA to persist when the Server certificate needs to be regenerated

cmd/vault-env/main.go
| Related tickets | fixes #934 
Fixing the subscription to signals in case of unstarted processes.
To prevent nil pointer panic of unset `.Process` attribute.
=> vault-env: fix signal subscription order

operator/deploy/cr.yaml, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go
| Related tickets | https://github.com/banzaicloud/bank-vaults-docs/pull/17
=> Use string for tlsExpiryTreshold in spec instead of duration

operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go, operator/pkg/controller/vault/vault_controller.go
| Related tickets | fixes #971 
Write standard Kubernetes Condition status to the Vault CR instance.
To be able to wait for healthy vault instance from deployments.
Can Vault CR status now can be tested with:
```bash
kubectl wait --for=condition=Healthy vault/vault
```
=> operator: add vault condition statuses

cmd/vault-secrets-webhook/registry/registry.go
| Related tickets | fixes #969 
Try to read the old `.dockercfg` key from the `imagePullSecret` as well a fallback option, since some providers still use the old Docker authentication format. The old format is deprecated for a long time: https://github.com/moby/moby/commit/18c9b6c6455f116ae59cde8544413b3d7d294a5e
=> webhook: try to read the old .dockercfg key from the imagePullSecret as well

pkg/sdk/vault/operator_client.go
| Related tickets | fixes #979
This adds support for Vault Policies to be provided as JSON strings, in addition to HCL-formatted strings. Current behaviour tries to use an HCL formatter to make it pretty, which won't work for JSON!
This change makes the operator attempt to parse the policy (with a Vault function which parses both JSON and HCL) and if it succeeds, applies it.
Vault supports policies in both HCL and JSON format so the operator should too!
Our policies were becoming boilerplate-y and less maintainable so we decided to generate them via Jsonnet, where it's significantly easier to template JSON than HCL.
This …
=> Operator: Support JSON-formatted Vault policies

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/templates/webhook-psp.yaml
| Related tickets | fixes #986 
This uses `semverCompare` helm template function instead of integer when comparing Kubernetes version.
It fixes #986.
Using `.Capabilities.KubeVersion.Major` and `.Capabilities.KubeVersion.Minor` is error prone as the value may not always be integer values (like it's the case of some managed Kubernetes offers as AWS EKS).
=> [chart/webhook] fix Kubernetes version comparison

internal/injector/inejctor.go, internal/injector/inejctor_test.go, pkg/sdk/vault/transit.go
| Related tickets | fixes #977
Design and implement the sending of write parameters and document the feature with examples.
It is already possible to request dynamic secrets from Vault with "write" requests.
However, this feature is undeservedly underdocumented and incomplete since it is not possible to add data to those write requests.
=> webhook: allow to pass data in write request

charts/vault/Chart.yaml, charts/vault/templates/rolebinding.yaml
Signed-off-by: Sam Weston <weston.sam@gmail.com>
| Related tickets | fixes #991 
Prepends the namespace name to the ClusterRoleBinding name to allow for multiple releases with the same name in the same cluster (but different namespaces).
Fixes #991
=> Prepend namespace name to ClusterRoleBinding for vault Helm Chart

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/webhook-deployment.yaml, charts/vault-secrets-webhook/values.yaml
The userid 65534 is not an allowed user in openshift.
| Related tickets | fixes #994 
Add the ability to use a custom runAsUser in the helm chart.
When using the vault secrets webhook chart in OCP 4.3.x for security reasons the runAsUser must be in the range between 1000570000 and 1000579999 and not 65534.
=> OCP 4.3: runAsUser in Vault Secrets webhook chart should be configurable

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/webhook-deployment.yaml
| Related tickets | fixes #1002 
Custom labels are added to pods themselves rather than only the deployment. The README was also updated with this undocumented value.
=> add: labels to pods themselves, update README

pkg/sdk/vault/operator_client.go
| Related tickets | fixes #1009 
The original cause of some errors was wrapped in #334 and this broke the NotFoundError detection.
=> notFoundError cause fix

charts/vault-secrets-webhook/README.md
This PR updates Vault Webhook readme, removing instructions for adding ClusterRoleBinding granting the Vault Webhook Service Account system:auth-delegator role.
In itself the clusterrolebinding granting Vault Webhook Service Account system:auth-delegator role has no consequence because it is not tied to any particular Vault install's Kubernetes auth method.
=> Remove unneeded webhook ClusterRoleBinding notes

cmd/vault-secrets-webhook/main.go
Check for the addr annotation is duplicate here, because its already
covered by parseVaultConfig method.
Fixes #938
Signed-off-by: flozzone <flozzone@gmail.com>
| Related tickets | fixes #938
Remove checks for the address annotation, because it is already done by the parseVaultConfig method.
This allows Secrets and Unstructured configurations to be mutated even there is no explicit `vault.security.banzaicloud.io/vault-addr` annotation. It will use the default configuration value instead.
Testings with this fix showed that Secrets get mutated as expected. See docker.hub repository …
=> Remove explicit check for annotations

operator/pkg/controller/vault/vault_controller.go
| Related tickets | fixes #1016 
Add `automountServiceAccountToken: true` to Vault and Bank-Vaults pods.
In some user clusters the service account token is not automatically mounted to pods (namespace/serviceAccount setting). This PR resolves the issue.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server
=> operaror: Automount ServiceAccount Token

operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go, pkg/sdk/vault/operator_client.go
In some cases for example RAFT the https scheme was hardcoded and was not configurable via the Vault config flag: `tls_disable: true`.
=> operator: fix hardcoded https schemes in case of raft

pkg/kv/kv.go, pkg/kv/multi/multi.go, pkg/sdk/vault/operator_client.go
| Related tickets | #1008, fixes #1009 
For Raft the `notFoundError` handling was still broken for Google Cloud KMS unseal.
=> fix notFoundError handling in raft

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/templates/webhook-cert-manager.yaml, charts/vault-secrets-webhook/templates/webhook-deployment.yaml, charts/vault-secrets-webhook/templates/webhook-pdb.yaml, charts/vault-secrets-webhook/templates/webhook-service.yaml
Fix consistency of names in `vault-secrets-webhook`. I have noticed that not all `app.kubernetes.io/name` labels for Kubernetes resources were consistently named. I also noticed that `_helpers.tpl` defines `vault-secrets-webhook.servingCertificate` (by default same as `fullname`), but this value is then not used throughout the rest of the template.
Consistent names are essential to prevent issues if things get renamed. This also gets us one step closer to support multiple deployments of `vault-secrets-webhook` in a single Kubernetes cluster.
=> Fix names of k8s resources in vault-secrets-webhook

cmd/bank-vaults/unseal.go
| Related tickets | fixes #1029 
This change adds some additional logic to the vault init check.
This addresses the use case in the related ticket so we can have vault unsealed by transit, but restrict access to the root token.
- [ x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
=> Add seal check to vault init

cmd/vault-secrets-webhook/main.go, deploy/test-configmap.yaml
This PR introduces the resource level `vault.security.banzaicloud.io/mutate` annotation, which currently can have one possible value which is `"skip"` which prevents the mutation process (even on parsing level).
To prevent some edge cases.
=> webhook: add resource skip annotation

charts/vault-operator/Chart.yaml, charts/vault-operator/templates/_helpers.tpl, charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/_helpers.tpl, charts/vault/Chart.yaml, charts/vault/templates/_helpers.tpl
| Related tickets | fixes #1038 
Fixes version image tag in charts calculated from Chart.AppVersion.
It got messed up with an extra `v` prefix in the latest release.
=> charts: fix image tag by appVersion

operator/pkg/controller/vault/vault_controller.go
| Related tickets | mentioned in #899 
Unsets owner references on TLS CA secrets that are synced to the namespaces in `CANamespaces`
As per the K8S garbage collector docs, cross-namespace owner references are
disallowed (https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/):
```
Note: Cross-namespace owner references are disallowed by design. This means:
1) Namespace-scoped dependents can only specify owners in the same namespace,
and owners that are cluster-scoped.
2) Cluster-scoped dependents can only specify cluster-scoped owners, but not
namespace-scoped owners.
```
The controller is namespace …
=> operator: Unset owner references on synced TLS CA secrets

operator/deploy/multi-dc/cr-primary.yaml, operator/deploy/multi-dc/cr-secondary.yaml, operator/deploy/multi-dc/cr-tertiary.yaml, operator/deploy/multi-dc/multi-dc-raft.sh
The `cluster_addr` parameter was made a mandatory setting in a recent version of Vault and it was not set in the multi-dc examples, because the operator overwrites that value in any cases. Setting an initial value fixes this issue.
=> some fixes in multi dc raft example

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/webhook-rbac.yaml, charts/vault-secrets-webhook/values.yaml
Adds the ability to specify vault-secrets-webhook Kubernetes serviceAccount optional labels and annotations from the Helm chart.
To be able to use implicit GCR authentication through GKE workload identity, the Kubernetes serviceAccount must have specific annotations. Labels are just an extended plus.
=> Chart: ability to add optional serviceaccount labels and annotations

operator/deploy/cr.yaml, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go, operator/pkg/controller/vault/vault_controller.go
| Related tickets | fixes #1049 
Adds the ability to pass in environment variables to the sidecar container, so Vault can be accessed on a different address for example, see example.
To be able to customize the sidecar only, for using custom certificates e.g..
=> operator: allow VAULT_ADDR to be overridden

charts/vault/Chart.yaml, charts/vault/templates/statefulset.yaml
| New feature? |   yes
The vault chart expects environmental variables in the form of name/value pairs and will
remove variables using the [k8s downward api](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#the-downward-api).
At the moment you cannot use environment variable like 
```      
env:
- name: MY_NODE_NAME
valueFrom:
fieldRef:
fieldPath: spec.nodeName
```
as they are not in the form of simple name/value pairs.
This is useful so that vault can access the downward api. It could be used to set the api_addr and cluster_addr and we would use also use it to set the …
=> Support k8s downward api in vault chart environment variables

charts/vault/Chart.yaml, charts/vault/templates/service-headless.yaml, charts/vault/values.yaml
Signed-off-by: Sam Weston <weston.sam@gmail.com>
Adds the option to enable a headless service for Vault in addition to the normal service. Also fixes indentation for the annotations on the normal service.
We wanted a headless service so we could expose Vault on Amazon EKS within our VPC without paying for a LoadBalancer.
- [N/A] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [N/A] User guide and development docs updated (if needed)
=> [charts/vault] Add option for headless service

charts/vault/Chart.yaml, charts/vault/templates/certificate.yaml, charts/vault/templates/secret.yaml, charts/vault/templates/statefulset.yaml, charts/vault/values.yaml
Signed-off-by: Sam Weston <weston.sam@gmail.com>
The option use cert-manager to generate the Vault certs rather than Helm.
Regeneration every Helm apply was an annoyance for us and cert-manager gives us more flexibility.
- [N/A] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [N/A] User guide and development docs updated (if needed)
=> [charts/vault] Option to use cert-manager to generate certs

charts/vault/Chart.yaml, charts/vault/README.md, charts/vault/templates/statefulset.yaml, charts/vault/templates/tests/test-vault-status.yaml, charts/vault/values.yaml
This makes pod affinity configurable.
The chart uses preferred anti-affinity while we want to use required anti-affinity as we run on spots.
If no affinity is defined the chart will work as before using the affinity values defined in the template.
(I also removed white space in the helm test that I introduced in a previous PR.)
=> make affinity configurable in helm chart.

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml
| Related tickets | partially #1071 
Use `apiVersion: admissionregistration.k8s.io/v1` for webhooks after in case of Kubernetes > 1.16.
`apiVersion: admissionregistration.k8s.io/v1beta1` got deprecated in 1.16 and might cause issues in some distros.
=> webhook: use admissionregistration.k8s.io/v1 in registration wherever possible

operator/pkg/controller/vault/vault_controller.go
| Related tickets | fixes #1077 
Add labels to Vault Statefulset and to the configurer deployment as well.
It is expected to be there.
=> operator: add labels to deployments and statefulsets as well

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/webhook-deployment.yaml, charts/vault-secrets-webhook/values.yaml
Fixes issue #1075 to allow for the vault-env repository to be overridden via the values file.
| Related tickets | Fixes #1075 
Allows the repository for the vault-env container, injected into deployments etc, to be overridden.  Primarily necessary in environments where dockerhub is not available due to firewalls or access rules.
My employer has secure environments where we need to use this chart, and make use of an Artifactory installation to serve our images.  We can't directly pull from docker.io, and upload images directly to our instance once they have been reviewed and approved.
=> Allow the vault-env repository to be overridden.

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/webhook-rbac.yaml, charts/vault-secrets-webhook/values.yaml
| Related tickets | fixes #1099
Add `system:auth-delegator` to the webhook ServiceAccount optionally.
To be able to authenticate via the webhook SA in an external Vault cluster.
=> webhook: allow adding auth-delegator role in the chart

operator/pkg/controller/vault/vault_controller.go
| Related tickets | partially #1085 
Only apply custom VAULT_CLUSTER_ADDR in case of multi-cluster setups when using LoadBalancer.
Otherwise the default `cluster_addr: "https://${.Env.POD_NAME}:8201"` from the Vault config should work fine.
=> operator: fix single cluster raft with LoadBalancer serviceType

charts/vault-operator/Chart.yaml, charts/vault-operator/README.md, charts/vault-operator/templates/psp.yaml, charts/vault-operator/templates/role.yaml, charts/vault-operator/templates/rolebinding.yaml, charts/vault-operator/values.yaml
| Related tickets | fixes #1109 
Add PSP for `vault-operator` and `vault` that is deployed by the operator.
If `PodSecurityPolicy` is enabled it will be useful to set a flag to deploy the necessary PSP resources via helm.
=> [charts/vault-operator]Add PSP for vault-operator and vault that is deployed by the oerator

cmd/vault-secrets-webhook/pod.go, cmd/vault-secrets-webhook/pod_test.go
When adding the env-from-path annotation, I was incorrectly mutating the pod instead of the container.  This fix is to actually mutate the container.  The work around for this is to explicitly add `VAULT_ENV_FROM_PATH` environment variable to the container.
=> fix: move VAULT_ENV_FROM_PATH to mutateContainers

cmd/vault-secrets-webhook/registry/registry.go
| Related tickets | partially #966
This PR adds support for authenticating against Google Container Registry without explicit username / password. 
It works similarly to the already present Amazon ECR support: If there are no username / password / imagePullSecrets specified, then it checks the registry hostname against the known GCR hotsts. If the pattern matches then it tries to obtain an auth token from the metadata service endpoint when running inside Google Cloud (which also works with workload identity if running in GKE).
Using default credentials avoids the need for pre-shared credentials (passwords or manually …
=> Add support for GCR default credentials

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/webhook-deployment.yaml, charts/vault-secrets-webhook/values.yaml
It is not possible to specify full gamut of `pod.spec.container[].securityContext` or `pod.spec.securityContext` without modifying the chart itself. In our case, we needed to set `pod.spec.securityContext.fsGroup` to the same group as the user in order to be compatible with AWS [OIDC EKS IAM](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html). This PR includes a minor fix to allow specifying all `securityContext` options on the webhook deployment. There should be no effective change unless custom options are set.
Users who may have set custom …
=> vault-mutating-webhook: allow specifying pod securityContext and full container securityContext

cmd/vault-secrets-webhook/secret.go
| Related tickets | fixes #1122 
Check `kubernetes.io/dockerconfigjson` type secrets deeper before actual mutation.
To prevent the construction of unconfigured Vault clients.
=> webhook: make secretNeedsMutation check work better for kubernetes.io/dockerconfigjson type secrets

cmd/vault-secrets-webhook/pod.go, cmd/vault-secrets-webhook/pod_test.go
| Related tickets | fixes #940 
Increasing the CPU limits and defining a proper CPU request for some init containers.
The copy-vault-env and vault-agent init containers are starving on throttled hosts.
=> webhook: change the resource limit/requests of copy-vault-env and vault-agent to a sane value

internal/vault/operator_client.go
In some stricter deployments, it is not allowed to list plugins, auth backends so exit if we are not required to touch them.
=> configurer: exit early if possible before touching the API

cmd/bank-vaults/main.go
| Related tickets | fixes #1128 
Handling signals, and do a 0 status code exit.
If signals are not captured the CLI exits with status code 2.
=> cli: handle signals properly

operator/deploy/cr-audit.yaml, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go
| Related tickets | fixes #1135 
Enable setting custom path for fluent.conf
We are using a custom fluentd image that expects `fluent.conf` to be under `/etc/fluent/` and we need a way to customise it.
- [ Y ] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [ Y ] User guide and development docs updated (if needed)
- [ Y ] Related Helm chart(s) updated (if needed)
=> Custom fluentd conf path

internal/injector/injector.go, internal/injector/injector_test.go
| Related tickets | fixes #1136 
Add back caching to the secret injector, which got removed during a refactor since 1.4.2.
Also added a test to prevent this from happening again.
=> injector: fix secret caching and add test

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/webhook-rbac.yaml
Fixes invalid yaml when `.Values.rbac.authDelegatorRole.enabled` is set to `true`. A yaml separator is missing then.
Original commit was: https://github.com/banzaicloud/bank-vaults/pull/1101
Seems like nobody tested it so far.
=> [BUGFIX] Fixes invalid yaml when `.Values.rbac.enabled` is set to `true`

cmd/vault-secrets-webhook/pod.go
The pod mutation checks to see if there are any env variables
that have vault keys in them, if there are no env variables it
continues on and doesn't mutate the pod.  This fix also checks if
the EnvFromPath annotation is empty, if it's empty and there are no 
env variables that reference vault keys it continues without mutating the pod.
If you have a pod that only has the envFromPath annotation and no env variables that reference vault keys, the pod does not get mutated.
=> add check for EnvFromPath to be empty for continuation

cmd/vault-secrets-webhook/main.go, deploy/test-secret.yaml, hack/acceptance-test.sh
Allow applying the `vault.security.banzaicloud.io/vault-tls-secret` annotation on non-Pod resources as well.
To have proper TLS CA validation between the webhook and Vault for all-resources.
=> webhook: Load CA for non-pods as well

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/values.yaml
This PR adds an option to `vault-secrets-webhook` chart to provide an already externally defined Certificate produced by cert-manager, without generating any new certificates or even CAs.
The existing chart currently has 2 options to generate a whole new CA and a new TLS certificate, and an option to manually specify Base64-encoded keys for a Secret. In my opinion some users already have an existing CA infrastructure managed by cert-manager, and issue all Certificates for all internal services and webhooks through it. Consequently, the `vault-secrets-webhook` chart only needs an option to specify …
=> Add support for externally defined Certificate by cert-manager

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml
| Related tickets | fixes #1149
Adding a Kubernetes Version validation before using the AdmissionReviewVersions parameter, as it was only introduced in [Kubernetes 1.14](https://github.com/kubernetes/kubernetes/commit/f7dff4725f8dc694a852e7fdbdde2c8a6dd5b7d4)
=> webhook: Adding KubeVersion validation when using admissionReviewVersions

cmd/vault-env/main.go, cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/pod.go
| Related tickets | fixes #1155
I would like to be able to use a pre-provided token to access the vault. We are using the mutating webhook to access but there is no way to use a provided token throughout the mutating webhook.
Tested with a vault where kubernetes auth is disabled
- injected secrets using `vault-env` into environment variables
- injected secrets using `consul-template` into ct-secrets
=> allow token access to vault

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/values.yaml
Add timeoutSeconds in chart.
> Default timeout for a webhook call is 10 seconds for webhooks registered created using admissionregistration.k8s.io/v1, and 30 seconds for webhooks created using admissionregistration.k8s.io/v1beta1. Starting in kubernetes 1.14 you can set the timeout.
With 10 seconds we have timeouts
=> [HELM] Webhook timeoutSeconds value

cmd/vault-secrets-webhook/registry/registry.go, deploy/test-deployment-gcp.yaml, pkg/sdk/vault/client.go
| Related tickets | #1093 
Automated GCP GCE auth (https://www.vaultproject.io/docs/auth/gcp#gce-login) without providing `GOOGLE_APPLICATION_CREDENTIALS`. For the webhook, client, and vault-env.
=> client: automated GCP GCE authentication

cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/pod.go
This PR adds 4 new annotations so we can alter the images for vault agent and vault-env at pod level.
This is useful when you need to test new images without breaking everything or deploy a whole new environment. This can be useful when you have multiple vaults with different versions, depending on the team. It can be useful if team A has vault v2 with a breaking change from v1 but team B has still vault v1.
- Review the doc for this PR: https://github.com/banzaicloud/bank-vaults-docs/pull/44
=> feat: annotations to control agent and env images

cmd/vault-secrets-webhook/pod.go
Q | A
-- | --
Bug fix | Yes
New feature | no
API breaks | no
Deprecations | no
Related tickets | none
License | Apache 2.0
This PR fixes the command passing the `vault agent` command to exit after the auth process. 
`vault agent` command doesn't support the current `-once` attribute, the correct attribute is `-exit-after-auth`
=> fix vault agent `-once` command to exit after auth

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/webhook-deployment.yaml, charts/vault-secrets-webhook/values.yaml
Q | A
-- | --
Bug fix? | no
New feature? | yes
API breaks? | no
Deprecations? | no
Related tickets | #1154 
License | Apache 2.0
What's in this PR?
add hostnetwork in chart.
Why?
This can help me to create a helm release with flux by integrated with inside values file
=> webhook: add hostnetwork in chart (following of #1154)

cmd/bank-vaults/unseal.go, internal/vault/operator_client.go, operator/deploy/cr-raft-ha-storage.yaml, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go
| Related tickets | fixes #1165 
Vault Raft HA storage (only) support got implemented.
It requires a different ceremony compared to a full raft storage setting.
=> [operator] Raft HA storage

operator/deploy/cr-raft-ha-storage.yaml, operator/deploy/cr-raft.yaml, operator/deploy/rbac.yaml, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go
| Related tickets | fixes #1167 
**!IMPORTANT!**
The minimal RBAC Role for a Vault pod has been changed, it should be:
```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: vault
rules:
- apiGroups: [""]
resources: ["secrets"]
verbs: ["*"]
- apiGroups: [""]
resources: ["pods"]
verbs: ["get", "update", "patch"]
```
=> operator: add service_registration

charts/vault/Chart.yaml, charts/vault/templates/statefulset.yaml, charts/vault/values.yaml
| Related tickets | fixes #1170, related #895 
Remove the IPC_LOCK capability from the StatefulSet if `mlock` is disabled in config.
=> vault/chart: align IPC_LOCK behaviour to operator based on disable_mlock

cmd/vault-secrets-webhook/pod.go, cmd/vault-secrets-webhook/pod_test.go, internal/injector/injector.go, internal/injector/injector_test.go
Signed-off-by: Lord-Y <Lord-Y@users.noreply.github.com>
This PR permit inline secrets mutation from vault-env/vault-secrets-webhook
=> Add inline secrets for vault-env/vault-secrets-webhook

cmd/vault-env/main.go
| Related tickets | #1177, #1156 
Fixing a regression introduced by #1156, the `vault:login` special value won't allow the client to be properly configured with clientOptions.
=> vault-env: fix vault:login clientOptions

cmd/vault-secrets-webhook/pod.go, cmd/vault-secrets-webhook/pod_test.go
| Bug fix        | no
| New feature    | yes
| API breaks     | no
| Deprecations   | no
This PR allows to use a ConfigMap with the agent when the agent is in the initContainers
I want to make sure the agent runs before all other containers and exits since I want to use the token the agent sinks directly in my application.
=> Use agent ConfigMap when agent is in the InitContainers

hack/acceptance-test.sh, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go
Adding type LoadBalancerIP for the vault crd
Selecting a specific loadbalancerIP is sometimes necessary. In case of multiple metallb pools and firewall configuration requirements.
Did test the setup. The setting of the loadbalancerIP of worked. I did experience TLS issues following normal documentation. I did got this fixed by adding:
```
tlsAdditionalHosts:
- vault-secondary
- vault-secondary.default
- vault-secondary.default.svc.cluster.local
- vault-tertiary
- vault-tertiary.default
- vault-tertiary.default.svc.cluster.local
- 172.21.123.10  # (lb dc2)
- 172.21.124.10  # (lb dc1)
```
the code …
=> Multidc use specific loadbalancerip

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/templates/warnings.tpl, charts/vault-secrets-webhook/templates/webhook-cert-manager.yaml, charts/vault-secrets-webhook/templates/webhook-ingress.yaml, charts/vault-secrets-webhook/templates/webhook-service.yaml, charts/vault-secrets-webhook/values.yaml
| API breaks?     | no|
| Deprecations?   | nos
MutatingWebhook can also connect to an url. Currently this can only be an (k8s) service. This PR add the ability to create 
a k8s Loadbalancer or k8s Ingress and use the url method
Using the Service method can cause the webhook to be temporary unreachable. Check the following issues
https://github.com/kubernetes/kubernetes/issues/80313
https://github.com/kubernetes/client-go/issues/374#issuecomment-632457187
In short, the client-go library caches the ip of the pod so if the pod gets  an different ip the cache needs to invalidate
which takes time. Using a url instead of the service is a workaround until this is fixed in …
=> allow the vault-webhook to be contacted over loadbalancer or ingress

internal/vault/operator_client.go
Logging warnings about configuration changes in the configured client, like:
```
INFO[0000] tuning already existing mount: pki/          
WARN[0000] Refusing to generate a root certificate over an existing root certificate. If you really want to destroy the original root certificate, please issue a delete against pki/root. 
INFO[0000] successfully configured vault    
```
These warnings were invisible previously in the logs of the configurer, and could leave the user in false calm.
=> client: log warnings from configuration changes

internal/vault/operator_client.go, operator/deploy/cr.yaml, vault-config.yml
Allow saving the output of API based Vault configuration calls to KV version 2 locations.
The PKI private key during root generation is only visible once (when you hit the API), but in some cases external users like Iistio needs it.
Full example:
```yaml
secrets:
- path: secret
type: kv
description: General secrets.
options:
version: 2
- type: pki
description: Vault PKI Backend
config:
default_lease_ttl: 144h
max_lease_ttl: 144h
configuration:
config:
- name: urls
issuing_certificates: https://vault.vault:8200/v1/pki/ca
crl_distribution_points: https://vault.vault:8200/v1/pki/crl
root/generate:
- …
```
=> configurer: allow saving Vault secret engine configuration data to KV engine

operator/deploy/cr.yaml, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go, operator/pkg/controller/vault/vault_controller.go
| Related tickets | fixes #1200 
Allows overriding the container specification of the Vault container deployed by the operator, see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core for all fields.
To be able to add lifecycle hooks for example.
=> operator: add VaultContainerSpec override

charts/vault/Chart.yaml, charts/vault/templates/role.yaml
fix error wheb psp enabled
```
Error: YAML parse error on vault/templates/role.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type releaseutil.SimpleHead
helm.go:84: [debug] error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go value of type releaseutil.SimpleHead
YAML parse error on vault/templates/role.yaml
```
=> fix yaml when install chart vault with .Values.rbac.psp.enabled=true

cmd/bank-vaults/common.go
| Related tickets | fixes #1220 
Employ the AWS_REGION/AWS_DEFAULT_REGION if possible during AWS based unsealing, if not provided for KMS/S3.
For convinience.
Only works for single region setups.
=> unseal: use AWS_REGION/AWS_DEFAULT_REGION if possible

.github/workflows/codeql-analysis.yml
This checkout step is no longer needed by the latest CodeQL engine action.
```
1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
```
=> codeql: remove unnecessary checkout step

charts/vault/Chart.yaml, charts/vault/templates/statefulset.yaml, operator/pkg/controller/vault/vault_controller.go
Marking DR secondary (only enterprise Vault) nodes as healthy. See https://www.vaultproject.io/api-docs/system/health#472
Otherwise, they are marked unhealthy by the Kubernetes probes.
=> operator&chart: drsecondary nodes should be healthy

operator/pkg/controller/vault/vault_controller.go
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
| Related tickets | fixes #1256
Add missing capability in order to make the vault pods run.
See issue #1256.
https://github.com/hashicorp/docker-vault/issues/137
=> Add missing capability

charts/vault-operator/Chart.yaml, charts/vault-operator/templates/role.yaml
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
| Related tickets | fixes #1260
OpenShift uses a special route concept, and w/o these permissions it will fail as described in #1260. I might have added a bit many verbs, but it mirrors the ingress, which makes sense.
Make ingress work ootb on openshift.
Uses api detection to avoid problems on non-openshift platforms - should not be intrusive.
=> add permissions to make ingress work on openshift

cmd/vault-secrets-webhook/object.go
Fix for inline mutations in custom resources
Inline mutations in custom resources did not work for me (values were not replaced), i looked into the source code and it seems like the data gets successfully retrieved from vault, but the object (custom resource) is not updated afterwards. I tested the fixed version in my cluster and it now works as expected.
To test it, create a custom resource definition, add it to the "customResourceMutations" list in the helm chart values and create a custom resource with an annotation, like:
```
metadata:
annotations:
foo: "secret is ${vault:secrets/data/foo#bar}"
```
It does not work …
=> [webhook] Fix for inline mutations in custom resources

charts/vault-operator/Chart.yaml, charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/values.yaml, charts/vault/Chart.yaml, charts/vault/README.md, charts/vault/templates/pdb.yaml, charts/vault/templates/statefulset.yaml, charts/vault/values.yaml
Adds a PodDisruptionBudget to the vault Helm Chart, turned on by default with maxUnavailable set to 1, to avoid issues for people running the default configuration of 1 replica.
Also adds the option to set a priorityClassName to the StatefulSet Pods.
Also adds the option (but no change to default behaviour) to set maxUnavailable on the vault-secret-webhook Helm Chart PDB.
Avoids the possibility of downtime if multiple Vault Pods get evicted at once.
=> [charts/vault] Add PodDisruptionBudget to vault Helm Chart

charts/vault-operator/Chart.yaml, charts/vault-operator/README.md, charts/vault-operator/templates/_helpers.tpl, charts/vault-operator/templates/deployment.yaml
This will allow to have separate versions of the the bank-vault & operator containers
When you build your own versions of the images you can't necessarily guarantee the same tag for different containers
=> [charts/vault-operator] Support separate tags in operator & bank-vaults images

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/values.yaml
| Bug fix?        | kind of
This PR adds missing `objectSelector` configuration options to the MutatingWebhookConfiguration resource. On one hand the `objectSelector` was completely missing for some hooks, on the other it did not support the `matchLabels` selector option (to provide the same options as `namespaceSelector`).
In addition, this PR adds a default `objectSelector` rule to not trigger on internal Helm v3 state resources (can be in Secrets or ConfigMaps).
My attempts to use the `objectSelector` configuration to prevent the `vault-secrets-webhook` to trigger on internal Helm v3 state resources have failed. By …
=> vault-secrets-webhook: Add missing objectSelector configuration options

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/webhook-cert-manager.yaml, charts/vault/Chart.yaml, charts/vault/templates/certificate-issuer.yaml, charts/vault/templates/certificate.yaml, operator/deploy/issuer.yaml
| Related tickets | fixes https://github.com/banzaicloud/bank-vaults/issues/1283
Upgrading to certmanager v1 resources in charts and examples.
Cert manager v1 has ben released last September, so now it's time to support the stable API version of it.
=> certmanager: use v1 resource versions

charts/vault/Chart.yaml, charts/vault/templates/certificate-issuer.yaml, charts/vault/templates/certificate.yaml, charts/vault/templates/configmap.yaml, charts/vault/templates/ingress.yaml, charts/vault/templates/prometheus-monitorservice.yaml, charts/vault/templates/pvc.yaml, charts/vault/templates/role.yaml, charts/vault/templates/rolebinding.yaml, charts/vault/templates/secret.yaml, charts/vault/templates/service-headless.yaml, charts/vault/templates/service.yaml, charts/vault/templates/serviceaccount.yaml, charts/vault/templates/statefulset.yaml
- chart/vault: namespace all resources explicitly (better for `helm template`)
- chart/vault: allow statsd to be enablable properly (it should have been optional since the start)
- chart/vault: make podAnnotations optional
=> [chart/vault] updates

internal/vault/operator_client.go
Fixes #1316
| Related tickets | fixes #1316 
Ensure that we properly check if a database connection has actually been configured.
Without this fix bank vaults will only try to apply a database connection once. If there is a problem it will never recover.
=> Properly check if database connections are already configured.

pkg/sdk/vault/client.go
| Bug fix?        | maybe
This PR enables `vault-env` to use JWT-based authentication methods while running outside a Kubernetes cluster (and even from outside cloud providers). It just removes an unnecessary check for running in an Kubernetes environment, that made it impossible to use `vault-env` elsewhere. 
Attempts to use a self-signed GCP SA JWT token (not signed by the metadata server as with `gcp-iam`) with `VAULT_AUTH_METHOD=jwt` resulted in:
```
FATA[0000] failed to create vault clientunable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined  app=vault-env
``` …
=> vault-env: Support JWT-based auth methods outside of K8s clusters

go.mod, go.sum, pkg/sdk/go.mod, pkg/sdk/go.sum, pkg/sdk/vault/client.go
Integration of the MSI AAD auth method for Azure. Currently there are only AWS and GCP available.
This method use the MSI ( Managed system identity ) of Azure. 
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/aks/use-managed-identity.md
https://cloudblogs.microsoft.com/opensource/2018/04/10/scaling-tips-hashicorp-vault-azure-active-directory/
It's very useful for adding vault admission controller in a multi-cluster environnement with an external Vault. Using this method the admission controller is auto registered to the vault using the MSI.
Adding Azure auth method …
=> feat: add azure msi auth method for vault

operator/deploy/cr-awskms.yaml
This PR adds a piece of configuration to a Vault CR configuration.
I'm not sure, but I think this configuration is needed to enable the `awskms` seal, which seems to be the purpose of the said configuration.
I used the configuration as it was and when starting, vault did not print out the expected lines in the logs. Expected lines being:
```
==> Vault server configuration:
AWS KMS KeyID: some-key-id …
```
=> Add awskms seal configuration to example

operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go
Put the vault config into a Secret instead.
| Related tickets | fixes #1327 
From now on the un-templated Vault config will be put into a Secret instead of plain-text in the VAULT_LOCAL_CONFIG environment variable.
We wanted to save a creation of a Secret but it seems like a bad idea now.
=> operator: remove usage of VAULT_LOCAL_CONFIG

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/values.yaml, cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/pod.go, cmd/vault-secrets-webhook/pod_test.go
| Related tickets | fixes #1328 
Introduced environment variables ( VAULT_ENV_CPU_REQUEST, VAULT_ENV_MEMORY_REQUEST, VAULT_ENV_CPU_LIMIT, VAULT_ENV_MEMORY_LIMIT) for vault-secrets-webhook. Instead of applying hard-coded values, this provides the users an option to specify resource requests and limits for the init-containers being added during pod mutation for secrets viz _vault-env_ and _copy-vault-env_. Without this change, it is not possible to run mutated pods with "guaranteed" QoS using the default settings - they always run with "burstable".
Hint: Set VAULT_ENV_CPU_LIMIT=50m to be able to run the mutated pod with …
=> vault-secrets-webhook: Allow users to specify resources for init-containers

cmd/vault-env/main.go, cmd/vault-secrets-webhook/main.go, cmd/vault-secrets-webhook/pod.go
| Related tickets | fixes #1330
This PR implements the proposed fix for race conditions with dynamic secrets (issue #1330). It adds:
- `VAULT_ENV_DELAY` environment var to `vault-env`
- `vault.security.banzaicloud.io/vault-env-delay` annotation to `vault-secrets-webhook`
To fix #1330.
=> vault-env/vault-secrets-webhook: Add VAULT_ENV_DELAY and vault-env-delay annotation

go.mod, go.sum, hack/acceptance-test.sh, internal/vault/operator_client.go
| Related tickets | fixes https://github.com/banzaicloud/bank-vaults/issues/1346
Setting the token issuer in the Kubernetes auth config explicitly, since from Kubernetes 1.21 this has changed.
=> configurer: set issuer explicitly from service account JWT for in-cluster scenarios

cmd/vault-secrets-webhook/main.go, pkg/sdk/vault/client.go, pkg/webhook/webhook.go
| Related tickets | fixes #1340
After migrating to kubewebhook v2 the framework has dropped error logging, so we have added this back with a a wrapper.
=> webhook: give back error logging

charts/vault/Chart.yaml, charts/vault/templates/role.yaml, charts/vault/templates/statefulset.yaml, charts/vault/values.yaml
| Related tickets | fixes #1353 
- Adds a global `openshift` flag to be set when deploying to OpenShift. This removes the hard-coded fsGroup from the stateful set
- Explicitly sets the required verbs in the secret-access Role - the default OpenShift config rejects the wildcard currently used.
=> charts/vault: openshift support

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/webhook-deployment.yaml, charts/vault-secrets-webhook/values.yaml
| New feature?    | Yes
| Related tickets | fixes #1356
Adds a new configuration parameter "topologySpreadConstraint" to the webhook deployment template and the values.yaml.  README updated with  this new parameter
=> [webhook] Adding support for topologySpreadConstraints to helm chart

internal/injector/injector_test.go
It somehow got ignored by a typo.
=> webhook: add back injector to the tests

cmd/bank-vaults/unseal.go, internal/vault/operator_client.go
| Related tickets | fixes #1366 
In case of Vault built-in auto-unseal and raft ha_storage we should build up the raft cluster correctly.
The operator haven't done this before this fix.
Operator and bank-vaults image update is needed as well when testing this.
=> operator: fix raft ha_storage combined with seal stanza

internal/injector/injector.go, pkg/webhook/common.go, pkg/webhook/configmap.go, pkg/webhook/object.go, pkg/webhook/pod.go, pkg/webhook/secret.go, pkg/webhook/webhook.go
| Related tickets | fixes #1379 
Fixing envFrom with inline mutation.
This wasn't working at all if only inline form data was requested. (Was working if there were simple `vault:...` fields as well).
=> webhook: fix inline-mutation for envFrom constructs

cmd/vault-env/main.go
fix panic
```
panic: errors: *target must be interface or implement error
```
`errors.As` will panic if target not a pointer to instance of `error`
`exec.ExitError` is not an instance of `error`, but `*exec.ExitError` is
following code is to reproduce the panic
```go
package main
import (
"errors"
"fmt"
"os/exec"
)
func main() {
cmd := exec.Command("bash", "-c", "exit 42")
cmd.Start()
err := cmd.Wait()
var exitError exec.ExitError
if errors.As(err, &exitError) {
fmt.Println("an ExitError", exitError.ExitCode())
} else {
fmt.Println("not an ExitError", err)
}
}
```
=> update vault-env main

pkg/webhook/registry.go
| Related tickets | May fix  #1384 and #1398
As @fdpeiter suggested, `containerInfo.Namespace` seems to never be empty.  So I changed the condition to only care about the presence of a credential in the pod spec. This will allow to use the default configuration for the auth k8s chain. 
I tried to implement tests but I ran into the use of the remote package which retrieves the image blob.
With this modification, we will always keep the priority of the presence of the configuration in the pod being deployed. 
And this will allow the default configuration to be used in case of absence in this one. 
Since the default value of …
=> fix(webhook-registry): use default value if no ImagePullSecrets was specified in podspec

pkg/sdk/vault/client.go, pkg/webhook/webhook.go
mutated object namespace must be used to inherit  vault policies
With the new feature serviceAccount, it is possible to choose which serviceAccount is used by the webhook to connect to Vault. The problem for me is that this serviceAccount is searched/used in the vault-webhook namespace instead of the mutated object namespace.
In our case, vault policies are namespaced and with this fix, vault-webhook namespace doesn't need to have access on all secrets...
=> fix(webhook): wrong namespace used for serviceaccount

charts/vault-operator/Chart.yaml, charts/vault-operator/README.md, charts/vault-operator/templates/deployment.yaml, charts/vault-operator/values.yaml, charts/vault-secrets-webhook/Chart.yaml, charts/vault/Chart.yaml, hack/acceptance-test.sh
| Related tickets | fixes #1410 
We are removing support for the automatic (and deprecated) etcd-operator install via the vault-operator chart.
etcd-operator is unmaintained and the chart doesn't support `Kubernetes 1.22 <=`.
If you still wish to use etcd-operator the code is still in the code base but you have to install it manually, see the README of the vault-operator for instructions.
=> operator: remove direct etcd subchart support

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/_helpers.tpl, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/templates/webhook-ingress.yaml, charts/vault-secrets-webhook/templates/webhook-pdb.yaml, charts/vault-secrets-webhook/templates/webhook-psp.yaml, charts/vault-secrets-webhook/values.yaml
This fixes chart deployment in clusters with version < 1.21 due to breaking change introduced at https://github.com/banzaicloud/bank-vaults/pull/1404.
Happy to do the same changes in the Vault chart if all looks good.
=> Fix API versions for k8s < 1.21

pkg/sdk/vault/client.go, pkg/webhook/webhook.go
| Related tickets | fixes #917 , completes #1361 
This completes the work in PR #1361 .  This enables mutation of non-pod resources like secrets.  It sets the vault namespace on the underlying `rawClient` used in [pkg/sdk/vault/client.go](https://github.com/banzaicloud/bank-vaults/blob/master/pkg/sdk/vault/client.go)
Even though PR #1361 parses out `vault-namespace` from a resource's annotation, it does not set that value on the underlying vault client.
As described in #917, this is not an issue for pods that set the `VAULT_NAMESPACE` environment variable. Setting this environment variable does get picked up by the …
=> Set Vault Namespace on underlying rawClient if it has a non-empty value

deploy/test-deployment.yaml, pkg/webhook/config.go, pkg/webhook/pod.go, pkg/webhook/pod_test.go, pkg/webhook/registry.go, pkg/webhook/webhook.go
| Related tickets | fixes #1416 
Fix for registry lookup and for a race condition as well in the mutating webhook. Added test for the registry lookup.
Mutation for pods without explicit commands were broken in 1.14.
=> webhook: fix registry lookup, add test for validating it in the future

charts/vault/Chart.yaml, charts/vault/templates/_helpers.tpl, charts/vault/templates/ingress.yaml, charts/vault/templates/pdb.yaml, charts/vault/values.yaml
| Related tickets | fixes #1420
This fixes chart deployment in clusters with version < 1.21 due to breaking change introduced at #1404 but not covered in #1413
The `vault` chart has some places that was missing from the fix.
=> Fix API versions for k8s < 1.21 for the vault chart

pkg/webhook/config.go, pkg/webhook/pod.go, pkg/webhook/pod_test.go
In some cases values from vault are needed for container probes. In this PR I add `vault-env` into exec command of liveness and readiness probes
=> webhook:  mutate container probes

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/values.yaml, cmd/vault-env/main.go, pkg/webhook/config.go, pkg/webhook/pod.go
Add syslog hook to logrus in vault-env.
With this feature, vault-env can log to a remote log server.
=> webhook: add syslog capability to vault-env

charts/vault-operator/Chart.yaml, charts/vault-operator/templates/psp.yaml
set privileged to true on vaultSA PSP
allowPrivilegeEscalation and allowedCapabilities don't work without privileged: true
=> set privileged to true on vaultSA PSP

charts/vault-operator/Chart.yaml, charts/vault-operator/crds/crd.yaml, operator/deploy/cr-audit.yaml, operator/deploy/crd.yaml, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/controller/vault/vault_controller.go
| Related tickets | [#1475](https://github.com/banzaicloud/bank-vaults/issues/1475)
This PR introduce a new Vault CRD attribute that allows to define the filename of the logging config which runs in the `auditlog-exporter` sidecar when `fluentdEnabled` is `true`.
this allow to easily to swap the default sidecar image from `fluentd` to `fluent-bit` which has now extended output capabilities tight to some cloud providers.
Other alternative to make this work have been investigated in related project to avoid this change: [aws-for-fluent-bit](https://github.com/aws/aws-for-fluent-bit/issues/270).
But they seems not willing to …
=> add attribute in the Vault CRD for specific logging config filename.

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/values.yaml
| Related tickets | fixes #1464
The webhook tried to ignore kube-system via the old `name: kube-system` label, but from now on it will try the well-known `kubernetes.io/metadata.name: kube-system` label as well.
About well-known labels https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetes-io-metadata-name
=> webhook: ignore kube-system according to the well-known kubernetes.io/metadata.name label

pkg/sdk/log/parser.go, pkg/sdk/log/parser_test.go
Use ConnectionError const in sdk/log
=> Use const for connection error in logparser

pkg/webhook/webhook.go
| Bug fix?        | yes|
| New feature?    | no|
| API breaks?     | no|
| Deprecations?   | no|
| Related tickets | fixes #1425, finishes #1412|
| License         | Apache 2.0|
The work in #1412 was incomplete.  The webhook also needs need to set `VaultNamespace` on the `VaultClient` when `VaultServiceAccount` is set.  This will address [the problem I mentioned](https://github.com/banzaicloud/bank-vaults/issues/1425#issuecomment-926885734) at the end of #1425, where the Namespace is not set when ServiceAccount is set.
I missed setting Namespace when ServiceAccount is set in #1412.  
When I tested this fix, it allowed me to mutate a Secret by itself when it used the `vault-namespace` and `vault-serviceaccount` annotations.
- [x ] Code meets …
=> Set vault-namespace on the client when vault-serviceaccount is also set

README.md
| Deprecations?   | no|
Fix the broken blog URL in `README.md`
In the `README.md` I found a broken link, furthermore didn't find any newsletter link in the official BanzaiCloud site so I change the text and the URL behind pointing to the blog.
=> docs(readme): change broken newsletter link to blog url

deploy/test-external-secrets-watch-deployment.yaml, internal/vault/operator_client.go, internal/vault/policies.go
| Related tickets | fixes #605
This feature allows purging unmanaged policies from Vault which simply with each sync it lists all policies and remove anything that is not in the `externalConfig`. That way no need to handle any state and it doesn't matter what was in the config previously.
Also, the purge option is disabled by default so there is no change in the behavior and anyone who wants to use it should enable it explicitly.
*How to configure it?*
If the user wants to remove any unmanaged config (just policies at the moment), they just need to add `purgeUnmanagedConfig` under `externalConfig`:
```
externalConfig: …
```
=> feature: add option to purge unmanaged policies from vault

pkg/webhook/config.go, pkg/webhook/pod.go, pkg/webhook/pod_test.go
This PR makes it possible to lock down the `securityContext` of containers that get injected into pods by the webhook.
This is achieved by:
1. Implementing a base `securityContext` shared by all injected containers.
2. Dropping all Linux capabilities by default and adding them back as needed.
3. Adding 4 new pod annotations recognized by the webhook that allow setting the `runAsNonRoot`, `readOnlyRootFilesystem`, `runAsUser` and `runAsGroup` parameters for injected containers.
Added pod annotations:
| Annotation                                       | Default | Explanation
| …
=> webhook: allow securityContext modification for injected containers

internal/vault/operator_client.go, internal/vault/secrets_engines.go
| Related tickets | fixes #605, related to #1503
This PR is the same as #1503 but for Secrets Engines, it allows to remove unmanaged (or manually added secrets engines).
The same as the previous PR, I didn't do much change in the add behavior (just restructure it without change) and added the remove option.
=> Feature: Purge unmanaged config - Secrets Engines

internal/vault/operator_client.go, internal/vault/plugins.go
| Related tickets | fixes #605, related to #1503
This PR is the same as #1503 but for the plugins config. It allows removing unmanaged or manually added plugins config.
The same as the previous PR, I didn't do much change in the add behavior (just restructure it without change) and added the remove option.
Next:
- Add purge options for `Audit Devices` (@wazery will work on it) and `Identity Groups` (I will work on it).
- Migrate Startup Secrets to the new style (it will not have a purge option because it doesn't fit it).
- Documentation and examples.
=> configurer: restructure and support purging plugins

internal/vault/identity_groups.go, internal/vault/operator_client.go, operator/deploy/cr.yaml, vault-config.yml
| Related tickets | fixes #605, related to #1503
This PR is the same as #1503 but for the `identity groups` config. It allows removing unmanaged or manually added identity groups config (groups and group-aliases).
The same as the previous PR, I didn't do much change in the add behavior (just restructure it without change) and added the remove option.
**Next:**
- Add purge options for `Audit Devices` (@wazery will work on it).
- Migrate Startup Secrets to the new style, it will not have a purge option because it doesn't fit it (@wazery will work on it).
- Documentation and examples (I will work on it).
=> configurer: restructure and support purging identity groups

charts/vault-operator/README.md
| Related tickets | mentioned in #1529
Adds the step to create the rbca.yaml on the docs.
If this step is not done the `statefulset.apps/vault` show this events. 
```
Events:
Type     Reason        Age                From                    Message
----     ------        ----               ----                    -------
Warning  FailedCreate  5s (x11 over 10s)  statefulset-controller  create Pod vault-0 in StatefulSet vault failed error: pods "vault-0" is forbidden: error looking up service account default/vault: serviceaccount "vault" not found
```
=> 🔨 Add rbac.yaml to instructions

internal/vault/audits.go, internal/vault/auth_methods.go, internal/vault/operator_client.go, internal/vault/secrets_engines.go
| Related tickets | mentioned in #1520, #1519, #1514, #1513
This PR is part of a series of feature PRs to implement purging unmanaged resources from Vault, you can refer to the previous PR over here #1520 .
This PR handles the logic of purging unmanaged Audit devices, as well as enabling them if they are non-existent.
- Migrate Startup Secrets to the new style, it will not have a purge option because it doesn't fit it (I will work on it).
- Documentation and examples @aabouzaid will work on it.
=> configurer: Purge Un-managed Audit Devices

internal/vault/operator_client.go, internal/vault/startup_secrets.go
| Related tickets | mentioned in #1520, #1519, #1514, #1513, #1532 
This PR is part of a series of feature PRs to implement purging unmanaged resources from Vault, you can refer to the previous PR over here #1532.
This PR just refactors StartupSecrets to be consistent with the new structure.
- Documentation and examples @aabouzaid will work on it.
=> configurer: refactor startup secrets

deploy/test-deploy-templating.yaml, hack/acceptance-test.sh, operator/deploy/cr-raft-1.yaml, pkg/webhook/pod.go, pkg/webhook/pod_test.go
| Related tickets | fixes #1531, fixes #1540
* Fix for capabilities regression introduced in 1.15.0
* Additional acceptance test
1.15.0 introduced a regression in dropping all capabilities necessary for Vault Agent Templating. The PR fixes that by keeping the capabilities drop while adding the bare minimum that is necessary for proper functionality of templating.
In addition to that, the PR adds a new acceptance test that goes through the process of templating. This test will fail the build in case same or similar regression happens in the future.
=> webhook: Fix broken capabilities (#1531)

internal/configuration/template.go
| Related tickets | https://github.com/banzaicloud/bank-vaults/issues/1573
Use `SplitN` instead of `Split` to split environment variables
=> properly split template variables with multiple equal signs

.github/workflows/ci.yml, hack/acceptance-test.sh, hack/kind.yaml, internal/vault/startup_secrets.go, operator/deploy/cr-kvv2.yaml
| Related tickets | https://github.com/banzaicloud/bank-vaults/issues/1576
That's my attempt to enable extra CAS options on writes to KVv2 backend, such as
```
startupSecrets:
- type: kv
path: secret/data/info
data:
data:
APP_LOGIN: user
APP_PASSWORD: password
options:
cas: 0
```
https://github.com/banzaicloud/bank-vaults/issues/1576
=> configurer: Allow to specify options on kv2 writes

operator/pkg/controller/vault/vault_controller.go
This PR sets the `partition` field of the Vault statefulset to `0` to allow restarting all Vault pods.
Without this, the `kubectl rollout restart statefulset vault` command only restarts the last pod of the 3.
`N/A`
=> Set Partition for rolling update

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/values.yaml
In order to control if secret values should be persisted in K8s.
Sometimes this is undesired, as this sensitive data might not
be encrypted at rest and RBAC might not be sufficient to prevent
users from reading data they should not have access to.
Signed-off-by: Lucas Caparelli <lucas.caparelli@gympass.com>
| Related tickets | fixes #1614
A way to control whether to register the Secrets in the MutationWebhookConfiguration.
I've kept the default as `true` so it doesn't break current behavior for users that do not care about this.
=> webhook: Add .Values.secretsMutation to control whether to mutate Secrets

pkg/webhook/config.go
| Related tickets | na
Allows us to set `transit_key_id` and `transit_path` as ENV vars for the web hook instead of requiring an annotation; 
Small usability improvement to set this globally for any secrets/pods/configmaps using transit encryption.
=> webhook: allow setting transit_key_id and transit_path as env vars

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/apiservice-webhook.yaml, charts/vault-secrets-webhook/values.yaml
Allows users to override objectSelectors and namespaceSelectors for a given resource
I have a scenario where I'm mostly using the webhook to mutate secrets globally and not pods. So needed some finer grain controls to allow me to set different selectors for pod mutation vs secret mutation
Tested out different options manually
=> Webhook helm override namespace and object selector

pkg/webhook/config.go, pkg/webhook/pod.go, pkg/webhook/pod_test.go, pkg/webhook/registry.go
Adding skipping tls check functionality for self-signed docker registry 
When you have a self-signed certificate in your docker registry, you can face this error from the k8s job with consul temples config.
`time="2022-05-20T17:31:04Z" level=error msg="Admission review request failed" app=vault-secrets-webhook dry-run=false error="cannot fetch image descriptor: Get \"https://localhost:8443/v2/\": x509: certificate signed by unknown authority" kind=v1/Pod name=test`
None
=> webhook: Add skip registry verify functionality

operator/deploy/cr.yaml
Adds a commented `tlsAdditionalHosts` section to `cr.yaml` to demonstrate how to add extra hosts to the generated CA certificate. I discovered that section by looking at the operator's Go code, it'll be easier for others to discover in the future if it's in one of the CR YAML files.
At present, this option isn't documented anywhere.
- [ x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
=> Add sample tlsAdditionalHosts setting to cr.yaml

.github/workflows/ci-config-crud-e2e.yml, internal/vault/audits.go, internal/vault/secrets_engines.go, scripts/validate-config-crud/validate-config-crud.sh, scripts/validate-config-crud/vault-config.yml
| New feature?    | no/
| Related tickets | fixes #1612
The Audit path default value was overwritten after it was set correctly because using the wrong var to trim.
In the trim process, the var `configs[index].Path` should be used because it was set by the previous if condition.
And to avoid a such issue in the future, I've also added that case (when the "path" would have defaulted to "type") to E2E tests.
=> Fix: use the correct path var for audit and secrets engines

charts/vault-operator/Chart.yaml, charts/vault-operator/crds/crd.yaml, operator/deploy/cr-audit.yaml, operator/deploy/crd.yaml, operator/pkg/apis/vault/v1alpha1/vault_types.go
| Related tickets | fixes #1652
Fixes typo and spelling in Vault CRD spec field `fleuntdConfLocation` -> `fluentdConfLocation`.
First it's a typo and more importantly as per issue #1652 if full CRD spec not applied to enable validation user can use the correct spelling leading to hidden misconfiguration.
=> Fix typo Vault CRD spec field 'FleuntDConfLocation' to 'FluentDConfLocation'

operator/deploy/cr-audit.yaml
I have added a missing syntax, which will make sure that you don't get any errors while applying an audit device using `bank-vaults` 
Current example is incorrect and leads to error.
```
vault-configurer-68cc75cc7d-bkqhs:bank-vaults {"level":"error","msg":"error configuring vault: error configuring audit devices for vault: error configuring managed audits: error enabling audit device  in vault: Error making API request.\n\nURL: PUT https://vault.vault-operator:8200/v1/sys/audit\nCode: 405. Errors:\n\n* 1 error occurred:\n\t* unsupported operation\n\n","time":"2022-07-29T10:42:45Z"} …
```
=> Adding path to avoid error during reconciling

charts/vault-operator/Chart.yaml, charts/vault-operator/templates/servicemonitor.yaml
| Related tickets | fixes #1679
#1679 Almost fixes the `ServiceMonitor` implementation for the operator, but the port name is not correct, this PR fixes that using the correct port defined in [the service](https://github.com/banzaicloud/bank-vaults/blob/ac9e73215916980e3217728de5d97d61d04be27b/charts/vault-operator/templates/service.yaml#L21L23)
Fixes #1679 
Tested on a standalone  deployment, it works
=> Operator: Fix metrics port name for ServiceMonitor in Helm chart

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/values.yaml, pkg/webhook/config.go, pkg/webhook/registry.go
| Related tickets | fixes #1659
Adds the option to specify a default image pull secret service account name.
To solve issue #1659
=> add default pull secret service account

operator/pkg/controller/vault/vault_controller.go, operator/pkg/controller/vault/vault_controller_test.go
| Related tickets | fixes #1572
A single character change to invert the check made on the `FluentdConfFile` field in the spec.
Currently the code checks if the value from the spec is **not** empty making it impossible to override the default. 
If there is no value set it leaves the fluentd config file name as empty string ("").
This means we can only ever use `fluent.conf` or empty string `""` as the name of the config file and the latter causes the validation error seen in #1572 . 
We'd like to set it to `fluent-bit.conf` for use in the `aws-for-fluent` image. 
See: …
=> operator: Fix setting fluentd config file name

internal/injector/injector.go, internal/injector/injector_test.go, pkg/sdk/vault/transit.go, pkg/webhook/config.go, pkg/webhook/configmap.go, pkg/webhook/object.go, pkg/webhook/secret.go
This PR improves performance when using the transit engine with lots of secrets coming in from vault;
When you have lots of secrets that use the transit engine, the webhook is really slow to respond; This is because it's making N number of API calls to vault; We can leverage batch_input to send multiple secrets at once, reducing the overhead and improving the response time of the webhook.
For example - If I have a secret with 20 Values coming from vault... previously this would take about 1.5-2 seconds for the webhook to respond; After this PR since it's only making 1 API call, it takes < 250 ms …
=> webhook: transit engine use batch api calls for better performance

pkg/webhook/pod.go
Added the ability to set the Vault namespace in the vault agent configuration.
Not functional with Vault Enterprise
Try to use the webhook with consul-template : 
* the vault-agent container cannot authenticate with Vault because the namespace is not defined.
* info : the namespace must be defined in the config.hcl file by the user, otherwise the consul-template container fails to authenticate
=> webhook: enable vault-agent namespace for Vault Enterprise

internal/vault/secrets_engines.go
| Related tickets | fixes #1481
Check for nil.
We can't cast `name` to `string` if it's nil. And the user can't work around the problem by providing a `name` to the config, because then we try to POST the config to the wrong path.
=> Don't crash trying to rotate aws config/root.

.github/workflows/docker.yml, .github/workflows/helm.yml
| Q               | A      |
| --------------- | ------ |
| Bug fix?        | no|
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets | - |
| License         | Apache 2.0 |
Replaced `::set-output` with `>> $GITHUB_OUTPUT`
Deprecated, will be removed in 2023-05-31.
Details: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
Tested [in another PR](https://github.com/banzaicloud/koperator/pull/906/files#diff-dce4cd1ca1dc3e5849de0fd3f3c7b132ad537e4ba79ba191f5de4330484b214bR39), worked well.
- ~Error handling code meets the [guideline](https://github.com/banzaicloud/developer-guide/blob/master/docs/coding-style/error-handling-guide.md)~
- ~Logging code meets the guideline~
- ~User guide and …
=> Replaced GHA `set-output` with `GITHUB_OUTPUT`

internal/injector/injector.go, internal/injector/injector_test.go
| Related tickets | fixes #1728
Support embedded templates inside templates as well.
Let's take this example into account, where you need to craft a database url from a secret and encode the password, since it contains some special chars:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: test-db-configmap
annotations:
data:
jdbc: postgresql://foo.bar.svc:5432/mydb?user=${vault:secret/data/account#username}&password=${vault:secret/data/account#${.password | urlquery}}
```
=> injector: fix embedded template parsing

Makefile, deploy/test-configmap-dev.yaml
| Related tickets | #1737 
A useful sample, to enable configmap mutation locally during webhook development, steps are included inline
It is hard and error prone to do tricks with Docker images, tags and chart versions.
[kurun](https://github.com/banzaicloud/kurun) is required for running the webhook locally against a cluster.
=> webhook: local dev environment facilitation

pkg/webhook/config.go, pkg/webhook/pod.go
If VAULT_TOKEN env variable is defined for the webhook pod, forward it to all additional init and sidecar containers. Do not add Vault Agent container if the variable is defined because looks like it's impossible to reuse an existing token when using Vault agent.
It's possible to inject secrets into pod, secrets, configmaps and use Consul templates to generate configuration files when explicitly specifying VAULT_TOKEN, so you bypass kubernetes authentication method if using Minikube.
=> webhook: Add VAULT_TOKEN support

pkg/webhook/webhook.go
| Related tickets | fixes #1738
Currently the webhook tries to find sa.secrets[0]
and load its token. But this is no longer available from K8S 1.24 (unless users force creating legacy
tokens on each sa which is not best practice). This change allows creating tokens by calling the apiserver instead of expecting it to be available as a k8s
secret associated to the service account.
This change allows creating tokens by calling the apiserver if the service account does not have  an associated secret with a legacy token.
From k8s 1.24 service account no longer have associated tokens stored in k8s secrets.
tested on EKS 1.24
- …
=> webhook: create sa tokens via apiserver

internal/injector/injector.go
This PR changes the log level from ERROR to WARNING when missing secrets are allowed.
Currently, when using annotation `vault.security.banzaicloud.io/vault-ignore-missing-secrets`, an error is logged with message `path not found: %s`, but in the [documentation](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/annotations/) of this annotation says: `When enabled will only log warnings when Vault secrets are missing`
=> fix: log with warning level instead of error if missing secrets are allowed

charts/vault/Chart.yaml, charts/vault/templates/secret-cleanup.yaml, hack/acceptance-test.sh
| Related tickets | #1760
Added a pre-delete Helm chart hook to cleanup secret used to unseal Vault.
So if Vault is installed, then deleted and installed again with Helm, it won't complain that this secret already exists.
=> Secret-cleanup pre-delete hook in vault Helm chart

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/webhook-rbac.yaml
| Related tickets |  fixes #1759 
Disables the ability for the webhook to modify secrets if the secret webhook is not enabled as the service no longer needs permissions once it is disabled.
Having the webhook overly permissible is a concern within my organization.
=> webhook: set conditional around unused verb when not using secrets mutation

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/README.md, charts/vault-secrets-webhook/templates/webhook-deployment.yaml, charts/vault-secrets-webhook/values.yaml
This PR adds an option in the chart to configure the deployment strategy. 
I've recently looked for a way to change the deployment strategy of the webhook pods without using kustomize.
=> chart/webhook: allow to customise the deployment strategy

internal/injector/injector.go, internal/injector/injector_test.go
I have noticed that the new `preprocessTransitSecrets` is calling `inject` even if nothing has been replaced with values from the transit cache. 
In case you are working with "maps" (ConfigMap, Secret) this does not matter as the "old" code will still overwrite the key with the secret. But in the case of `vault-env` you will have the same env var set twice and most the the time only the first occurence (without the secret) is taken into account.
Since https://github.com/banzaicloud/bank-vaults/pull/1697 we are experimenting issues with `vault-env`: the generated environment has all the env vars …
=> vault-env: fix vault-env generated env which may contain duplicates

cmd/bank-vaults/main.go
| Bug fix?        |  yes
This PR fixes typo for the --once flag description
This PR fixes typo for the --once flag description
=> Fixed typo for once flag description

cmd/vault-env/main.go, pkg/webhook/pod.go
| Related tickets | fixes #1788 
Fix for `panic: runtime error: integer divide by zero` when using transit-encrypted secrets in deployments.
TransitBatchSize was never set when entering from the vault-env main function.
Tested manually.
=> vault-env: set TransitBatchSize in vault-env config

charts/README.md, charts/vault-operator/Chart.yaml, charts/vault-operator/crds/crd.yaml, charts/vault-secrets-webhook/Chart.yaml, charts/vault/Chart.yaml, operator/deploy/cr-containers.yaml, operator/deploy/crd.yaml, operator/pkg/apis/vault/v1alpha1/vault_types.go, operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go, operator/pkg/controller/vault/vault_controller.go
| Related tickets | fixes #1354
This PR allows additional sidecars to be provided.
Allowing additional sidecars allows you to connect the vault sts to cloudsql using [cloudsql-proxy](https://github.com/GoogleCloudPlatform/cloudsql-proxy/tree/main/examples/k8s-sidecar) for dynamic mysql credential generation. Additionally, you can provide sidecars for log extraction without using fluentd.
Tested locally to ensure the cr-containers deploy works as expected.
=> Add extra containers

ADOPTERS.md
Adding Wildlifestudios as an Adopter
We have been using vault-secrets-webhook for some years now and I saw the slack message asking for users to add themselves to the adopters list.
=> Add Wildlife Studios as an adopter

pkg/kv/k8s/k8s.go
| Related tickets | fixes #1814 
Simple fix to allow the code to populate an empty Kubernetes secret.
=> Fix panic when secret is empty

go.mod, go.sum, internal/vault/operator_client.go
| Related tickets | fixes #1787 
This PR checks the seal type and uses the according parameters in the init API call. Furthermore, I updated the vault go api.
This PR is the successor of #1795. I had to create a new one because GitHub force-pushed to my fork and automatically closed the PR when syncing the branch. Sorry for the confusion.
=> fix: Add missing parameters when using auto unseal

pkg/webhook/config.go, pkg/webhook/configmap_test.go, pkg/webhook/pod.go, pkg/webhook/pod_test.go
| Related tickets | fixes #1782 
This feature enables environment variables to be set In the vault init container
=> 1782: allow env to be set in vault init container

charts/vault/Chart.yaml, charts/vault/templates/statefulset.yaml, operator/pkg/controller/vault/vault_controller.go
| Related tickets | fixes #1813
Adds a startup probe to the vault container, allowing it 3 minutes to start up instead of 30 seconds from the liveness probe
Vault instances with large numbers of leases can take longer than 30 seconds to load the database
=> Add startup probe to vault container

go.mod, internal/vault/operator_client.go
| Related tickets | fixes #1808 
This PR checks the seal recovery key support and uses the according parameters in the init API call.
This PR fixes the initialization of vaults that use a seal type that supports only recovery keys and vice versa.
Vault 1.12.0 introduced parameter validation in the operator init request. In the cases where the unseal type does not support recovery keys and recovery keys are provided, the initialization will fail. The same case applies to unseal types that do support recovery keys and secret keys are provided. The related Vault change can be found …
=> fix: Honor vault operator init parameter validation

pkg/webhook/config.go
Removed the remains of the annotation `vault.security.banzaicloud.io/mutate-configmap`.
The logic for it has been already removed for some time, since the feature to mutate configmaps can be enabled on the webhook level in the chart (it is disabled by default).
Removing the annotation from the docs is [on the way](https://github.com/bank-vaults/bank-vaults.dev/pull/106).
=> webhook: remove obsolete mutate-configmap annotation

charts/vault-secrets-webhook/Chart.yaml, charts/vault-secrets-webhook/templates/_helpers.tpl, charts/vault-secrets-webhook/templates/webhook-cert-manager.yaml
| Related tickets | fixes #1844 
Fixed using a pre-existing serving certificate provided in the webhook helm cart. Previously the name of the given cert did not got to all places it needed to be because the `vault-secrets-webhook.servingCertificate` helper function always returned the same string.
So the chart could be used with an existing cert using the following config:
```shell
helm install vault-secrets-webhook banzaicloud-stable/vault-secrets-webhook \
--set certificate.generate=false \
--set certificate.servingCertificate=<certificateName> \
--namespace <namespaceName>
```
Tested locally.
=> webhook: fix webhook servingCertificate helm issue

pkg/webhook/webhook.go
As described in the mentioned issues, there is a need to define a role based on variables such as the Namespace or ServiceAccount involved.
Instead of manually training developers to set the right annotation, we could define a default using templating to ensure the right role for the right namespace or other concepts.
| Related tickets | fixes #1160 #954
We want to be able to define the vault role setting with a default of the form _"k8s.\<namespace\>"_, where namespace is the namespace of the pod. Being able to supply a template for the vault role in the settings for the webhook would grant sufficient flexibility.
Hence …
=> templating support for vault-role setting

Dockerfile
Added template binary to the docker image
The template binary was left out from the Dockerfile when it was refactored, causing an error in the `config-templating` initContainer when started a Vault with the operator:
```
failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "template": executable file not found in $PATH: unknown         
```
=> Added template binary to docker image

internal/vault/startup_secrets.go
| Related tickets | fixes #1666 
Added support for creating startup secrets in v1 KV Secrets engines by the Bank-Vaults operator. It only works if `version: 1` is specified in the secrets engine's options, otherwise still version 2 format is considered to be default, as this is the default for Vault as well.
Previously the way the operator handled startup secrets didn't work with Version 1 KV Secrets engines, the secrets were not created correctly (see issue #1666). Now if you use a similar config in the CRD, the startup secrets will be created correctly in the related Secrets engine:
```yaml
spec:
externalConfig: …
```
=> configurer: Startup secret support for v1 kv engine

.gitignore, cmd/bank-vaults/common.go, cmd/bank-vaults/main.go, pkg/kv/awskms/awskms.go
This PR introduced a new feature allowing you to configure the AWS KMS encryption context
In some cases, existing recovery/unseal keys may have been encrypted with a different encryption context
In our use case, we have an existing vault cluster that has existing unseal keys that are encrypted with a custom encryption context. This feature will allow us to migrate this vault cluster to be managed by bank-vaults.
=> feat: Add configurable AWS KMS encryption context

.github/workflows/ci.yaml, .github/workflows/e2e.yaml
Fixes https://github.com/bank-vaults/bank-vaults/issues/2040
Hashicorp has deprecated Duplicative Docker Images (see https://developer.hashicorp.com/vault/docs/v1.13.x/deprecation).
New versions of vault are only published to https://hub.docker.com/hashicorp/vault.
https://hub.docker.com/_/vault only contains old versions up to 1.13.3.
=> chore: Use verified publisher image `hashicorp/vault`

cmd/bank-vaults/main.go, pkg/kv/awskms/awskms.go
This PR fixes three bugs, two of which has been introduced in #1968:
- Fixes the default value for encryption context
- Fixes flags for map types
- Fixes AWS KMS encryption context for encryption
=> Fix AWS KMS encryption context

.github/workflows/ci.yaml, .github/workflows/e2e.yaml
Update to `hashicorp/vault:1.14.1` due to bug: https://github.com/hashicorp/vault/issues/21465
=> chore: Update to `hashicorp/vault:1.14.1`

Dockerfile
=> fix: add back missing pcscd entrypoint script

.licensei.toml
This new licence is what Hashicorp recently switched to.
Fixes #2121
=> fix(licensei): add busl-1.1 to approved list

cmd/bank-vaults/configure.go, cmd/bank-vaults/unseal.go, internal/configuration/template.go, internal/vault/audits.go, internal/vault/auth_methods.go, internal/vault/identity_groups.go, internal/vault/plugins.go, internal/vault/secrets_engines.go, pkg/kv/hsm/hsm.go, pkg/kv/k8s/k8s.go, scripts/configure-sshd.sh
This PR corrects spelling mistakes in the error message, info logs, unexported variable names, cmd description, and comments.
Is it safe to change the error message? Because it can break functions that depend on this specific error message.
=> fix: Typos in errors, logs, vars, and comments

pkg/kv/hsm/hsm_test.go
This PR fixes the build tag in one test file via running `go fix ./...`.
`// +build` has been obsolete since Go 1.18. It was replaced by `//go:build`. See [the SO answer](https://stackoverflow.com/questions/10646531/golang-conditional-compilation/67937234#67937234) for details.
=> chore: fix buildtag

cmd/template/main.go, internal/configuration/template.go, internal/vault/auth_methods.go, pkg/kv/alibabaoss/oss.go, pkg/kv/dev/dev.go, pkg/kv/file/file.go, pkg/kv/gcs/gcs.go, pkg/kv/s3/s3.go
This PR replaces the deprecated in Go 1.17 package [io/ioutil](https://pkg.go.dev/io/ioutil) with `io` and `os` packages. 
The changes are not user-facing and are safe to merge.
=> Replace deprecated io/ioutil with io and os

.golangci.yml, cmd/bank-vaults/common.go, cmd/bank-vaults/main.go, cmd/bank-vaults/unseal.go, internal/vault/auth_methods.go
This PR modifies `golangci-lint` config:
- enables and fixes `dupword` lint issues;
- enables `exhaustruct`, `contextcheck` linters;
- moves `golint, scopelint, nosnakecase` under the deprecated comment.
=> fix: dupword lint; mark few linters as deprecated

cmd/bank-vaults/common.go, cmd/bank-vaults/main.go
This PR removes viper's pflag `StringToString` workaround as https://github.com/spf13/viper/issues/608 is already fixed in [1.7.0](https://github.com/spf13/viper/releases/tag/v1.7.0).
=> cli: remove viper StringToString pflag workaround

pkg/kv/awskms/awskms.go
Regarding issue #1823.  When migrating keys from kubernetes secret to s3 bucket, the migrate script https://bank-vaults.dev/docs/unseal-keys/#aws-1 results in a key with a newline at end.  When retrieved from the s3 bucket and passed to vault, vault rejects the key.  
Fixes #1823 
added strings.TrimSpace(string(out.Plaintext)) to remove trailing newline.
Tested by deploying to private ecr, editing pod vault-configurer and updating with private ecr image.  Configurer was able to config audit device.  Edited each of the vault-X pods with private ecr image.  Vault pods were able to connect to vault and unseal.
I am not sure if this could be fixed in the script.  TrimSpace will not hurt existing installations as the the key value will not be changed.
=> fix: Issue #1823 - moving vault keys from kube secret to aws s3

internal/vault/secrets_engines.go
This MR fixes #2462 to set the cache-config of the secrets engine
=> feat: Allow to set transit cache-config

internal/vault/operator_client.go, pkg/kv/awskms/awskms.go
This PR fixes a bug in the configurer in cases where a recovery type unseal is used.
The configurer first checks what key type to use before getting it from the key store.
I've also added a fix for canceling any inflight root token generations that are remnants from previous attempts.
Another fix I added was the missing KMS key ID from the decrypt function.
=> fix: Use correct unseal key name in cofigurer

.golangci.yml, .yamlignore, .yamllint.yaml, cmd/bank-vaults/completion.go, cmd/bank-vaults/configure.go, cmd/bank-vaults/init.go, cmd/bank-vaults/unseal.go, flake.lock, flake.nix, internal/vault/operator_client.go, internal/vault/secrets_engines.go, pkg/kv/hsm/hsm_test.go
- Updated Nix, fixed Vault version to the latest (1.14.8) with MPL2.0 license. 
- Fixed linter violations.
- After Nix was updated, the HSM integration test broke, until resolved it is turned off: https://github.com/bank-vaults/bank-vaults/issues/2726
Fixes a [Backlog item](https://github.com/orgs/bank-vaults/projects/2/views/1?filterQuery=nix&pane=issue&itemId=48311457)
=> chore: update nix

.github/workflows/artifacts.yaml
Adds cosign container image signing to sign all image artifacts. Use cosign to verify signatures via:
```bash
cosign verify \
ghcr.io/bank-vaults/bank-vaults:latest \
--certificate-oidc-issuer https://token.actions.githubusercontent.com \
--certificate-identity https://github.com/bank-vaults/bank-vaults/.github/workflows/artifacts.yaml@refs/heads/main 
```
> Note: All images post-v1.31.1 version are signed by default.
=> feat(build): add image signing GH action

.github/workflows/artifacts.yaml
This PR adds a check into the artifact signing step of the build process, so the workflow will only sign the artifact (using cosign) when it's called by the repositories within the same GitHub organization.
This fix is to prevent other arbitrary repositories from using the certificate identity `https://github.com/bank-vaults/bank-vaults/.github/workflows/artifacts.yaml@refs/heads/main` to sign their artifacts
The cosign feature was originally added by this PR: https://github.com/bank-vaults/bank-vaults/pull/2756
=> chore(build): check calling repository before cosign signing

.github/workflows/artifacts.yaml, .goreleaser.yaml, Makefile, cmd/bank-vaults/main.go, cmd/template/main.go, flake.lock
- This PR bumps Goreleaser to 2.0.0
=> chore: bump goreleaser

go.mod, go.sum, internal/vault/auth_methods.go
Vault supports reading its own /var/run/secrets/kubernetes.io/serviceaccount/token and since version 1.9.0 it can handle short lived tokens. The removed code prevented that handling to occur.
Looking at the compatibility matrix for vault operator I'd say loosing functionality for vault pre 1.9.0 should be fine:
https://github.com/bank-vaults/vault-operator/blob/main/VERSIONS.md
More details on how vault is handling Kubernetes tokens: https://developer.hashicorp.com/vault/docs/auth/kubernetes#kubernetes-1-21
Fixes #1603
=> fix: don't set static token_reviewer_jwt

.github/workflows/artifacts.yaml, .goreleaser.yaml, Makefile, flake.nix
- Building of Bank-Vaults was a bit hacky since the pkcs11 package can't be built with simple Go Crosscompiling, so we used xgo, but that is not directly supported in GoReleaser, so we did the actual compilation with xgo in post hooks for all targets.
- This PR introduces [Goreleaser-cross](https://github.com/goreleaser/goreleaser-cross)
Fixes #2074
=> feat: switch from xgo to gorelaser-cross

internal/vault/auth_methods.go
This PR adds support for AWS Identity Integration: https://developer.hashicorp.com/vault/api-docs/auth/aws#configure-identity-integration.
Fixes #(issue)
https://github.com/bank-vaults/bank-vaults/issues/2621
```
auth:
- path: aws-iam
type: aws
roles:
- name: test
bound_iam_instance_profile_arn:
- <your instance profile>
policies:
- <your policy>
ttl: 12h
inferred_entity_type: ec2_instance
inferred_aws_region: <your aws region>
auth_type: iam
token_type: service
```
```
$ vault read /auth/aws-iam/config/identity
Key             Value
---             -----
...
iam_metadata    [account_id auth_type]
```
The IAM metadata value is [account_id auth_type] by default.
```
auth:
- path: aws-iam
type: aws
config:
aws-identity-integration:
iam_metadata: canonical_arn
roles:
<unchanged>
```
```
$ …
```
=> feat: add support for AWS Identity Integration

internal/vault/auth_methods.go, internal/vault/operator_client.go
To be able to use a plugin as authentication backend, plugins need to be loaded before authentication configuration happens. Once loaded, the plugin can now be used as authentication method.
It would be used with a config file like the following:
```
auth:
- path: aws-iam
type: plugin
options:
plugin_name: my-vault-plugin-auth-aws
roles:
- name: 'myRoleName'
bound_iam_instance_profile_arn:
- 'myInstanceProfile'
ttl: 12h
inferred_entity_type: ec2_instance
inferred_aws_region: us-east-1
auth_type: iam
token_type: service
plugins:
- plugin_name: vault-plugin-auth-aws
command: vault-plugin-auth-aws
sha256: <sha256hash>
type: auth
```
Fixes #(issue)
https://github.com/bank-vaults/bank-vaults/issues/3091
=> feat: Vault plugins can be used for authentication

internal/vault/auth_methods.go
Fixes an issue where if authMethod.Config is present only the first auth mount is configured even if multiple are included in the config file.
This is because the additional configuration code added in https://github.com/bank-vaults/bank-vaults/pull/3089 to support the `aws-identity-integration` option returns an error for all other `configOptions` rather than continuing to loop over each subsequent option. The result is that `addManagedAuthMethods` returns immediately after configuring the first auth mount, skipping any additional auth mounts.
This issue was silently occurring because `errors.Wrap` returns nil if err = nil so when this default case was being hit it was returning from `addManagedAuthMethods` early with a nil err.
Fixes …
=> fix: only first auth mount with authMethod.Config would be configured

internal/vault/operator_client.go
Fixes #(issue)
We should not throw error when unseal keys are not found or else first pod can't initialize the Vault Cluster
I've introduced this error in PR #3310. Related to issue #3309
=> fix: keys may not exist yet
