bank-vaults/bank-vaults

cmd/bank-vaults/unseal.go

Return condition to a proper place

---

cmd/bank-vaults/unseal.go

Reverts banzaicloud/bank-vaults#8

Revert "Allow init & unseal in one go"

---

pkg/kv/k8s/k8s.go

Remove double b64 encoded secret

---

cmd/examples/main.go
vault/vault.go

The token renewing logic is no revised and more robust.

Renewer fix

---

pkg/vault/vault.go
vault-config.yml

Add support for very basic aws auth configuration (roles)

Add aws auth configuration

---

README.md

@bonifaido yamls are moved, readme needs to follow

fix yaml path

---

.circleci/config.yml
auth/tokenstore.go

I have sneaked in some build fixes as well.

Differentiate token not found case

---

operator/deploy/cr-etcd-ha.yaml
operator/deploy/cr-gcs-ha.yaml
operator/deploy/etcd-operator.yaml
operator/deploy/operator.yaml
operator/pkg/stub/handler.go
pkg/tls/tls.go
pkg/tls/tls_integration_test.go

TLS library package integrated
Fixes: #80

etcd: full TLS support on client, peer and operator level

---

cmd/bank-vaults/main.go
cmd/bank-vaults/util.go
operator/pkg/apis/vault/v1alpha1/types.go
pkg/kv/s3/s3.go

Fixes: https://github.com/banzaicloud/banzai-charts/issues/275

Add support for specifying AWS Region

---

operator/pkg/stub/handler.go

- also this change updates the vault.spec field in the statefuleset if the vault root configuration changes.
Fixes: #99

Vault should run in a StatefulSet

---

cmd/bank-vaults/unseal.go

Add Unseal --once flag

---

operator/README.md
operator/deploy/operator.yaml

Add OPERATOR_NAMESPACE to deployment sample

---

operator/pkg/stub/handler.go

Open cluster port as well for Vault

---

operator/deploy/cr.yaml
operator/pkg/apis/vault/v1alpha1/types.go
operator/pkg/stub/handler.go

operator: support specifying pod annotations

---

pkg/vault/vault.go

Validate external Vault configuration

---

README.md

Took me a fair amount of investigation to get the unsealing working in our setup. Added documentation that will, hopefully, prevent others from wasting as much time and focus on unseal their own Vault when using AWS with KMS/S3.

[DOC] Linting and expand AWS section

---

operator/pkg/apis/vault/v1alpha1/types.go

Fix annotations nil map assignment

---

operator/pkg/stub/handler.go

Fixes: #134 
The issue was introduced in yesterday's breaking change in statsd exporeter :) https://github.com/prometheus/statsd_exporter/commit/82f75d3b9ad053751cc2a5fe869c321b64a47934

Fix statsd's new dash style

---

auth/tokenstore.go

Needed for storing tokens with values.

Add value field to auth.Token

---

operator/README.md
operator/deploy/etcd-operator.yaml
operator/deploy/etcd-rbac.yaml
operator/deploy/operator.yaml

Also, the ETCD setup is streamlined, no more auto-creation of CRDs.

Various RBAC fixes around Operator sample deployments

---

pkg/vault/vault.go
vault-config.yml

Method to handle configuring Kubernetes auth method through configuration yaml. #46

Handling kubernetes auth config

---

pkg/vault/vault.go

Fix Kubernetes auth configuration

---

Gopkg.lock
operator/deploy/cr-azure.yaml
pkg/kv/azurekv/iam.go
pkg/kv/azurekv/keyvault.go

Fixes: #161 
This PR enables file-based Azure KV authentication very similarly to the AWS solution.

Improve Azure file based auth

---

operator/pkg/apis/vault/v1alpha1/types.go
operator/pkg/stub/handler.go

Hello, noticed that this issue was floating around for a while https://github.com/banzaicloud/bank-vaults/issues/83

Make etcd version configurable 

---

operator/cmd/vault-operator/main.go
pkg/kv/dev/dev.go
pkg/kv/k8s/k8s.go
pkg/tls/tls.go

Add an http health endpoint which can be used by Kubernetes as a liveness probe

---

pkg/auth/auth.go
pkg/auth/tokenstore.go
pkg/auth/tokenstore_test.go

Fixes: https://github.com/banzaicloud/bank-vaults/issues/75

add ExpiresAt to tokens and remove expired ones

---

README.md
pkg/vault/operator_client.go

Add [gcp]  auth backend support
[gcp]: https://www.vaultproject.io/docs/auth/gcp.html

Add gcp auth backend support

---

pkg/auth/tokenstore.go

Fixes:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf01cbf]
goroutine 93 [running]:
github.com/banzaicloud/pipeline/vendor/github.com/banzaicloud/bank-vaults/pkg/auth.vaultTokenStore.GC(0xc0008649f0, 0xc00000c690, 0x1, 0x101)
/go/src/github.com/banzaicloud/pipeline/vendor/github.com/banzaicloud/bank-vaults/pkg/auth/tokenstore.go:272 +0x9f
github.com/banzaicloud/pipeline/auth.StartTokenStoreGC.func1(0xc00083e460)
/go/src/github.com/banzaicloud/pipeline/auth/authn.go:223 +0x90
created by github.com/banzaicloud/pipeline/auth.StartTokenStoreGC
/go/src/github.com/banzaicloud/pipeline/auth/authn.go:220 +0x52
```

Fix race condition between token list/lookup/removal

---

operator/deploy/cr.yaml
operator/pkg/apis/vault/v1alpha1/types.go
operator/pkg/stub/handler.go

Fixes: https://github.com/banzaicloud/bank-vaults/issues/200

Add ServiceAccount configurability to CRD

---

README.md

Forgot change the readme's description for `envsConfig`

---

operator/deploy/cr.yaml

Document serviceType through an example

---

cmd/examples/main.go
operator/deploy/rbac.yaml

Add auth-delegator binding to vault-operator service account

---

README.md
cmd/bank-vaults/main.go
cmd/bank-vaults/util.go
pkg/kv/file/file.go

This helps us to create local (dev) persistent Vault instances for development purposes, and what else.

File based unsealing

---

operator/pkg/stub/handler.go
pkg/vault/operator_client.go

Fixes: https://github.com/banzaicloud/bank-vaults/issues/215

Fix for in faulty leader state in metrics

---

pkg/vault/client.go

The BeaerToken attribute of the k8s Config will not be filled in future k8s.io/go-client versions, so this breaks the Vault login.

Make k8s incluster config based auth future proof

---

operator/deploy/cr-aws.yaml
operator/deploy/cr-azure.yaml
operator/deploy/cr-credentialFromSecret.yaml
operator/deploy/cr-etcd-ha.yaml
operator/deploy/cr-gcs-ha.yaml
operator/deploy/cr-podAntiAffinity.yaml
operator/deploy/cr.yaml
operator/deploy/rbac.yaml

separate vault service account in examples

---

Gopkg.lock
Gopkg.toml
pkg/kv/azurekv/iam.go
pkg/kv/azurekv/keyvault.go

Improve Azure KV authentication with NewAuthorizerFromEnvironment

---

operator/cmd/vault-operator/main.go
operator/deploy/operator.yaml
operator/pkg/stub/handler.go

Make logLevel configurable via OPERATOR_LOG_LEVEL

---

operator/deploy/rbac.yaml

Add secret reading role to vault service account

---

README.md
cmd/vault-env/main.go
cmd/vault-secrets-webhook/main.go
deploy/test-deployment.yaml
pkg/vault/client.go

Add vault auth path to webhook

---

cmd/vault-env/main.go
cmd/vault-secrets-webhook/main.go
deploy/test-deployment.yaml

webhook: support injecting secrets into initContainers

---

Dockerfile.vault-env
deploy/test-deployment.yaml

Fixes: #247 static binary issues

Make vault-env a static binary

---

cmd/vault-env/main.go

`secret.Data` already parsed the data property.

Remove unnecessary data property.

---

operator/deploy/rbac.yaml

add missing namespace to ClusterRoleBinding

---

operator/deploy/cr-aws.yaml

/operator/deploy/cr-aws.yaml: update config aws/s3

---

.circleci/config.yml
cmd/examples/main.go
hack/acceptance-test.sh
operator/cmd/manager/main.go
operator/deploy/cr-etcd-ha.yaml
operator/deploy/operator.yaml
operator/deploy/rbac.yaml

Introduce acceptance tests

---

operator/pkg/controller/vault/vault_controller.go

redeploy vault-configurer if CRD changes

---

cmd/examples/main.go
pkg/vault/client.go

Initial token arrived timeout

---

operator/pkg/controller/vault/vault_controller.go

operator: update etcd when corresponding part of the CRD changes

---

Dockerfile.webhook
cmd/vault-secrets-webhook/main.go

Also, set it to false by default.

Make webhook debug configurable

---

hack/Dockerfile.fluentd
operator/deploy/cr-audit.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go
pkg/vault/operator_client.go
vault-config.yml

Configuring audit devices and CRD example

---

operator/deploy/cr-etcd-ha.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go
operator/pkg/controller/vault/vault_controller.go

Make etcd backend durable via PVC

---

Gopkg.lock
Gopkg.toml

Bump operator-sdk version to 0.4.0

---

pkg/vault/client.go

Handle SIGSEGV in NewClientWithConfig

---

operator/deploy/cr.yaml
pkg/vault/operator_client.go
vault-config.yml

Support writing secrets to vault during configuration

---

Gopkg.lock
Gopkg.toml
operator/cmd/manager/main.go
operator/deploy/operator.yaml

operator: separate liveness and readiness checks

---

operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go
operator/pkg/controller/vault/vault_controller.go

make etcd PersistentVolumeClaimSpec optional

---

Makefile
README.md
cmd/vault-secrets-webhook/main.go

Supporting mutate valueFrom and envFrom

---

README.md
pkg/vault/operator_client.go

this is a duplicate of https://github.com/banzaicloud/bank-vaults/pull/328

Add JWT Auth backend support

---

README.md
pkg/vault/operator_client.go
vault-config.yml

configurer: fix Kubernetes auth out of cluster

---

pkg/vault/operator_client.go

* Allow every currently supported auth backend to be mounted on a custom path 
* Add support for description when mounting a new auth backend 
* Defaults to ("%s backend", authmethodType)

add Auth backend support for custom path and description

---

cmd/vault-secrets-webhook/main.go

Fix envFrom empty handling

---

cmd/bank-vaults/configure.go
pkg/vault/operator_client.go

configurer: support multiple configuration files

---

cmd/vault-env/main.go

Hello @bonifaido,
I tried to play around with golang and have come up with this. It addresses #341 issue. Please let me know your considerations.

[vault-env] added VAULT_* environment sanitization

---

Dockerfile.webhook
cmd/vault-secrets-webhook/main.go

vault-secrets-webhook run as nobody with unprivileged port

---

cmd/bank-vaults/configure.go
operator/deploy/config.yaml
operator/pkg/controller/vault/vault_controller.go
pkg/vault/operator_client.go

support multiple external ConfigMaps

---

cmd/bank-vaults/configure.go

remove redundant and incorrect active check in new HA setup

---

operator/deploy/cr-customports.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

https://github.com/banzaicloud/bank-vaults/issues/372

add the ability for custom ports

---

operator/deploy/cr-customports.yaml
operator/pkg/controller/vault/vault_controller.go

To prevent the StatefulSet from being always re-created.

getServicePorts should sort the values returned

---

cmd/bank-vaults/configure.go

Will exit on any configuration error with status code 1
Useful for running bank-vaults in CI to test policies before merging
Fixes: #388

Add "--fatal" flag to configurator

---

README.md

Add AWS Secret engine example

---

cmd/bank-vaults/configure.go
operator/deploy/cr-prometheus.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

Add disable-statsd flag

---

.circleci/config.yml
hack/acceptance-test.sh
pkg/vault/client.go

An error could cause the client to leak two goroutines + some updates.

Small fixes

---

cmd/bank-vaults/configure.go
cmd/bank-vaults/init.go
cmd/bank-vaults/unseal.go
pkg/kv/alibabakms/kms.go
pkg/kv/alibabaoss/oss.go
pkg/kv/awskms/awskms.go
pkg/kv/azurekv/keyvault.go
pkg/kv/dev/dev.go
pkg/kv/file/file.go
pkg/kv/gckms/cloudkms.go
pkg/kv/gcs/gcs.go
pkg/kv/k8s/k8s.go
pkg/kv/kv.go
pkg/kv/s3/s3.go
pkg/vault/client.go
pkg/vault/operator_client.go

Implement backend test

---

operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

As etcd is quite an important component should we choose to use it for vault storage it would be great if we could set resources on this component in the operator to be passed down to the etcd operator.

operator: allow setting of etcd resources

---

go.mod
pkg/vault/operator_client.go

configurer: format policies before posting them

---

.circleci/config.yml
.dockerignore
Dockerfile
Dockerfile.operator
Dockerfile.vault-env
Dockerfile.webhook
operator/deploy/cr-audit.yaml
operator/deploy/cr-aws.yaml
operator/deploy/cr-azure.yaml
operator/deploy/cr-credentialFromSecret.yaml
operator/deploy/cr-customports.yaml
operator/deploy/cr-etcd-ha.yaml
operator/deploy/cr-gcs-ha.yaml
operator/deploy/cr-nodeAffinity.yaml
operator/deploy/cr-podAntiAffinity.yaml
operator/deploy/cr-resource.yaml
operator/deploy/cr.yaml

- Bump alpine, Vault and Go versions in CI and Docker images.
- Reduce Docker context.

Version updates + .dockerignore improvements

---

operator/deploy/cr-aws.yaml
operator/deploy/cr.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go

Operator: add common unseal options

---

README.md
cmd/bank-vaults/configure.go
operator/deploy/config-jwt-groups.yaml
pkg/vault/operator_client.go

This is an initial implementation of groups and group-aliases support
* Creating **external** Groups with policies and metadata associated to them 
* Right now it does not directly support adding identities to it , see below for "Possible improvements"
* Creating group aliases to reference external groups to the group membership
* Internal groups are not supported - only external groups are supported for now , see this [example](https://learn.hashicorp.com/vault/identity-access-management/iam-identity#step-4-create-an-external-group)
* Backends that support external groups are , not limited to, _jwt_, _oidc_, _github_, _ldap_
* Some auth backends already support mapping , that was before identity was added to vault. JWT/OIDC is not one of them and groups are only supported through this 
* …

Initial implementation of Groups and Groups aliases

---

operator/deploy/cr-gcs-ha-autounseal.yaml

Add an example of how to use autounseal on gcp

Add example CR configuration with autounseal on GCP

---

cmd/vault-secrets-webhook/main.go

we changed the name

---

pkg/vault/operator_client.go

Remove leaked configuration from error log

---

operator/deploy/operator-rbac.yaml
operator/pkg/controller/vault/vault_controller.go

Fixes: #437 
The operator Helm charts has to be updated as well to add RBAC extensions.

operator: fix resource quota issues via checking and upgrading existing objects

---

cmd/vault-secrets-webhook/main.go
docs/mutating-webhook/consul-template.md

add the ability to run consul-template _NOT_ in daemon mode. Great for jobs.

allow it so consul-template can be run in daemon mode

---

cmd/vault-env/main.go
pkg/vault/client.go

This PR contains a number of improvements for the Bank Vaults client.

Bank vaults client constructor improvements

---

pkg/vault/operator_client.go
vault-config.yml

configurer: tls cert auth support

---

Makefile

- Add missing `make docker-vault-env`

Add missing vault-env image build

---

.circleci/config.yml
hack/acceptance-test.sh

add webhook coverage to acceptance test

---

cmd/vault-secrets-webhook/secret.go

Check auth credentials existence

Check auth credentials existence

---

docs/mutating-webhook/README.md

- vault-secrets-webhook: add annotate command in case of secrets

Fix readme

---

cmd/vault-secrets-webhook/secret.go
hack/acceptance-test.sh
operator/deploy/cr.yaml

- fix docker secret mutator
- add ci test for it

Fix docker secret mutator

---

hack/acceptance-test.sh

print last command on exit as well (helps debugging)

add secret validation to CI test

---

pkg/vault/operator_client.go

Resolves Issue #504 
Added switch case for auth type 'oidc'.

Add support for oidc auth type

---

cmd/vault-env/main.go
cmd/vault-secrets-webhook/main.go
docs/mutating-webhook/consul-template.md

vault-env: added option to pass VAULT env vars to main process

---

docs/mutating-webhook/consul-template.md

VAULT_TLS_SECRET instead of VAULT_TLS_CONFIGMAP

fix mistake

---

hack/acceptance-test.sh
operator/deploy/cr-etcd-ha.yaml
operator/pkg/controller/vault/vault_controller.go

operator: sync only necessary CA keys and don't sync into source namespace

---

docs/mutating-webhook/README.md

webhook: remove limitation from doc

webhook: remove limitation from doc

---

operator/pkg/controller/vault/vault_controller.go

Add fqdn to generated cert hosts

---

hack/acceptance-test.sh
operator/deploy/cr-priority.yaml
operator/deploy/priorityclass.yaml

- example using PriorityClass via vaultPodSpec and vaultConfigurerPodSpec
- use cr-priority.yaml in acceptance test in case of single node cluster
fixes: #533

Example with vaultPodSpec and vaultConfigurerPodSpec

---

operator/pkg/controller/vault/vault_controller.go

Fetch the Vault instance again before update to minimize the possibility of updating a stale object. 
Should fix error seen in #364

Fix stale Vault CR updates

---

Dockerfile
cmd/bank-vaults/configure.go
cmd/template/main.go
go.mod
internal/configuration/template.go
operator/cmd/manager/main.go
operator/deploy/cr-mysql-ha.yaml
operator/deploy/cr.yaml
operator/deploy/operator.yaml
operator/pkg/controller/vault/vault_controller.go

Complete MySQL HA example and Vault config templating support

---

cmd/vault-secrets-webhook/configmap.go
cmd/vault-secrets-webhook/main.go
cmd/vault-secrets-webhook/secret.go

A connection was made to Vault in case of ConfigMaps and Secrets even if they didn't contain any Vault sourced fields. This PR:
- improves mutation performance and reduces overall overhead
- closes the Vault client after the actual mutation happened (there was a connection/memory leak)
- adds small unification fixes

webhook: lazy connection to vault in case of configmaps and secrets

---

cmd/vault-secrets-webhook/main.go

This change introduces a way to inject another the vault_path as an environment variable.

Use VAULT_PATH if specified as an environment variable

---

docs/mutating-webhook/README.md

Howto install vault and webhook two different k8s clusters.
fixes: #544

Extending readme

---

cmd/vault-secrets-webhook/main.go
deploy/test-deployment.yaml
docs/mutating-webhook/README.md
operator/pkg/controller/vault/vault_controller.go

- webhook: better defaults for role and path
- operator: put back vault name to the certificate
- webhook: reduce the number of mandatory annotations

small webhook improvements

---

pkg/tls/tls.go

Instead of just allowing one wild card host entry, add support for multiple wild card hosts and use the first as commonName.
Fixes #561

[TLS] Add support for multiple wildcard hosts

---

cmd/vault-secrets-webhook/main.go

Allow collect webhook metrics for analytics.

Add vault-secrets-webhook basic metrics

---

.circleci/config.yml
charts/README.md

Build and release charts from this git repository to the Banzai Helm repository.

helm: build charts with circle

---

charts/vault-secrets-webhook/templates/apiservice-webhook.yaml
cmd/vault-secrets-webhook/main.go
docs/mutating-webhook/README.md

Add support for dry-run with the Webhook controller.
Fixes #575 
It also adds a default false value to verbose logging.

Add support for dry-run with the webhook controller

---

hack/acceptance-test.sh

acceptance-test: kurun run was moved to a subcommand

acceptance-test: kurun run was moved to a subcommand

---

hack/acceptance-test.sh

Fixes: #590 
So we covert the current chart version.

use the webhook chart directly for acceptance-test

---

charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/templates/prometheus-monitorservice.yaml
charts/vault-secrets-webhook/values.yaml
docs/monitoring/README.md

and we have metrics in prom;
https://take.ms/TjvS5

feat: add servicemonitor config to the webhook chart

---

cmd/vault-secrets-webhook/main.go

Fixes: #593 
The Dashboard is not ready yet! ;)

webhook: expose mutation metrics in prometheus format

---

charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/templates/apiservice-webhook.yaml
charts/vault-secrets-webhook/values.yaml

YAML indentation issue found when adding a custom one.

fix: yaml indentation

---

cmd/vault-secrets-webhook/registry/registry.go

**Description**
Add a little bit of logging to the imagePullSecret secret selection and remove the TODO about pulling imagePullSecrets from ServiceAccounts (see explanation in the comments to this PR).

[webhook] Small logging / comment additions

---

cmd/vault-env/main.go

| Bug fix?        | yes and no (this is rather a not existing feature)
| Related tickets | fixes #620 
Calling Vault only once per path.
To reduce API calls and support dynamic credentials (implicitly).

vault-env: cache secrets to reduce calls and support dynamic credentials

---

cmd/examples/main.go
cmd/vault-env/main.go
cmd/vault-secrets-webhook/secret.go
pkg/auth/tokenstore.go
pkg/db/database.go

| Bug fix?        |no|
| New feature?    |no|
| API breaks?     |no|
| Deprecations?   |yes|
This PR removes the deprecated Vault client method and replaces with the new RawClient one.

Use RawClient method instead of the deprecated Vault method

---

cmd/vault-secrets-webhook/main.go

| Related tickets | fixes https://github.com/banzaicloud/bank-vaults/issues/619
Optional envFrom constructs shouldn't stop the mutation flow when the given reference is missing.

webhook: don't bail out on missing optional env sources

---

charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/values.yaml

Update to 0.5.1
Closes #629, #627

feat: update vault-secrets-webhook helm chart to 0.5.1

---

charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/templates/webhook-pdb.yaml
charts/vault-secrets-webhook/values.yaml

feat: add pdb to vault-secrets-webhook

---

pkg/sdk/go.mod
pkg/sdk/go.sum

| Bug fix?        | yes?
Kubernetes API dependency seemed invalid

Tidy SDK dependencies

---

charts/vault-operator/templates/crd.yaml
charts/vault-operator/templates/deployment.yaml
charts/vault-operator/templates/role.yaml
charts/vault-operator/templates/rolebinding.yaml
charts/vault-operator/templates/sa.yaml
charts/vault-operator/templates/service.yaml
charts/vault-secrets-webhook/templates/prometheus-monitorservice.yaml
charts/vault-secrets-webhook/templates/webhook-deployment.yaml
charts/vault-secrets-webhook/templates/webhook-pdb.yaml
charts/vault-secrets-webhook/templates/webhook-service.yaml
charts/vault/templates/configmap.yaml
charts/vault/templates/ingress.yaml
charts/vault/templates/prometheus-monitorservice.yaml
charts/vault/templates/role.yaml
charts/vault/templates/rolebinding.yaml
charts/vault/templates/secret.yaml
charts/vault/templates/service.yaml
charts/vault/templates/serviceaccount.yaml
charts/vault/templates/statefulset.yaml
deploy/test-deployment.yaml
docs/mutating-webhook/README.md
docs/mutating-webhook/consul-template.md
docs/mutating-webhook/howto-ct-prom.md
operator/deploy/config-jwt-groups.yaml
operator/deploy/config.yaml
operator/deploy/secret.yaml

This changes to the recommended k8s labels as documented in #631. This PR was based upon #632 as to not cause conflicts. I will rebase this PR once that is merged in, or vice versa depending on what you ask for.
Closes #631

feat: use recommended k8s labels

---

docs/go-library/README.md

docs: update sdk docs for the new module

---

operator/deploy/cr-prometheus.yaml
operator/pkg/controller/vault/vault_controller.go

| Related tickets | fixes #635 
Fixes #635 
To have a fully automated working example with Prometheus Operator and Vault Agent.

Prometheus ServiceMonitor token automation example

---

charts/vault-secrets-webhook/values.yaml

Fix typo in vault-secrets-webhook values yaml

Fix typo in vault-secrets-webhook values yaml

---

.circleci/config.yml
Dockerfile
Dockerfile.operator
Dockerfile.vault-env
Dockerfile.webhook
Makefile
go.mod
go.sum

| Related tickets | fixes #646 

ci: add GOPROXY

---

pkg/sdk/vault/operator_client.go

| Related tickets | completes fix to #503
Fixes the error below when adding a config with the `rotate: true`
```
error configuring vault: error configuring secret engines for vault: error rotating credentials for 'database/config/xxx' config in vault: error rotating credentials for 'database/config/xxx' config in vault: Error making API request.
URL: PUT http://vault:8200/v1/database/rotate-root/xxx
Code: 500. Errors:
* 1 error occurred:
* failed to find entry for connection with name: \"xxx\"
```
The original fix to #503 worked fine when adding the rotate key to an existing
config, but if the config didn't exist in vault …

fix: Config not added with rotate: true

---

cmd/vault-secrets-webhook/registry/registry.go

Fix format of imagePullSecret log message

---

pkg/sdk/vault/client.go

This PR enables setting a Vault token manually on the client.
Only disk or env var based support was offered until now for doing this.

client: add the ability to provider a Vault token

---

cmd/vault-secrets-webhook/main.go

This PR adds an annotation "vault.security.banzaicloud.io/vault-configfile-path" to indicate where to mount the shared volume (ct-secrets) in the main container. With this annotation it is possible to place the generated config file at the desired location in the main container and not only in /vault/secrets
To be able to write the configuration file generated by consul-template in the right directory (ex: /etc/nginx/nginx/nginx.conf for nginx) and not only in /vaut/secrets

Add new annotation to change the config file path in the container

---

docs/mutating-webhook/monitoring.md
hack/prometheus.yaml

A complete guide on how to monitor the webhook with Prometheus and exercise the Grafana dashboard for slok/kubewebhook.

webhook: add monitoring guide with example Grafana dashboard

---

charts/vault-secrets-webhook/README.md

| Related tickets | fixes #672
I have updated the documentation to include the challenges we have solved in issue #672 
The documentation was thin and I spent alot of time googling.

Added more information about the Vault Webhooks

---

docs/unseal-keys/README.md

In trying to decode my encoded value I noticed the flag was wrong.
$ man base64
```
base64(1)                 BSD General Commands Manual                base64(1)
NAME
base64 -- Encode and decode using Base64 representation
SYNOPSIS
base64 [-h | -D] [-b count] [-i input_file] [-o output_file]
DESCRIPTION
base64 encodes and decodes Base64 data, as specified in RFC 4648. With no options, base64 reads raw data from stdin and writes encoded data as a continuous block to stdout.
OPTIONS
The following options are available:
-b count
--break=count        Insert line breaks every count characters. Default is 0, which generates an unbroken stream.
-D
--decode             Decode incoming Base64 stream into binary data.
-h
--help               Print usage summary and exit.
-i input_file …
```

Updates base64 decode flag

---

vault-config.yml

GCP secrets engine configuration example

add gcp secret engine example to vault-config.yml

---

cmd/bank-vaults/util.go
operator/deploy/cr-vault-kv-unseal.yaml
operator/deploy/cr.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go
pkg/kv/vault/vault.go
pkg/sdk/vault/client.go

| Related tickets | #678 Vault unseal conf
This PR completes the work in #678 with the operator implementation of it. Also contains some fixes.

vault-unsealing: add operator part and some fixes

---

deploy/test-deployment-seccontext.yaml
hack/acceptance-test.sh

securityContext example

---

deploy/test-configmap.yaml
hack/acceptance-test.sh

Fixes: https://github.com/banzaicloud/bank-vaults/issues/610

acceptance-test: webhook should reject mutation failures

---

charts/vault-operator/Chart.yaml
charts/vault-operator/templates/role.yaml
charts/vault-operator/values.yaml
operator/deploy/operator-rbac.yaml

| Related tickets | fixes (partially) #705 
Setting finalizers on deployments has to be enabled for creating the `vault-monitor-service` by the operator (its owner is the vault-operator deployment itself.

operator: fix rbac for openshift

---

charts/vault-operator/README.md
charts/vault/README.md

Minor documentation fix, added "banzaicloud-stable/" prefix to chart docs.

---

deploy/test-external-secrets-watch-deployment.yaml
deploy/test-external-secrets-watch-secrets.yaml
docs/external-secrets/README.md
go.mod
go.sum
hack/acceptance-test.sh
operator/deploy/cr-customports.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

backport of #719 to 0.5.x

---

charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/templates/apiservice-webhook.yaml
charts/vault-secrets-webhook/values.yaml

SHADOW PR: Add option to use static certicates for vault-secrets-webhook helmchart.

---

.circleci/config.yml
.github/workflows/ci.yml
hack/acceptance-test.sh

As a secondary/backup CI solution I would like to enable GitHub Actions as well because we recently had many troubles with CircleCI.

Enable GitHub actions

---

charts/vault/Chart.yaml
charts/vault/README.md
charts/vault/templates/ingress.yaml
charts/vault/values.yaml

add path handling for ingress in vault chart

---

Makefile
README.md
docs/contributing/README.md

dev: description how to run the webhook and the operator locally for development

---

operator/cmd/manager/main.go

operator: remove redundant configuration reading

operator: remove redundant configuration reading

---

charts/vault-secrets-webhook/README.md

We doesn't want to tell users specify password in annotations.

[webhook] Fix readme example usage

---

cmd/vault-secrets-webhook/main.go

webhook: allow vault_role to be specified globally

---

cmd/vault-env/main.go
deploy/test-deployment.yaml
deploy/vault-pipeline-feature.yaml
docs/mutating-webhook/README.md
internal/configuration/template.go

| Related tickets | fixes partially #655 
Add support for templating secrets with Go templates for Pods (currently).
ConfigMap and Secret templating will be implemented in a future PR.

vault-env: implement templating of data sourced from vault

---

charts/vault-operator/Chart.yaml
charts/vault-operator/values.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/values.yaml
charts/vault/Chart.yaml
charts/vault/README.md
charts/vault/values.yaml

Use 0.6.0 in charts.
Fixes: https://github.com/banzaicloud/bank-vaults/pull/741 :)

charts: update app versions after release

---

operator/pkg/controller/vault/vault_controller.go

| Related tickets | fixes https://github.com/banzaicloud/bank-vaults/issues/739

operator: accept vault-config.yml and .yaml as well

---

charts/vault-operator/Chart.yaml
charts/vault-operator/values.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/values.yaml
charts/vault/Chart.yaml
charts/vault/values.yaml

chart: bump versions

---

go.mod
go.sum
operator/deploy/cr-etcd-ha.yaml
operator/deploy/etcd-operator.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go

Also added a note on etcd 3.4 version line.

operator: etcd upgrade to 3.3.17

---

.gitignore
charts/vault-operator/Chart.yaml
charts/vault-operator/requirements.yaml
charts/vault-operator/values.yaml

operator: update etcd in chart as well

---

.gitignore
certs/README.md
certs/config.json
certs/csr.json
certs/server.json
charts/vault/Chart.yaml
charts/vault/README.md
charts/vault/templates/secret.yaml
charts/vault/templates/statefulset.yaml
charts/vault/values.yaml

add custom certificate documentation and support for Vault chart

---

ADOPTERS.md

Signed-off-by: Murphy, Kealan <kealan.murphy@aspect.com>
Adding Aspect to the list of Adopters 
Banzai and bank-vaults has been great to work with and the engineers have been a great help along the way. As both an adopter and contributor happy to put our name on the list.

Adding Aspect to the Adopters list

---

ADOPTERS.md

Update adopters list

---

operator/deploy/cr.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

| Related tickets | fixes #767 
Istio needs some special port name prefixes, which Bank-Vaults didn't respect. Until now.
https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/

operator: istio compatibility flag added with port naming support

---

charts/vault/Chart.yaml
charts/vault/templates/statefulset.yaml
charts/vault/values.yaml

[Chart][Vault] Add default requests / container

---

operator/pkg/controller/vault/vault_controller.go

operator: restart configurer as well in case of tls cert changes

---

.circleci/config.yml
.github/workflows/ci.yml
charts/vault/Chart.yaml
charts/vault/values.yaml
hack/acceptance-test.sh

Fixin Vault chart resources + add acceptance test to the pure chart.
There was an extra `resources` block under the resources block of the Vault chart.

chart/vault: fix resources + acceptance test

---

deploy/test-deploy-ct.yaml
operator/deploy/cr.yaml

A proper PKI example with the webhook consul-template feature.
To have it documented.

add consul-template with PKI example

---

.circleci/config.yml
.github/workflows/ci.yml
deploy/test-deployment-seccontext.yaml
deploy/test-deployment.yaml
hack/acceptance-test.sh

acceptance-test/github: use kind, it is installed by default

---

cmd/vault-env/main.go

| Related tickets | fixes #794 
The version was missing from the secret cache key.

vault-env: add version to secret cache key

---

charts/vault-operator/Chart.yaml
charts/vault-operator/templates/deployment.yaml

fix nodeSelector conditionCheck in the deployment
in deployment the condition being checked to populate nodeSelector is for tolerations, may be a typo.

fix nodeSelector conditionCheck in vault-operator chart deployment file

---

charts/vault-operator/Chart.yaml
charts/vault-operator/requirements.yaml
charts/vault-operator/templates/deployment.yaml
charts/vault-operator/values.yaml
hack/acceptance-test.sh

- update etcd operator chart version
- fix etcd operator config
- remove unconfigurable probe value
- involve vault operator chart under acceptance testing

operator acceptance test + etcd chart update/fix

---

cmd/vault-secrets-webhook/main.go

| Related tickets | fixes #805 
This PR fixes the missing configmap/secret in case of valueFrom/envFrom.
Despite the secret/configmap is missing, the pods will be mutated.
If the missing secret/configmap is created after the deployment, restarting the pod will fix the crashloopback state.

Fix error handling in case of missing secret/configmap 

---

charts/vault/README.md
operator/deploy/openshift-vault-scc.yaml

| Related tickets | fixes #706 
Add Vault SCC example for IPC_LOCK

add openshift scc example

---

charts/vault/README.md
operator/deploy/openshift-vault-scc.yaml

| Related tickets | fixes #X
Update description of scc.

Update description of scc

---

cmd/vault-secrets-webhook/main.go

| Related tickets | fixes #804 

webhook: ownerreferences should be always queried

---

docs/mutating-webhook/webhooks-comparision.md

Improve webhook comparison

---

operator/deploy/cr-raft.yaml

| Bug fix?        |no
This PR contains an example of using RAFT backend with a local kind cluster.

Example raft directory permission setup

---

README.md

community enhancements

---

go.mod
go.sum

Fix dependencies

---

docs/unseal-keys/README.md

| Related tickets | fixes #839 

docs: add Google Cloud unseal key description

---

charts/vault/Chart.yaml
charts/vault/templates/statefulset.yaml
charts/vault/values.yaml
cmd/bank-vaults/configure.go
cmd/template/main.go
cmd/vault-env/main.go
internal/configuration/template.go

We are removing the dependency on Dockerize in the Vault chart, so we can control better what we are distributing.

templates: remove the dependency on dockerize

---

deploy/test-deploy-va.yaml
docs/mutating-webhook/vault-agent-templating.md

| Related tickets | #823 
Fixing the agent config ConfigMaps in the examples.

webhook: fix agent config examples

---

operator/deploy/cr-raft.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

- minimize fsfreeze's resource needs
- rename fsfreeze container
- move asOwner to the Vault type as AsOwnerReference
- fix image in cr-raft.yaml
- make velero fsfreeze image configurable

operator: velero enhancements

---

hack/acceptance-test.sh
operator/deploy/cr-raft.yaml

| Related tickets | #820
Testing Raft example in CI.

raft: cover in acceptance-test

---

docs/cloud-permissions/README.md

Update to the readme on how to set up AWS for S3-based unseal using KMS.
The original readme does not detail how.
```
Gyorgy Nadaban  1 day ago
So I spent some time yesterday trying to make this work with S3/KMS unseal key storage and cert-manager signed custom external ingress.
Now I have an operator and vault deployment, but it fails the preflight checks for S3 and KMS. I realize that for an EKS cluster to use roles that allow the Vault operator to access S3 and KMS needs IAM auth in the cluster.
I scoured the net for details but got lost in the weeds about what exactly is required.
For example, …
```

Update AWS cloud permission setup in readme

---

docs/unseal-keys/README.md

**Please squash before merge.**

[docs] add unseal-key and root-token migration docs

---

charts/vault/Chart.yaml
charts/vault/templates/serviceaccount.yaml
charts/vault/templates/statefulset.yaml
charts/vault/values.yaml

- Adding ServiceAccount annotations, so EKS annotations can be specified: https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html
- Fix token permissions: https://github.com/kubernetes-sigs/external-dns/pull/1185/files
So EKS IAM binding can be used with the Vault chart.

chart: add eks iam sa capability

---

docs/cloud-permissions/README.md

docs: more detailed eks iam sa docs

---

charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-operator/values.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/values.yaml
charts/vault/Chart.yaml
charts/vault/values.yaml

Using the 0.9.0 release in all charts.

bump chart and app versions

---

docs/annotations-and-labels/README.md
docs/backup/README.md
docs/cli-tool/README.md
docs/cloud-permissions/README.md
docs/contributing/README.md
docs/external-secrets/README.md
docs/go-library/README.md
docs/installing/README.md
docs/monitoring/README.md
docs/mutating-webhook/README.md
docs/operator/README.md
docs/tls/README.md
docs/unseal-keys/README.md

It seems that search engines update their caches somewhat slower than expected.

Add readme.mds to direct visitors to the doc site

---

operator/deploy/cr-azure.yaml

Azure Storage is non-HA from Vault point of view.

azure: fix size to 1 in non-HA example

---

.github/workflows/ci.yml

Add license check to gh actions

---

charts/vault-operator/Chart.yaml

| Related tickets | fixes #907 
Repackaging the chart with Helm3, but keep the compatibility with Helm 2.

bump-operator-chart-version, repackage with helm3

---

.circleci/config.yml

Publish helm chart without linting

---

.circleci/config.yml

Update helm dependencies

---

.circleci/config.yml

Somehow `type` field of Chart.yaml disappeared during `helm push`...

Replace helm push with curl

---

charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/templates/webhook-psp.yaml

| Related tickets | fixes #919
Fix PSP apiversion.

[Webhook/Chart] Fix PSP apiversion in case of k8s 1.16

---

charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-operator/values.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/values.yaml
charts/vault/Chart.yaml
charts/vault/README.md
charts/vault/values.yaml

Bumping chart and image versions to 1.0.0
To prepare for release 1.0.0.

prepare for release 1.0.0

---

operator/deploy/cr-aws.yaml
operator/deploy/cr-etcd-ha-aws.yaml
operator/deploy/cr-etcd-ha-file.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

| Related tickets | fixes #923
Checks in both storage and ha_storage stanzas if an etcd cluster should be deployed. Also added some sample CR files for etcd+aws and etcd+file.
Etcd cluster was not deployed if conf declared in ha_storage stanza.

support etcd when declared in ha_storage stanza

---

charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-operator/values.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/values.yaml
charts/vault/Chart.yaml
charts/vault/values.yaml

prepare 1.0.1

---

go.mod
go.sum

| Related tickets | fixes #939 , https://github.com/banzaicloud/bank-vaults/issues/548
Upstream issue: https://github.com/gomodules/jsonpatch/pull/22#issuecomment-554732839

webhook: upgrade jsonpatch to fix index out of range

---

operator/deploy/cr-aws.yaml

update aws example

---

charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-operator/requirements.yaml
charts/vault-operator/values.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/values.yaml
charts/vault/Chart.yaml
charts/vault/values.yaml

prepare 1.1.0

---

operator/pkg/controller/vault/vault_controller.go

Use Data instead of StringData when accessing the previous CA, add log message if the CA has to be rotated
Bug Fix for CA persistence
The CA was being regenerated because we were accessing it via a WriteOnly map

operator/tls: Use Data instead of StringData when accessing the previous CA, add log message if the CA has to be rotated

---

.circleci/config.yml
.github/workflows/ci.yml

Some versions like Go were out of sync.

fix versions in ci

---

.github/workflows/ci.yml
charts/testing.yaml

add chart linter github action

---

deploy/test-cronjob.yaml

Add CronJob example to inject env vars with the webhook.
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

add cronjob injection example

---

cmd/vault-env/main.go

Process all signals and send them to the child process.
Only the first signal was processed, which was not enough.

vault-env: process all signals

---

go.mod
internal/configuration/template.go
operator/deploy/cr-awskms.yaml
operator/deploy/cr-file.yaml
operator/deploy/cr-gcpkms.yaml

Signed-off-by: patoarvizu <patoarvizu@gmail.com>
| Related tickets | fixes #945 
Extending the templating functionality by adding custom functions to enable getting strings from other sources like an AWS KMS-encrypted string or a file path.
The only function available for templating that comes close to it is `env` which has limited usefulness for the use case.
- Update documentation
- Add examples
- Add/update tests
- Maybe add other sources (e.g. PGP, Google Cloud KMS, a REST endpoint, another Vault, etc.)

Add custom functions for awskms and file

---

charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-operator/values.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/values.yaml
charts/vault/Chart.yaml
charts/vault/values.yaml

prepare for version 1.2.0

---

charts/vault-secrets-webhook/README.md

| Related tickets | fixes #967 
Update webhook chart readme.

[Chart/Webhook] Update webhook chart readme

---

.circleci/config.yml

Adding snyk job to circle

---

examples/backup/backup.yaml
examples/backup/schedule.yaml
examples/istio/app.yaml
examples/istio/cr-istio.yaml
examples/istio/rbac.yaml
examples/tls/config.json
examples/tls/csr.json
examples/tls/server.json

Re-adds example yaml and json files to the main repo

---

.circleci/config.yml

Initiate snyk check only on the master branch.

Snyk check on master

---

pkg/sdk/tls/tls.go
pkg/sdk/tls/tls_client.go
pkg/sdk/tls/tls_integration_test.go
pkg/sdk/tls/tls_peer.go

Cert serial number generation unified, broken API fixed with shadowed type.

some sdk/pkg/tls fixes

---

charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-operator/values.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/values.yaml
charts/vault/Chart.yaml
charts/vault/README.md
charts/vault/values.yaml

prepare 1.3.0: bump chart and image versions

---

ADOPTERS.md

Add Pulselive to the production adopters.
@bonifaido asked me to.
Bank Vaults makes our lives easier :grin:

Add Pulselive to ADOPTERS.md

---

.circleci/config.yml

Using `large` machine instance during acceptance-test in Circle.
The tests often fail on the `medium` type.

acceptance-test: resource_class: large

---

go.mod
go.sum
pkg/sdk/go.mod
pkg/sdk/go.sum
pkg/sdk/vault/client.go

| Related tickets | fixes  #1007
Fixes the sdk logger not being available on all code paths.
It also upgrades logrus dependency

Fix sdk logging

---

charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-operator/values.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/values.yaml
charts/vault/Chart.yaml

prepare 1.3.1

---

charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-operator/values.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/values.yaml
charts/vault/Chart.yaml
charts/vault/README.md
charts/vault/values.yaml

prepare 1.3.2

---

.circleci/config.yml
.github/workflows/ci.yml
cmd/examples/main.go
hack/acceptance-test.sh
hack/kind.yaml
hack/oidc-pod.yaml
internal/configuration/template.go
operator/deploy/cr-oidc.yaml
operator/deploy/cr-priority.yaml
pkg/sdk/vault/client.go

This PR adds support for using projected ServiceAccount tokens with the Bank-Vaults Vault client wrapper library.
It also adds examples for using the Kubernetes ServiceAccount Discovery feature based on OIDC with Vault.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery

Kubernetes OIDC and projected SA support

---

.circleci/config.yml
Dockerfile
Dockerfile.operator
Dockerfile.vault-env
Dockerfile.webhook
hack/acceptance-test.sh
operator/deploy/cr-etcd-ha.yaml
operator/pkg/controller/vault/vault_controller.go
pkg/sdk/vault/client.go

- improved cluster status reporting in the CR status.conditions field.
- reduce noise in acceptance test with the new status based waits

simplify test with conditional waits

---

charts/vault/Chart.yaml
charts/vault/templates/tests/test-vault-status.yaml

Fix error an in helm test
When vault is using https the "helm test" fails with "Client sent an HTTP request to an HTTPS server."
Added VAULT_SKIP_VERIFY=true as we are not testing if the cert is valid (e.g. self-signed).

fix helm test for https

---

charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-operator/templates/_helpers.tpl
charts/vault-operator/templates/deployment.yaml
charts/vault-operator/values.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/templates/_helpers.tpl
charts/vault-secrets-webhook/templates/webhook-deployment.yaml
charts/vault-secrets-webhook/values.yaml
charts/vault/Chart.yaml
charts/vault/README.md
charts/vault/templates/_helpers.tpl
charts/vault/templates/statefulset.yaml
charts/vault/values.yaml

Prepare new release and help writing less yaml boilerplate when upgrading to a new version.

Prepare 1.3.3 + image version templating

---

charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/templates/webhook-deployment.yaml
cmd/vault-env/main.go
cmd/vault-secrets-webhook/main.go

Signed-off-by: Andrii Nasinnyk <anasinnyk@macpaw.com>
It's a possibility to change the log level
We have some noisy logs message, and those messages can't parse by fluentd and it looks ugly for us.

Possibility to change the log level

---

charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-operator/templates/_helpers.tpl
charts/vault-operator/templates/deployment.yaml
charts/vault-operator/values.yaml

Add support of image pull secrets
I need to proxify the image
Would be nice to support imagePullSecrets in Vault CRD :-)

[charts/vault-operator] Add image image pull secrets

---

operator/deploy/multi-dc/multi-dc-raft.sh

| Related tickets | fixes #1044 
Remove the custom image setting from the install script.
The tag has been already merged to master and got released a while ago, and the custom tag was deleted.

remove outdated image setting from script

---

cmd/vault-secrets-webhook/pod.go

Just pass log_level to mutated container 
We want to remove unnecessary logs from end container

Pass log_level to mutated container

---

deploy/test-deploy-va.yaml

| Bug fix?        | sort of?  more like "bug-unfix"
| Related tickets | https://github.com/hashicorp/vault/issues/7889
Removal of extraneous configuration lines in config.hcl
The bug that made the example require this entry has been patched for a while.  
Submitting this PR to remove the extraneous config lines.

Remove unnecessary config.hcl entry in example deployment

---

charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/values.yaml

Fixing the case of the VAULT_IMAGE env var.
It was ignored.

webhook: fix VAULT_IMAGE case

---

operator/deploy/multi-dc/cr-primary.yaml
operator/deploy/multi-dc/cr-secondary.yaml
operator/deploy/multi-dc/cr-tertiary.yaml
operator/deploy/multi-dc/multi-dc-raft.sh
operator/pkg/controller/vault/vault_controller.go

Fixes for the multi-DC raft setup script and related operator code.
The current Vault version (1.4.3) wasn't working with the operator correctly.

Multi-DC Raft fixes

---

operator/deploy/multi-dc/multi-dc-raft.sh
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go
pkg/sdk/tls/tls.go

Waiting for LB to get a stable address before generating the TLS certificate. Some code renaming a for better readability. More effective TLS parsing.
To make multi-DC RAFT work better.

Another set of Multi DC raft improvements

---

charts/vault-operator/Chart.yaml
charts/vault-operator/templates/_helpers.tpl
charts/vault-operator/templates/deployment.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/templates/_helpers.tpl
charts/vault-secrets-webhook/templates/webhook-deployment.yaml
charts/vault/Chart.yaml
charts/vault/templates/_helpers.tpl
charts/vault/templates/statefulset.yaml

| Related tickets | fixes #1065 
Namespacing chart templates.

charts: fix template globalness

---

.golangci.yml
charts/vault/Chart.yaml
charts/vault/templates/statefulset.yaml
cmd/bank-vaults/configure.go
cmd/bank-vaults/init.go
cmd/bank-vaults/main.go
cmd/bank-vaults/metrics.go
cmd/bank-vaults/unseal.go
cmd/examples/main.go
cmd/vault-secrets-webhook/main.go
internal/injector/inejctor_test.go
pkg/kv/multi/multi.go
pkg/sdk/tls/tls_integration_test.go
pkg/sdk/vault/client.go
pkg/sdk/vault/operator_client.go

Enabling the `errcheck` sub-linter and fix missing error handlings.
Otherwise, some issues can swallowed.

check errors correctly

---

pkg/sdk/vault/operator_client.go
vault-config.yml

Support configuring the [userpass](https://www.vaultproject.io/docs/auth/userpass.html) auth method in Vault.

configurer: implement userpass auth method

---

charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault/Chart.yaml
charts/vault/README.md

| Related tickets | fixes #1069 

prepare 1.4.0 release

---

.circleci/config.yml

upgrade:
- minikube version
- kubernetes version in minikube
- add more cpu and memory to minikube

upgrade minikube cpu/memory

---

operator/pkg/controller/vault/vault_controller.go

| Related tickets | fixes #1072
Minor fix that adds the hostnames of the individual services to the server certificate of the Vault cluster, when the cluster has more than one nodes
From #1072:
> In canary and production deployments we are setting up clusters with more than one nodes and a HA backend. However, occasionally, we need to hit individual nodes to see if they are online, if they booted up, etc and it's annoying that the server certificate does not include the hostname of the individual service that points to a node.
-

Add per instance svc hosts to Vault cert SANs

---

cmd/vault-secrets-webhook/common.go
cmd/vault-secrets-webhook/secret.go

| Related tickets | fixes #1083 
Fix removing of `>>` before `>>vault:` so communicate the request method correctly.

webhook: fix injection request method for non-pods

---

.github/workflows/docker.yml

| Related tickets | #1086, #1076 
Publish container images to the new Github Container Registry.

ci: github container registry build

---

charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault/Chart.yaml
charts/vault/README.md

prepare 1.4.2

---

cmd/vault-env/main.go
deploy/test-deployment-gcp.yaml
pkg/sdk/vault/client.go

The current code already supported basically all kind of JWT based Vault authentication mechanisms, it was just not realized and the naming didn't support that well (but it worked). This is now changed and documented. So from now on JWT/GCP auth works as well in vault-env, documented with an example as well.

vault-env: support JWT/OIDC/GCP auth

---

.github/workflows/docker.yml
Dockerfile
Dockerfile.operator
Dockerfile.vault-env
Dockerfile.webhook

| Related tickets | fixes #1076 
Docker:
- Update go to 1.15
- Update alpine to 3.12
- Multi-platform Docker images for `armv7`, `arm64`, and `amd64` in GitHub Container Registry.

ci: build multi-platform images

---

operator/deploy/multi-dc/test/multi-dc-raft.sh

test: narrow CIDR range to prevent .0 addresses

---

.licensei.toml
operator/deploy/multi-dc/aws/cr-primary.yaml
operator/deploy/multi-dc/test/cr-primary.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

| Related tickets | https://github.com/banzaicloud/bank-vaults/pull/1105

operator: fix raftLeaderAddress with self option

---

operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

operator: extract raft detection logic to IsRaftBootstrapFollower

---

.github/workflows/ci.yml
Makefile

| Related tickets | #1076 
Update to Go 1.15, the Docker images were updated in a previous PR already.

ci: go 1.15

---

operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

| Related tickets | #1076 
Replace deprecated Docker images deployed by the operator.

operator: update images to support arm64

---

charts/README.md
charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault/Chart.yaml
charts/vault/README.md

Chart preparation for the 1.5.0 release.

prepare 1.5.0

---

charts/vault-operator/values.yaml

| New feature?    | no|no
| API breaks?     | no|no
| Deprecations?   | no|no
Fix typo in values.yaml file.
Enable chart installation with PSP manifest, as documented in README.md and stated in templates/

Update values.yaml: fix typo

---

operator/pkg/controller/vault/vault_controller.go

In resource-constrained environments there it is better not to deploy the configured if not absolutely necessary.

operator: deploy configurer only if there is any externalConfig present

---

README.md

and mentions commercial support in Readme.md

Adds links to the blog and newsletter

---

.circleci/config.yml
.licensei.toml
README.md
internal/injector/injector.go
pkg/kv/alibabakms/kms.go
pkg/kv/awskms/awskms.go

| Related tickets | #988 
Remove Snyk code analysis. Fix some code issues scanned by CodeQL.
Since GitHub received an integrated code-scanner (CodeQL) we decided to use that.

Remove Snyk and fix CodeQL issues

---

cmd/vault-secrets-webhook/common.go
cmd/vault-secrets-webhook/configmap.go
cmd/vault-secrets-webhook/main.go
cmd/vault-secrets-webhook/object.go
cmd/vault-secrets-webhook/secret.go
deploy/test-configmap.yaml
deploy/test-secret.yaml
hack/acceptance-test.sh

| Related tickets | fixes #1001 
https://github.com/banzaicloud/bank-vaults/issues/1001#issuecomment-707641069
https://github.com/banzaicloud/bank-vaults/issues/1001#issuecomment-707641069

Possibility to define multiple inline-secrets for mutation

---

charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-secrets-webhook/Chart.yaml
charts/vault/Chart.yaml
charts/vault/README.md

prepare 1.7.0

---

ADOPTERS.md

Adds TripleLift to the list of adopters. :)
We love how powerful the operator and VSWH makes Vault on Kubernetes.

Add TripleLift to adopters

---

deploy/test-configmap.yaml
deploy/test-deployment-env-from.yaml
hack/acceptance-test.sh

| Related tickets | fixes #1143 

webhook: extend inline example

---

operator/deploy/cr-alibaba.yaml

| Related tickets | fixes #1175 
Adding an Alibaba working CR example for the operator.
Alibaba was missing from the samples.

operator: add Alibaba example

---

cmd/bank-vaults/common.go
cmd/bank-vaults/completion.go
cmd/bank-vaults/configure.go
cmd/bank-vaults/init.go
cmd/bank-vaults/main.go
cmd/bank-vaults/unseal.go

cli: add completion command

---

.github/workflows/ci.yml
Makefile
charts/vault-operator/Chart.yaml
charts/vault-operator/values.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault-secrets-webhook/values.yaml
charts/vault/Chart.yaml
charts/vault/values.yaml
cmd/vault-secrets-webhook/main.go
hack/Dockerfile.fluentd
hack/acceptance-test.sh
main-targets.mk
operator/deploy/multi-dc/aws/multi-dc-raft.sh
operator/deploy/multi-dc/test/multi-dc-raft.sh
operator/pkg/apis/vault/v1alpha1/vault_types.go

| Related tickets | #1089 
ghcr.io is the primary registry now.

move all images to ghcr.io in charts and operator

---

operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go
operator/pkg/controller/vault/vault_controller.go

| Related tickets | fixes #1195 

operator: apply sidecarEnvsConfig to fluentd and statsd, add resources for fluentd

---

charts/vault-secrets-webhook/values.yaml

webhook: comment on webhook role env variable

---

charts/README.md
charts/vault-operator/Chart.yaml
charts/vault-operator/README.md
charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/README.md
charts/vault/Chart.yaml
charts/vault/README.md

prepare 1.9.0

---

hack/prometheus.yaml
operator/deploy/cr-prometheus.yaml

| Related tickets | https://github.com/banzaicloud/bank-vaults-docs/pull/60

operator: prometheus fixes in example

---

operator/deploy/cr-prometheus.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

| Related tickets | fixes #1209 

operator: support for unauthenticated_metrics_access and deduplicating prometheus targets

---

charts/vault-operator/Chart.yaml

operator: fix stable chart repo location

---

operator/deploy/cr-hsm-nitrokey.yaml
operator/deploy/cr-hsm-softhsm.yaml
operator/deploy/cr-init-containers.yaml
operator/deploy/cr-k8s-startup-secret.yaml
operator/deploy/cr-nodeAffinity.yaml
operator/deploy/cr-priority.yaml
operator/deploy/cr-raft-ha-storage.yaml
operator/deploy/cr-raft.yaml
operator/deploy/cr.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/apis/vault/v1alpha1/zz_generated.deepcopy.go
operator/pkg/controller/vault/vault_controller.go

This PR adds support for all affinity-based configurations and deprecates the old (and a bit patchy) way of configuring affinity.

operator: support for all affinity configurations

---

internal/injector/injector.go
internal/injector/injector_test.go

| Related tickets | https://github.com/banzaicloud/bank-vaults/issues/1204

injector: differentiate "not found" from other errors

---

.github/dependabot.yml
Dockerfile
Dockerfile.operator
Dockerfile.vault-env
Dockerfile.webhook

- pin patch version in case of base images
- add dependabot config for docker

Add dependabot config for docker

---

.github/workflows/anchore-analysis.yml

docker: add anchore image scan action

---

charts/vault-operator/Chart.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault/Chart.yaml

charts: prepare for 1.10.1

---

README.md

Fixes capitalization of macOS in the readme - (macOs > macOS)

docs(readme): fix capitalization

---

charts/vault-secrets-webhook/README.md

Some clarifications and updates for the webhook installation by the Helm chart.

webhook: extend and specify documentation around namespaces

---

operator/pkg/controller/vault/vault_controller.go

| Related tickets | #972 
Update the Vault CR status in all cases when needed.
Some branches weren't covered here.

operator: fix Vault status updates

---

internal/vault/operator_client.go

| Related tickets | fixes #1247 

configurer: fix map types in auth config blocks

---

README.md

Delete obsolete reference to try pipeline

---

charts/vault-operator/Chart.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault/Chart.yaml

prepare for 1.11.2

---

cmd/vault-env/main.go

| Related tickets | fixes #1263
Extend the list of Vault client env vars.
Automatic detection of env var inclusion in case of `vault:login`.

vault-env: smarter env sanitization in case of vault:login

---

Makefile
examples/dev/microk8s/README.md
examples/dev/microk8s/dev.yaml
examples/dev/microk8s/pvc.yaml
examples/dev/microk8s/rbac.yaml

Just a bunch of utilities for developers:
1. A readme for developing on MicroK8s
2. Utilities for building images with buildah
3. Extra flags for docker build that prevent network errors when using OpenVPN
Development tooling is kinda important IMHO

Add example files for development on MicroK8s and buildah utils

---

charts/vault/Chart.yaml
charts/vault/templates/rolebinding.yaml
charts/vault/values.yaml

| Related tickets | fixes #1275

chart/vault: make ClusterRoleBinding optional

---

charts/vault-operator/Chart.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault/Chart.yaml

| Related tickets | fixes #1279 

prepare 1.13

---

charts/vault-operator/Chart.yaml
charts/vault-operator/crds/crd.yaml
operator/deploy/crd.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go

| Related tickets | fixes #1292
These region fields should be optional.
Those fields can be extracted from env variables as well for example on EKS.

operator: make aws region optional in the crd

---

charts/vault/Chart.yaml
charts/vault/templates/role.yaml

The only needed secret by default is `bank-vaults`.

chart/helm: stricter default rbac for secrets

---

operator/pkg/controller/vault/vault_controller.go

| Related tickets | fixes #1300 

operator: fix nodes null unmarshal issue

---

operator/pkg/controller/vault/vault_controller.go

operator: better code style

---

operator/pkg/apis/vault/v1alpha1/vault_types.go

operator/ingress: add default backend only if there are no rules defined

---

charts/vault-operator/Chart.yaml
charts/vault-operator/crds/crd.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault/Chart.yaml
hack/acceptance-test.sh
operator/deploy/crd.yaml
operator/deploy/multi-dc/aws/multi-dc-raft.sh
operator/deploy/multi-dc/test/multi-dc-raft.sh
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

| Related tickets | fixes #1304 

operator/ingress: v1

---

charts/vault-operator/Chart.yaml
charts/vault-operator/templates/role.yaml

| Related tickets | fixes #1307 
We migrated to v1 Ingress API but the RBAC scope wasn't updated properly to follow this.

operator: fix ingress rbac api group

---

pkg/kv/kv.go
pkg/kv/kv_test.go

| Related tickets | fixes #1311 

type fix for IsNotFoundError

---

Makefile
cmd/vault-secrets-webhook/main.go

webhook: fixes for running with kurun

---

cmd/vault-secrets-webhook/main.go
pkg/webhook/common.go
pkg/webhook/config.go
pkg/webhook/configmap.go
pkg/webhook/object.go
pkg/webhook/pod.go
pkg/webhook/pod_test.go
pkg/webhook/registry.go
pkg/webhook/registry_test.go
pkg/webhook/secret.go
pkg/webhook/webhook.go

| Related tickets | #1334 
This way the webhook code can be imported to another application.

webhook: extract the main code to pkg

---

pkg/webhook/configmap.go
pkg/webhook/object.go
pkg/webhook/pod.go
pkg/webhook/pod_test.go
pkg/webhook/secret.go
pkg/webhook/webhook.go

webhook: make mutate functions public

---

.circleci/config.yml
.github/workflows/ci.yml
cmd/vault-env/main.go

| Related tickets | fixes #1341 

vault-env: fix exit code detection

---

operator/pkg/controller/vault/vault_controller.go

After deleting the Vault instance the raw config stayed on the cluster, because of this missing ownerReference.﻿

operator: set owner reference on raw config

---

operator/pkg/apis/vault/v1alpha1/vault_types.go

Otherwise it won't let multiple replicas.

operator: fix config check for ha capable storages (ha_enabled=false) combined with ha_storage stanza

---

deploy/test-configmap.yaml
deploy/test-secret.yaml
pkg/webhook/config.go
pkg/webhook/configmap.go
pkg/webhook/configmap_test.go
pkg/webhook/secret.go

| Related tickets | fixes #1379 

webhook: remove the need for the inline-mutation annotation

---

charts/vault-operator/Chart.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault/Chart.yaml

release 1.13.1

---

charts/vault-operator/Chart.yaml
charts/vault-operator/templates/psp.yaml

Add missing capability to Helm psp template
| Related tickets | https://github.com/banzaicloud/bank-vaults/pull/1257
According to https://github.com/banzaicloud/bank-vaults/pull/1257 add missing capability to Helm psp template
Current Pod Security Policy  does not allow to deploys vault pods
```
Warning  FailedCreate  56s (x3 over 3m40s)    statefulset-controller  create Pod vault-ph-stage-1 in StatefulSet vault-ph-stage failed error: pods "vault-ph-stage-1" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[0].securityContext.capabilities.add: Invalid value: "SETFCAP": capability may not be added …
```

Add SETFCAP Capabilities to Helm psp template

---

operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

operator: change default configurer config to a Secret

---

charts/README.md

bad helm command

---

.github/workflows/docker.yml
.idea/bank-vaults.iml

build: fix ghcr auth

---

charts/vault-operator/README.md
charts/vault-secrets-webhook/README.md
charts/vault/README.md

Fixes bad formatting in markdown tables
The Readmes render fine in browsers etc, but looks weird when read in their raw form.,
I use this thing for linting markdown: https://github.com/DavidAnson/markdownlint
There are some other warnings, but I think tables are the only thing that makes sense fixing.

charts: Fix markdown tables in chart Readmes

---

pkg/webhook/pod.go

| Related tickets | fixes #1352 
Checking if pods are already annotated via the presence of the universal `vault-env` volume that we add in every scenario.

webhook: make pod mutation idempotent

---

charts/vault-operator/Chart.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault/Chart.yaml

prepare release of 1.14.1

---

charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/templates/webhook-rbac.yaml

| Related tickets | fixes #1456 
Remove the conditional checking on `serviceAccount.create` when creating ClusterRole and ClusterRoleBinding
- [x ] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x ] User guide and development docs updated (if needed)
- [x ] Related Helm chart(s) updated (if needed)

chart/webhook: Change template condition for RBAC 

---

.github/workflows/ci.yml

| Related tickets | https://github.com/banzaicloud/kurun/pull/26

[ci] update kurun to fix kubectl --limits deprecation

---

scripts/release-charts.sh

add chart releaser script

---

charts/vault-operator/Chart.yaml
charts/vault-operator/templates/deployment.yaml
charts/vault-operator/values.yaml

Ability to add Labels to bank-vault pod.
Useful for monitoring and alerting

Add pod Labels to vault-operator deployment

---

operator/pkg/controller/vault/vault_controller.go

| Related tickets | fixes #1521
Checking the expiry of the generated `ca.crt` as well, instead of just checking the `server.crt` expiry time.
See #1521 for details.

operator: fix expiry detection for CA.crt

---

operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

operator: proper context propagation in k8s calls

---

charts/vault-operator/Chart.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault/Chart.yaml

charts: 1.15 release

---

charts/testing.yaml

fix chart testing branch

---

.github/workflows/ci-config-crud-e2e.yml
.gitignore
internal/vault/audits.go
internal/vault/auth_methods.go
internal/vault/identity_groups.go
internal/vault/operator_client.go
internal/vault/plugins.go
internal/vault/policies.go
internal/vault/secrets_engines.go
internal/vault/startup_secrets.go
scripts/validate-config-crud/validate-config-crud.sh
scripts/validate-config-crud/vault-config.yml

| Related tickets | #1503, #1513, #1514, #1519, #1520, #1532, #1535
This PR wraps and finalizes the config purge feature.
I've written a bash script and Github Actions workflow that test the config CRUD to make sure we don't introduce any breaking changes.
No new code is expected but could be bug fixes or code tidy up to keep the code consistent across config sections (audit, auth, secrets, etc.)

configurer: Finalize config purge feature

---

internal/injector/injector.go
internal/injector/injector_test.go
pkg/webhook/common.go
pkg/webhook/configmap.go
pkg/webhook/object.go
pkg/webhook/secret.go

| Related tickets | fixes #1536 
Making the caching object (pod, secret, configmap, etc...) level (it wanted to be like that, but was broken), and also fixing it for using the same path multiple times inlined.
It was broken.

fix very much broken secret caching

---

charts/vault-operator/Chart.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault/Chart.yaml

| Related tickets | fixes #1547 

charts: fix charts version to v2

---

.github/workflows/ci.yml

| Bug fix?        | no 
| Related tickets | #1551 

build: fix git checkout action vs chart-testing

---

.circleci/config.yml
operator/deploy/multi-dc/test/cr-primary.yaml
operator/deploy/multi-dc/test/cr-secondary.yaml
operator/deploy/multi-dc/test/cr-tertiary.yaml
operator/deploy/multi-dc/test/multi-dc-raft.sh

ci: improve metallb based multi-dc-raft local test

---

.github/workflows/codeql-analysis.yml

it has no write access to upload results

codeql: remove push trigger

---

internal/vault/auth_methods.go

| Related tickets | fixes #1581
Convert `map[interface{}]interface{}` to `map[string]interface{}` before sending the config to Vault API.
That's because the config data can have a sub dict (like `provider_config` in JWT/OIDC).
Without this conversion, Vault API will retrun the following error:
```
json: unsupported type: map[interface {}]interface {}
```
This issue has been already fixed in #1247 however, it was removed (unintentionally) in the refactoring of v1.5 which caused #1581.

fix: auth config data sub dict type

---

main-targets.mk

ci: fix broken golangci installation

---

charts/vault-operator/Chart.yaml
charts/vault-operator/crds/crd.yaml
hack/acceptance-test.sh
main-targets.mk
operator/deploy/cr-statsd.yaml
operator/deploy/crd.yaml
operator/pkg/apis/vault/v1alpha1/vault_types.go
operator/pkg/controller/vault/vault_controller.go

| Related tickets | https://github.com/banzaicloud/bank-vaults/issues/1623
Allow to change statsd configuration
Hardcoded statsd configuration
https://github.com/banzaicloud/bank-vaults/blob/main/operator/pkg/controller/vault/vault_controller.go#L1526-L1531
None
None

chart/operator: allow to change statsd configuration

---

charts/vault-operator/Chart.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault/Chart.yaml

charts: release 1.16

---

charts/vault-operator/Chart.yaml
charts/vault-operator/templates/deployment.yaml
charts/vault-operator/templates/service.yaml
charts/vault-operator/templates/servicemonitor.yaml
charts/vault-operator/values.yaml

| Q               | A                                                                                                                                                  |
| --------------- | -------------------------------------------------------------------------------------------------------------------------------------------------- |
| Bug fix?        | yes                                                                                                                                                |
| New feature?    | no                                                                                                                                                 | …

operator: fix helm chart ServiceMonitor

---

.github/workflows/helm.yml

| Related issues | #1741
Fixed Helm chart path in the chart release Github Action, also added possibility to release charts with dev tag.
Helm chart release CI pipeline is currently broken, also it would be nice if new charts could be tested via dev tagged versions if there is a need for it.

Fix helm release Github Action

---

.licensei.toml
charts/README.md
charts/vault-operator/Chart.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault/Chart.yaml

Release 1.17.0 chart versions.

Release 1.17

---

.github/workflows/ci.yml

| Related tickets | fixes #1765 
Envtpl install broke a few days ago, we need to fix onto a concrete version instead of relying on the main branch.
See: https://github.com/banzaicloud/bank-vaults/actions/runs/3929310716/jobs/6735142580

multi-dc-test: fix envtpl install

---

charts/README.md
charts/vault-operator/Chart.yaml
charts/vault-secrets-webhook/Chart.yaml
charts/vault/Chart.yaml

Release 1.18.0 chart versions.

Release 1.18

---

charts/vault-secrets-webhook/Chart.yaml
charts/vault-secrets-webhook/templates/apiservice-webhook.yaml

Signed-off-by: Djerfy <djerfy@gmail.com>
| Related tickets |
Improve error message, required certificate values
When the configuration is bad, it's the same message

feat: improve required values

---

charts/vault/Chart.yaml
charts/vault/values.yaml

There is a minor typo in the Helm chart
I noticed the small error, so decided to make a PR to fix it
None
- None

Fix minor typo

---

.github/workflows/helm.yml

Fixed GHA Helm version check to exactly match chart name.
To avoid mismatching other chart's versions.

ci(GHA): fixed Helm version check

---

README.md

Delete reference to commercial support from README

---

ADOPTERS.md

Added PhishLabs to adopters list.
- ~Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)~

feat: added PhishLabs to adopters list

---

ADOPTERS.md

Add PITS Global Data Recovery Services to adopters list

---

.github/workflows/ci.yaml
flake.lock

ci: apply flake updates

---

e2e/validate-config-crud/test.sh
e2e/validate-config-crud/vault-config.yaml

| Related tickets | fixes #1996 
Extend e2e tests with checking the case sensitivity of startupSecrets and testing with v1 and v2 kv secrets engines.
There was a new feature (#1920) that should be tested and an issue (#1990) that could have been caught.

Add e2e test startupSecrets cases

---

.github/workflows/artifacts.yaml
Dockerfile

feat: add back softhsm as a separate stage

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md

Add PR template
Also update outdated versions in issue template

docs: Add PR template

---

.licensei.toml

Reverts bank-vaults/bank-vaults#2123

Revert "fix(licensei): add busl-1.1 to approved list"

---

.github/ISSUE_TEMPLATE/config.yml

Update Slack URL to https://outshift.slack.com/messages/bank-vaults

docs: Update Slack URL

---

README.md

added OpenSSF best practices badge
Fixes [#2231](https://github.com/bank-vaults/bank-vaults/issues/2231)

docs: added OpenSSF best practices badge

---

.golangci.yml
cmd/bank-vaults/metrics.go
internal/vault/auth_methods.go
internal/vault/operator_client.go
internal/vault/policies.go
internal/vault/secrets_engines.go
pkg/kv/dev/dev.go
pkg/kv/hsm/hsm.go
pkg/kv/k8s/k8s.go

This PR enables and fixes lint issues.
Some issues are suppressed with `//nolint` comment.

fix: gocritic lint issues; enable some linters

---

.github/workflows/checks.yaml

Adds a Github Action step that verifies PRs by checking for merge commits

feat: verify pull request

---

.licensei.toml
Makefile
cmd/bank-vaults/gen_docs.go
go.mod
go.sum

Enables generating CLI docs via `make gen-docs`.

dev: add gen-docs command

---

.github/workflows/ci.yaml
Makefile
README.md

chore: update makefile

---

cmd/bank-vaults/configure.go
cmd/bank-vaults/gen_docs.go
cmd/bank-vaults/init.go
cmd/bank-vaults/main.go
cmd/bank-vaults/metrics.go
cmd/bank-vaults/unseal.go
cmd/template/main.go
flake.lock
go.mod
internal/vault/audits.go
internal/vault/auth_methods.go
internal/vault/identity_groups.go
internal/vault/operator_client.go
internal/vault/plugins.go
internal/vault/policies.go
internal/vault/secrets_engines.go
pkg/kv/hsm/hsm.go
pkg/kv/multi/multi.go

Fixes #2261 
Replace `sirupsen/logrus` logging package with `log/slog`.
Still figuring out `json` logging...
Logs with logrus (from `configurer` pod):
```json
{"level":"info","msg":"vault metrics exporter enabled: :9091/metrics","time":"2023-11-29T08:26:51Z"}                                                                                    
{"level":"info","msg":"watching directory for changes: /config/vault-configurer/","time":"2023-11-29T08:26:51Z"}                                                                        
{"level":"info","msg":"applying config file : /config/vault-configurer/vault-config.yml","time":"2023-11-29T08:26:51Z"}                                                                 
{"level":"info","msg":"checking if vault is sealed...","time":"2023-11-29T08:26:51Z"} …
```

feat: switch from logrus to slog

---

internal/vault/secrets_engines.go

After the vault update, we faced tuning and mounting error(after the upgrade to 14.4) due to Google storage  limit.
The code changes add an exponential backoff mechanism to the process of mounting a secret engine within the vault service. It enhances the system resiliency by reattempting to add or tune a secret engine into vault in case of failures within defined minimum and maximum time intervals. It finally exits after several unsuccessful attempts reaching the maximum backoff time.
Fixes #2449
```
{"level":"error","msg":"error configuring vault: error configuring secret engines for vault: error adding secrets engines: error tuning llm_api in vault: Error making API request.\n\nURL: POST https://vault.vault:8200/v1/sys/mounts/mount_name/tune\nCode: 400. Errors:\n\n* 1 error …
```

feat: Add retry logic to vault secret engine mount process

---

ADOPTERS.md
README.md

Adds usage example and adopter

docs(usage): add usage and adopter

---

cmd/bank-vaults/common.go
cmd/bank-vaults/main.go
go.mod
go.sum
pkg/kv/oci/oci.go
pkg/kv/ocikms/ocikms.go

This PR, add support for OCI Unseal method. It used the same approach as GCS.
See PR bank-vaults/vault-operator#457 for CRD integration

feat: Add Support for Oracle Cloud Infrastructure

---

ADOPTERS.md
Makefile
README.md

- This PR changes `Vault-env` and `vault-secrets-webhook`references to secret-init and secrets-webhook references.

feat: switch to generic secrets webhook

---

cmd/bank-vaults/main.go
cmd/template/main.go

chore: change version to dev

---

internal/vault/secrets_engines.go

This PR adds ability for the common name of the certificates to be signed to be templated
Fixes #3086
Certificate signing policy with templated allowed_domain:
```
secrets:
[...]
- type: pki
path: REDACTED
description: PKI Backend
config:
default_lease_ttl: REDACTEDh
max_lease_ttl: REDACTEDh
configuration:
config:
- name: urls
crl_distribution_points: https://REDACTED
issuing_certificates: https://REDACTED
roles:
- name: test
allow_glob_domains: true
allow_localhost: false
allow_bare_domains: true
allowed_domains_template: true
allowed_domains:
- system:node:{{identity.entity.aliases.${ accessor `aws-iam/` }.metadata.inferred_hostname}}
enforce_hostnames: false
[...]
```
Check result as Vault admin:
```
$ vault read "$MOUNT_PATH/roles/test"
Key                                   Value
--- …
```

feat: templated policy support for PKI

---

internal/vault/operator_client.go

If the root key is not stored in the bucket, cluster is not getting up during an initial bootsrap if the root key is not in the gcs bucket. With the current code, a second pod will assume that it's actually a first one to exist and it will panic once it notices the vault-unseal-0 key in the bucket.
In this PR we try to fix it by trying to contact
the vault leader in case the root key doesn't exist -> this is a valid config option.
Fixes #(issue)
https://github.com/bank-vaults/bank-vaults/issues/3309

fix: secondary pod tries to initalize Vault when vault-root key is not stored
